window.ANDY_ANALYSIS_BATCH14 = (() => {
  const rows = `
115759|Lilyshay|Dog|Torn-nail injury treated with bandage care and a minimal medication plan|1|The veterinarian kept the plan narrow and only layered on more pain control if the dog started limping.|The discussion focused on cleaning the nail, protecting it, and watching for worsening discomfort rather than overbuilding the discharge plan.|staged,risk,min
115987|Isabella Rose|Dog|Allergy and ear-itch visit with diet control, Cytopoint, and cheaper product sourcing|1|The veterinarian managed the chronic itch problem with practical options the owner could maintain at home.|The discussion combined allergy control with over the counter ear-cleaner sourcing and a realistic long-term plan instead of pushing a larger workup.|options,pharmacy,staged
116128|Tabby|Cat|Itchy-skin visit where heart concerns narrowed the medication choices|1|The veterinarian adjusted the plan around the heart-murmur risk instead of reflexively reaching for the usual steroid path.|The discussion contrasted safer symptom control with more typical itch treatment and explained why the heart finding changed the calculus.|options,staged,risk,rep
116338|Rambl|Dog|Fearful-dog vaccine visit with rabies now and the rest deferred to the neuter day|1|The veterinarian kept the visit intentionally small because stress tolerance was the limiting factor, not medical complexity.|The discussion used staged vaccine timing and day-of-neuter bloodwork rather than forcing a full preventive plan into one difficult visit.|staged,min,nooption
116411|Summer|Dog|Hair-loss and endocrine-concern visit with stepwise bloodwork before bigger conclusions|1|The veterinarian avoided overcalling the case and used a measured first step to sort trauma, thyroid disease, and Cushings possibilities.|The discussion kept the next move on targeted bloodwork and explained why guessing at the cause too early would not help.|options,staged,risk,min
116462|Beau|Dog|Mobility decline visit with pain-first treatment before expanding the workup|1|The veterinarian started with anti-inflammatory and pain support because the dog still fit a lower-intensity orthopedic flare.|The discussion used supportive treatment first and left bloodwork or imaging for later if the dog failed to bounce back quickly.|options,staged,min
116494|Green|Dog|Truncated chronic-cough intake without a complete exam-room decision sequence|1|This capture cut off before a usable medical branch or owner-facing options discussion developed.|The available audio stayed in history-taking and team chatter, so it was not strong enough to code as a real cost-of-care conversation.|nooption
116507|Coco|Dog|Pot-bellied-dog workup with brief ultrasound, rough pricing, and an anti-inflammatory trial|1|The veterinarian built a cost-aware diagnostic ladder instead of sending the owner directly to the most expensive imaging path.|The discussion contrasted an in-house look with a formal radiology ultrasound, used rough pricing openly, and still protected against missing a more serious endocrine problem.|options,money,pay,staged,risk,rep
119566|Sinister|Cat|Recurrent ear-cyst visit with home care now and removal later if it keeps recurring|1|The veterinarian framed surgery as a later step and kept the immediate plan conservative because the lesion was still manageable.|The discussion combined ear cleaning, dietary support, and the possibility of removing the cyst during a future dental if it kept coming back.|options,staged,min
119689|Leo|Dog|Rabies-observation clearance visit without a larger treatment branch|1|This was a protocol-driven visit rather than a meaningful options encounter.|The discussion stayed on legal clearance and routine follow-up rather than on competing medical paths.|nooption
119734|Gypsy|Dog|UTI and hind-limb-limp visit with vulvoplasty priced as the bigger long-term fix|1|The veterinarian treated the urinary flare and explained the more definitive but more expensive structural option without overselling it.|The discussion used a staged UTI plan, discussed hooded-vulva anatomy, and gave a realistic surgery range while also addressing the separate limp problem conservatively.|options,money,staged,risk,rep
120142|Loki|Dog|IMHA emergency with hospitalization, transfusion, and referral costs discussed plainly|1|The veterinarian balanced urgency with transparent cost framing and made the local-versus-specialty tradeoff explicit.|The discussion compared in-hospital stabilization and transfusion costs against specialty referral expense while keeping survival needs in the foreground.|options,money,pay,staged,risk,rep
120240|Napa|Dog|Corneal-ulcer eye visit with stain-first treatment and a narrow recheck plan|1|The veterinarian kept the plan proportional to the eye findings and used the stain result to guide treatment intensity.|The discussion centered on medications, follow-up, and ulcer risk rather than on a broader diagnostic branch.|staged,risk,min,nooption
120290|Pug|Dog|Routine preventive visit without a meaningful treatment-options branch|1|This read as routine wellness care rather than a real cost-of-care or decline conversation.|The discussion stayed in vaccine and maintenance territory and did not open a substantial alternative-path decision.|nooption
120439|Bitty|Cat|Weight-loss and systemic-concern visit with bloodwork first and GI disease left on the table|1|The veterinarian built the case stepwise and used early diagnostics to separate endocrine disease from GI disease or cancer.|The discussion resisted premature conclusions and kept the next move on labs and later abdominal imaging if the trend continued.|options,staged,risk,rep
120654|Trigg|Dog|Rapid mobility-decline visit with medical management, MRI referral, and euthanasia all discussed|1|The veterinarian laid out the hard spectrum honestly and still gave the owner a reasonable trial-therapy path first.|The discussion contrasted specialist MRI and possible surgery with anti-inflammatory and gabapentin treatment at home, while also naming euthanasia as the fallback if function did not return.|options,staged,risk,rep
120680|Bella|Dog|First-heat recheck with motion-sickness choices and spay timing guidance|1|The veterinarian used the visit to make a simple reproductive plan and to offer practical anti-nausea choices for the car.|The discussion compared meclizine with stronger prescription support and tied the eventual spay to the end of the heat cycle rather than rushing it.|options,staged,min
120721|Toby|Dog|Horners and vestibular-sign visit with medication pricing and CT reserved for nonresponders|1|The veterinarian treated the likely inflammatory or inner-ear problem first and held advanced imaging for failure to improve.|The discussion used blood pressure screening, staged medication, and a rough price conversation while preserving CT as the next fork only if the dog stalled.|options,money,staged,risk,rep
120968|Ranger|Dog|Behavior and anxiety visit with medication, training, and home-context framing|1|The veterinarian treated the behavior issue as a management problem that had to fit the household rather than as a single-drug problem.|The discussion combined Prozac, training, and trigger context and kept the advice grounded in what the owners could actually do at home.|options,staged,barrier,rep
121049|Wednesday|Cat|Dental-pain visit with comfort medication now and a fuller dental plan later|1|The veterinarian kept the immediate goal on comfort and nutrition while still pushing the cat toward definitive dental work.|The discussion used gabapentin, softer food, and a near-term dental plan rather than pretending the damaged mouth could be ignored.|options,staged,risk,min
121300|Cooper|Dog|Chronic GI case with biopsy versus empirical treatment framing|1|The veterinarian explained the diagnostic gold standard but still offered a lower-intensity path that could help without a biopsy first.|The discussion contrasted intestinal biopsy with medication-based management and made clear that inflammatory bowel disease and GI lymphoma can look very similar up front.|options,staged,risk,rep
121411|Milly|Dog|Chicken-wing ingestion visit with conservative management before bigger intervention|1|The veterinarian used the immediate exam and history to justify a smaller first step rather than rushing into maximal care.|The discussion mixed home feeding guidance, monitoring, and escalation triggers with the option to pursue more imaging if recovery stalled.|options,staged,risk,rep
121867|Bo|Dog|Progressive neck-disc concern with MRI referral versus medical treatment at home|1|The veterinarian acknowledged the best-case specialist answer but still supported a reasonable home-therapy path when surgery was off the table.|The discussion contrasted MRI and neurology referral against Rimadyl, gabapentin, and strict rest while carefully explaining what neurologic function was still intact.|options,staged,risk,rep
121927|Ben|Cat|Overgrooming visit with steroid-first management before deeper behavior medication|1|The veterinarian started with the simpler and more common pathway instead of jumping directly to chronic anxiolytics.|The discussion treated the belly hair loss as a branch between allergy-type inflammation and behavioral overgrooming and used the lower-friction option first.|options,staged,risk
122041|Logan|Dog|Wellness visit that uncovered painful infected teeth and a secondary luxating-patella discussion|1|The veterinarian used the exam to surface the truly important problem and kept the incidental orthopedic finding on a watchful track.|The discussion pushed a dental with likely extractions while explaining why the kneecaps did not need surgery unless the dog started limping persistently.|options,staged,risk,rep
124716|Bitty|Cat|Result callback that narrowed the next step to abdominal ultrasound|1|The veterinarian kept the recommendation focused by using the bloodwork to point toward gut protein loss rather than broadening the plan blindly.|The discussion tied the low protein to IBD or GI lymphoma and used ultrasound as the next responsible fork in the workup.|options,staged,risk
127179|Mabel|Dog|Bloody-urine visit with antibiotics first and imaging held for nonresponders|1|The veterinarian used a pragmatic first-line UTI plan while still naming the structural causes that might need later imaging.|The discussion combined treatment, vulvar hygiene, and a future x-ray branch instead of going immediately to more diagnostics.|options,staged,min
127195|Harper|Dog|Groin-laceration repair visit that stayed on the straightforward wound-management path|1|The veterinarian treated this as a direct repair problem rather than opening unnecessary branches.|The discussion focused on sedation, suturing, home medications, and wound protection because the injury already dictated the appropriate path.|staged,risk,min,nooption
127196|Lucky|Dog|Drain-site reopening with staples, stitches, and direct price comparison|1|The veterinarian made the lower-cost repair path explicit instead of assuming one closure method without discussion.|The discussion compared staples with stitches, gave clear price points, and still explained the tissue-healing tradeoffs around each option.|options,money,pay,staged,risk,rep
127197|Subie|Dog|Seizure-pattern visit with monitoring, Keppra, and liver workup held in the same frame|1|The veterinarian kept the case on a rational neurologic ladder rather than overcommitting to medication after a single pattern description.|The discussion contrasted watchful waiting with seizure medication and linked future escalation to recurrence, clustering, or evidence of a liver-related trigger.|options,staged,risk,rep
127198|Legend|Dog|Puppy rectal-prolapse and parasite visit with deworming and simple home backup steps|1|The veterinarian used a minimum-responsible plan that matched a common young-dog problem.|The discussion centered on deworming, probiotics, and sugar-water home care if the prolapse reappeared rather than on a bigger intervention sequence.|options,staged,min
127229|Ben|Dog|Fracture recheck with low-cost x-ray and possible reset only if alignment worsened|1|The veterinarian kept the next move small and priced it cleanly because the leg was already healing in a usable position.|The discussion used a modest recheck radiograph to decide whether continued splinting was enough or whether the alignment had drifted too far.|options,money,staged,risk,rep
127230|Daisy|Dog|Short recheck focused on the scheduled shot and blood draw only|1|This was too narrow and maintenance-oriented to count as a real options conversation.|The discussion stayed on the planned recheck tasks without opening a competing treatment path.|nooption
127232|Mishio|Dog|Brief urinary and hair-regrowth recheck without a broader decision branch|1|This was a straightforward improvement visit rather than a new care-spectrum encounter.|The discussion centered on a urine recheck and simple topical-home-care reassurance.|nooption
128177|Flipsy|Dog|Possible partial airway obstruction with monitoring versus immediate scoping|1|The veterinarian used the dog's stable breathing to justify a cautious first step without hiding the risk of a true obstruction.|The discussion contrasted observation and repeat imaging with a more invasive scope and kept aspiration pneumonia in view as the likely downstream complication.|options,staged,risk,rep
128179|Flipsy|Dog|Duplicate-like airway-obstruction monitoring case with invasive scope held in reserve|1|This duplicate-like capture preserved the same conservative-but-alert reasoning as the paired file.|The discussion again balanced hospitalization and observation against more aggressive visualization of the airway if breathing worsened or the repeat films failed to improve.|options,staged,risk
128189|Flipsy|Dog|Duplicate-like airway-obstruction monitoring case with repeat imaging logic|1|This duplicate-like capture showed the same staged monitoring logic from the earlier Flipsy files.|The discussion kept the decision anchored to stability first, repeat x-rays later, and intervention only if the apparent partial obstruction stopped behaving conservatively.|options,staged,risk
129374|Ben|Dog|Duplicate-like fracture recheck with an inexpensive x-ray fork|1|This duplicate-like capture preserved the same low-cost reassessment logic from the earlier leg case.|The discussion again used a small recheck investment to decide whether continued conservative management was still safe.|options,money,staged,risk
130282|Zoey|Dog|Acute GI-upset visit with symptom control first and imaging if recovery stalled|1|The veterinarian treated the dog supportively because the presentation still fit a common stomach upset pattern.|The discussion layered anti-nausea care, probiotics, and monitoring with the option to escalate to x-rays if the dog stopped improving.|options,staged,risk,min
130283|Zoey|Dog|Duplicate-like GI-upset visit with conservative care and escalation triggers|1|This duplicate-like capture kept the same symptom-first logic from the paired Zoey file.|The discussion again used supportive treatment and clear red flags to decide whether a larger workup would become necessary.|options,staged,risk,min
130345|Rocket|Dog|Foot-laceration visit with local repair if possible and stronger restraint only if needed|1|The veterinarian tried to match the repair intensity to what the wound and dog would tolerate.|The discussion used local management, cone use, and oral medications while leaving heavier intervention for a dog that could not be handled safely enough for the simpler path.|options,staged,risk,min
130376|Poe|Dog|Travel-paperwork visit centered on vaccine timing and certificate sequencing|1|This was a logistics-heavy preventive visit rather than a substantive illness-options encounter.|The discussion stayed on the timing needed for Korea travel paperwork and routine vaccine compliance.|staged,nooption
130377|Poe|Dog|Duplicate-like travel-paperwork visit without a wider medical branch|1|This duplicate-like capture preserved the same timing-focused travel guidance from the paired file.|The discussion remained on certificate windows and vaccine sequencing instead of on a competing treatment plan.|staged,nooption
130441|Jack|Cat|Hairball-versus-obstruction visit with x-rays used to separate a familiar problem from a bigger one|1|The veterinarian refused to assume the cat was having a routine hairball episode without first checking whether something more serious was stuck.|The discussion paired x-rays with the possibility of lactulose and airway review and kept the plan proportional to what the images might show.|options,staged,risk
130449|Jack|Cat|Hairball workup that pivoted into feline-asthma recognition after the x-rays|1|The veterinarian used the imaging to reframe the case from a presumed hairball problem to probable asthma without overreacting to the gastric air.|The discussion walked through the films, explained why the lungs mattered more than the small possible hairball, and set up a different chronic-care direction from there.|options,staged,risk,rep
130472|Dexter|Cat|Kitten-diarrhea visit with fecal-first reasoning instead of blind deworming|1|The veterinarian treated parasites as the leading cause but still chose a data-first approach because the standard dewormer would miss some causes anyway.|The discussion used probiotics, fluids, and fecal testing before selecting a treatment, which kept the plan both conservative and specific.|options,staged,risk,min
130506|Wrigley|Dog|Severe vaccine-reaction visit with immediate stabilization and future premedication planning|1|The veterinarian treated the reaction aggressively while still turning the conversation toward how vaccines could be handled more safely later.|The discussion layered Benadryl, steroids, epinephrine, cooling, and follow-up prevention advice instead of stopping at a single rescue step.|options,staged,risk,rep
130509|Cecil|Cat|Vomiting-blood visit with gastritis treatment instead of a larger emergency escalation|1|The veterinarian used the normal diagnostics to justify a focused upper-GI treatment plan rather than building a broader speculative workup.|The discussion centered on likely esophageal or gastric irritation and paired that explanation with targeted medication rather than maximal intervention.|options,staged,risk,rep
130515|Michael|Dog|Morning-bile vomiting visit solved with feeding changes and short symptom support|1|The veterinarian treated the pattern like a classic empty-stomach problem and kept the plan intentionally small.|The discussion used meal timing, anti-nausea support, and simple home adjustments instead of opening a larger diagnostics branch.|staged,min,nooption
130520|Bear|Dog|Back-pain flare managed conservatively with rest and home pain control|1|The veterinarian used a minimum-responsible plan because the presentation still fit a routine orthopedic or spinal pain flare.|The discussion kept the care on Rimadyl, gabapentin, and strict rest while explaining why the dog still needed watching for neurologic deterioration.|staged,risk,min,nooption
130523|Goliath|Cat|Broken-tooth visit with immediate extraction versus waiting for the scheduled dental|1|The veterinarian explained the timing tradeoff instead of treating the damaged tooth as either trivial or an absolute emergency.|The discussion paired pain control with a choice between moving the extraction sooner or managing briefly until the planned dental slot.|options,staged,risk,min
130528|Addison|Dog|TPLO recheck with seroma-versus-infection reasoning and stepwise response|1|The veterinarian treated the postop swelling as a differential diagnosis problem rather than assuming failure of the surgery outright.|The discussion used fluid sampling, ice, medication decisions, and watchful reassessment to separate irritation from true infection.|options,staged,risk,rep
130533|Ellie|Dog|Severe jaundice and anemia case with hospitalization, transfusion, and euthanasia all in frame|1|The veterinarian handled the case as a life-or-death discussion and still made the tradeoffs plain enough for the owner to understand.|The discussion walked through local stabilization, specialty referral, approximate costs, and the possibility that euthanasia could become the humane endpoint if the dog could not be turned around.|options,money,pay,staged,risk,rep
130549|Lamb chop|Dog|Acute vomiting-and-diarrhea visit with GI-biome food, metronidazole, and fluids|1|The veterinarian escalated just enough to support hydration and intestinal recovery without building a large workup immediately.|The discussion layered an anti-diarrheal antibiotic, a more targeted GI diet, and subcutaneous fluids because the dog still fit a supportive-care pattern.|options,staged,risk,min
130555|Bentley|Dog|Anal-gland visit that stayed on the straightforward expression path|1|This was a direct maintenance problem rather than a real branching care discussion.|The visible exam-room decision was simply whether the glands needed to be expressed, which did not create a broader options structure.|nooption
130565|Finch|Cat|Chronic vomiting and weight-loss visit framed as IBD versus GI lymphoma|1|The veterinarian named the two likeliest chronic gut paths and still kept the first move on a practical medication trial rather than a biopsy-first approach.|The discussion used steroids, probiotics, and diagnostic restraint to manage a case that could only be fully separated with invasive sampling.|options,staged,risk,rep
130731|Duke|Dog|Mass-and-lameness visit with cytology first and orthopedic pain managed conservatively|1|The veterinarian treated the skin mass and the subtle lameness as two different problems and scaled each appropriately.|The discussion used needle sampling to rule out a mast-cell tumor while also framing the front-leg issue as likely early arthritis rather than a surgical emergency.|options,staged,risk,rep
130812|Bob|Cat|Constipation visit with x-rays used to decide between home management and a bigger cleanout|1|The veterinarian used imaging as the fork between mild constipation care and a more intensive disimpaction path.|The discussion kept the next move on radiographs and severity assessment before deciding whether outpatient treatment was enough.|options,staged,risk,rep
130910|Ice|Dog|Compulsive paw-licking visit with itch treatment and enrichment instead of a single-cause story|1|The veterinarian treated the behavior as a mixed medical-and-behavioral problem rather than forcing it into one category.|The discussion combined Apoquel, motion-sickness support, and puzzle-feeder style management with owner-context reasoning about boredom and compulsive licking.|options,staged,barrier,rep
131005|Cici|Dog|Kennel-stress diarrhea and stiffness visit with supportive care shaped by the boarding context|1|The veterinarian linked the dog's symptoms to environment and handling stress instead of overmedicalizing the whole visit.|The discussion mixed GI support, orthopedic assessment, and routine wellness work while keeping the kennel context central to what probably triggered the flare.|options,staged,risk,barrier
131130|Bailey|Dog|Mild cough visit with conservative tracheitis-style treatment and simple home add-ons|1|The veterinarian kept the care low intensity because the dog still fit a mild airway irritation picture.|The discussion used cough tablets, antihistamine options, and red-flag guidance rather than opening a larger cardiopulmonary workup immediately.|options,staged,risk,min
131197|Gomer|Dog|Drooling and salivary-gland concern visit with anti-nausea treatment before riskier escalation|1|The veterinarian took the least invasive useful step first instead of racing toward surgery or long-term neurologic medication.|The discussion used Cerenia and symptom reassessment while keeping more invasive or chronic options in reserve if the odd episodes continued.|options,staged,risk,rep
131544|Mikey|Dog|Resolved paw-and-skin recheck without a meaningful new treatment branch|1|This was an improvement visit rather than a fresh options encounter.|The discussion mainly confirmed that the owner's current management had worked and did not open a broader decision set.|nooption
131666|Indy|Dog|Giant-breed puppy wellness visit with breathing concern folded into staged preventive care|1|The veterinarian used routine care to address the owner's worry without turning a mild concern into a major workup.|The discussion kept the plan on vaccines, growth-stage decisions, and monitoring the odd sleep-breathing pattern rather than escalating prematurely.|options,staged,risk
131806|Coco|Dog|Ear-maintenance visit where the problem stayed on the simple cleaning path|1|The veterinarian treated the ears as a maintenance issue rather than as an active infection requiring a bigger plan.|The discussion focused on cleaner use and low-intensity home upkeep because there was not much disease left to solve.|min,nooption
132028|Marty|Cat|Chronic-URI visit with repeat Convenia and GI support instead of a wider workup|1|The veterinarian used the prior response to justify a repeat supportive plan before building something more complex.|The discussion kept the treatment on antibiotic support and probiotics because the cat's pattern still fit an upper-respiratory flare rather than a brand-new diagnostic mystery.|options,staged,min
132046|Tucker|Dog|Cryptorchid-neuter consult with timing and surgery-complexity explained plainly|1|The veterinarian framed the decision around maturity and surgical difficulty rather than pushing immediate intervention on a still-young dog.|The discussion used staged timing, behavior context, and abdominal-retained-testicle risk to set up the eventual neuter plan.|options,staged,risk,min
132087|Astrid|Dog|Serious-eye-disease visit with ophthalmology held as the next step if medical therapy failed|1|The veterinarian treated the uveitis-like problem urgently but still gave the owner a reasonable first-line treatment path.|The discussion combined pressure data, stain results, topical medications, and referral logic without pretending the eye could simply be watched casually.|options,staged,risk,rep
133879|Discgo|Dog|Eye-discharge visit with stain-first branching and routine vaccines layered in|1|The veterinarian used the corneal stain to decide between soothing steroid-containing drops and a safer ulcer protocol.|The discussion kept the visit simple and guideline-driven because the eye problem still fit a common conjunctivitis-versus-scratch branch.|staged,min,nooption
133884|Discgo|Dog|Duplicate-like eye-discharge visit with the same stain-first treatment logic|1|This duplicate-like capture preserved the same straightforward conjunctivitis-versus-ulcer reasoning from the paired file.|The discussion again kept the decision tree on stain result first and medication choice second.|staged,min,nooption
133994|Kaner|Dog|Dry-eye recheck with more frequent Optimmune and continued lubrication|1|The veterinarian adjusted chronic therapy rather than opening a larger branch because the eye was improving, just not fast enough.|The discussion centered on tear support, medication frequency, and staying the course on a manageable chronic eye problem.|options,staged,min
134001|Kaner|Dog|Duplicate-like dry-eye recheck with chronic-medication adjustment only|1|This duplicate-like capture preserved the same adherence-and-frequency logic from the paired eye recheck.|The discussion stayed on getting more tear support out of the current regimen rather than escalating to a new pathway.|options,staged,min
134145|Owen|Dog|Grooming-intolerance visit with oral sedation first and stronger sedation later if needed|1|The veterinarian treated the grooming issue as a staged handling problem and respected the dog's cardiac risk at the same time.|The discussion contrasted home premedication with heavier future sedation and explained why a murmur made the lighter path worth trying first.|options,staged,risk,rep
134197|Prince|Dog|Routine wellness visit without a meaningful options branch|1|This stayed in preventive-care territory rather than becoming a real treatment-spectrum encounter.|The visible discussion focused on routine screening, vaccines, and stable day-to-day management.|nooption
134333|Opie|Cat|Recurrent vomiting visit with IBD or GI lymphoma treated empirically because of a heart murmur|1|The veterinarian used the classic chronic-cat vomiting framework but changed the drug choice to fit the cardiac limitation.|The discussion moved from prednisolone to budesonide, kept bloodwork retrieval in play, and used probiotics and diet as part of the lower-friction path.|options,staged,risk,rep
134451|Gypsy|Dog|Short intake-style urinary and limp note without a complete doctor-owner decision sequence|1|This capture never developed into a full exam-room treatment conversation and stayed mostly at the presenting-problem stage.|The visible content documented the working concerns and the plan to run urine first, but not enough of the final conversation to code it as a full branching case.|nooption
134775|Sumo|Cat|Routine annual and chronic-URI maintenance visit without a larger medical branch|1|This was a stable maintenance encounter rather than an options-heavy discussion.|The conversation stayed on preventive care, a refill-style steroid plan, and ordinary home upkeep.|nooption
135046|Jade and Hobbes|Cat|Urinary-accident and dental-pain visit with in-house urine testing and dental care decisions|1|The veterinarian used the bladder findings and the mouth exam to keep both problems on clear, manageable next steps.|The discussion contrasted in-house versus send-out urine answers, identified painful teeth, and built a practical plan around both issues without overcomplicating the visit.|options,staged,risk,rep
135082|Jade and Hobbes|Cat|Duplicate-like urinary-and-dental visit with the same practical testing fork|1|This duplicate-like capture preserved the same urine-first and dental-follow-up reasoning as the paired file.|The discussion again centered on quickly identifying the urinary culprit while recognizing that the mouth pain also deserved a later definitive fix.|options,staged,risk
135153|Stella|Dog|Very short GI-intake capture without a full exam-room recommendation sequence|1|This file was too truncated to show a reliable branching treatment discussion.|The visible audio stayed at the presenting-problem stage around vomiting and profuse diarrhea, so it was not strong enough to code as a complete options encounter.|nooption
135159|Stella|Dog|Duplicate-like GI-intake capture without a usable completed care discussion|1|This duplicate-like file was likewise too truncated to support a full treatment-path coding decision.|The available content documented the complaint but not the veterinarian's completed plan in a way that would support a stronger coding label.|nooption
135237|Wick|Dog|Mild ear-and-allergy visit kept on short-course local treatment and calorie guidance|1|The veterinarian kept the problem small and practical because the disease burden was still modest.|The discussion stayed on brief ear medication, weight guidance, and simple home management instead of escalating into a larger allergy workup.|staged,min,nooption
135386|Bella|Dog|Travel-timed UTI visit treated conservatively after ultrasound ruled out stones|1|The veterinarian kept the plan tight because the main structural concern had already been checked and the dog still fit a simple infection pattern.|The discussion used antibiotics and routine chronic-med continuation rather than opening a larger diagnostic branch before travel.|staged,min,nooption
135508|Odie|Dog|Wellness visit with benign-lump reassurance and ongoing murmur monitoring|1|The veterinarian stayed proportional and did not overreact to findings that still looked stable and familiar.|The discussion covered routine maintenance, lump interpretation, and chronic monitoring while leaving room to escalate only if the lesions changed.|options,staged,risk
135583|Roger|Dog|Routine annual visit with food-safety counseling and preventive updates|1|This stayed squarely in maintenance care rather than a real treatment-options conversation.|The main counseling point was to avoid raw-diet risk, with vaccines and ordinary preventive care layered around it.|staged,min,nooption
135705|Hazel|Dog|Acute diarrhea and hematochezia visit with a layered outpatient GI plan|1|The veterinarian matched the plan to a common but messy GI flare and kept hospitalization off the table unless the dog worsened.|The discussion used bland diet, probiotics, anti-nausea medication, and metronidazole with risk framing around what would justify a bigger escalation.|options,staged,risk,min
136209|Lucy|Dog|Senior wellness visit without a substantive treatment branch|1|This was a stable preventive visit rather than a live options conversation.|The discussion stayed on routine screening and maintenance observations, with no major new medical fork opened.|nooption
136464|Wrigley|Dog|Forelimb-lameness visit with x-rays optional and arthritis support used first|1|The veterinarian kept the plan conservative because the pain pattern still fit a common orthopedic aging problem.|The discussion contrasted immediate imaging with anti-inflammatory support and supplements while explaining what signs would justify more diagnostics later.|options,staged,risk,rep
136559|Kayden|Dog|High-risk handling and aggression visit where safety context dominated the plan|1|The veterinarian treated the dog's behavior and household limitations as the main clinical constraint rather than pretending this was a normal annual visit.|The discussion centered on training, muzzle use, safety around other animals and people, and the practical limits of what could be done in the room that day.|barrier,nooption
136721|Cooper|Dog|Severe chronic-ear-disease visit with different treatments assigned to each ear|1|The veterinarian tailored the plan ear by ear instead of flattening the case into one simple label.|The discussion used a long-acting ear medication on one side, cleaner on the other, and steroid extension as a staged attempt to regain control before anything more invasive.|options,staged,risk,rep
143588|Hunter|Dog|Anal-gland abscess visit treated medically instead of immediately lancing|1|The veterinarian kept the care on the less invasive side because the lesion had not yet matured into a drainable pocket.|The discussion combined pain control, antibiotics, cone use, and GI support while explaining why a cut-open approach was not yet the right move.|options,staged,risk,min
143684|Lexus|Dog|Collapse-or-seizure visit with neurology, cardiac, and orthopedic reasoning kept in play|1|The veterinarian treated the event as a differential diagnosis problem and used medication only as a contingency for recurrence.|The discussion balanced syncope, seizure, and mobility explanations and held Keppra as the next step only if the pattern repeated clearly enough.|options,staged,risk,rep
145561|Luke|Dog|Excitement-collapse visit managed with monitoring before chronic seizure medication|1|The veterinarian used the episode pattern to justify watchful tracking rather than immediate long-term drug commitment.|The discussion kept the dog on a monitor-first path while still naming seizure-threshold concern and what escalation would look like later.|options,staged,risk
145644|Shadow|Dog|Papilloma visit with contagiousness counseling and simple watchful waiting|1|The veterinarian treated the lesion as something to respect but not aggressively intervene on.|The discussion focused on avoiding puppies or immunosuppressed dogs, watching for change, and letting the wart run its usual course.|staged,nooption
145725|abe|Dog|Lethargy and abdominal-pain visit with x-rays first and broader testing held in reserve|1|The veterinarian built the case from the most likely painful problem outward instead of loading the owner into a maximal workup immediately.|The discussion used radiographs as the first fork and left combined bloodwork and more diagnostics for whatever the initial picture justified.|options,staged,risk,rep
145847|Nellie|Dog|Routine wellness visit with microchip and small home-care questions only|1|This was preventive maintenance rather than a real alternatives discussion.|The conversation stayed on microchip registry, minor home questions, and ordinary ongoing care.|nooption
145968|Smoochie|Cat|Chronic vomiting and weight-loss visit with heart-safe steroid choice for probable gut disease|1|The veterinarian used the usual IBD-versus-lymphoma framework but changed therapy to fit the cat's murmur and age.|The discussion moved from prior labs to budesonide, chronic gut disease reasoning, and a practical treatment-first path instead of invasive sampling upfront.|options,staged,risk,rep
146080|Apolo|Cat|Young-kitten hind-limb injury visit with x-rays as the clear first step|1|The veterinarian treated this as a direct trauma-assessment problem rather than opening multiple competing branches.|The discussion centered on imaging, fracture or luxation risk, and what would change depending on what the films showed.|staged,risk,nooption
146115|Penelope|Dog|Vaccine visit with sensitivity prevention and seizure-threshold counseling added in|1|The veterinarian used the routine visit to make two practical risk-reduction decisions rather than to build a larger workup.|The discussion covered Benadryl premedication, luxating-patella monitoring, and oral flea-and-tick medication caution in a dog with seizure history concerns.|options,staged,risk
146278|Lucy|Dog|Shoulder-lesion visit with shave-and-inspect first and closure if the deeper look warranted it|1|The veterinarian kept the first move procedural and proportionate instead of assuming the lesion needed the biggest intervention possible.|The discussion used clipping, inspection, and likely staple-plus-medication follow-through while keeping the wound-management logic tight and practical.|options,staged,risk,min
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 14',
      date: '2026-03-19',
      selectionSeed: '20260319-wave14',
      selectionMethod: 'Fourteenth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1300_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
