window.ANDY_ANALYSIS_BATCH18 = (() => {
  const rows = `
256921|Iggy Mae|Dog|Pancreatitis recheck managed with diet transition and supportive home care|1|The veterinarian kept this recurrent GI case on a conservative outpatient track instead of reopening a larger workup.|The discussion focused on sensitive-stomach food, mixing diets carefully, Fortiflora, and watching for another flare.|staged,min,nooption
256943|Pickles|Dog|Tail-drainage surgical note without a usable owner-facing decision sequence|1|This file reads like staff-side discussion around tail disease rather than a clean exam-room options conversation.|The visible content centers on tail infection, culture thoughts, and surgery timing without a clear client recommendation sequence.|nooption
257078|Mama|Cat|Urinary-diet recheck with de-escalation back toward normal food|1|The veterinarian used the clean recheck to step back from the prescription diet rather than extending it unnecessarily.|The discussion focused on a normal urine sample, gradually transitioning off Urinary SO, and watching for recurrence.|staged,nooption
257694|Fuzz and Goofy|Dog|Routine wellness visit with vaccine timing and annual-screening maintenance|1|This was preventive maintenance rather than a real care-spectrum conversation.|The discussion stayed on wellness exams, vaccine timing, and routine bloodwork without a meaningful treatment fork.|nooption
257760|Benji|Dog|Wellness visit with bilious-vomiting advice and vaccine-duration pricing|1|The veterinarian kept the mild stomach issue conservative and only surfaced cost in the preventive-medication choices.|The discussion covered a bedtime snack for morning bile vomiting, optional urine testing, and one-year versus three-year rabies pricing.|money,min,nooption
257795|Lilo|Cat|Vomiting and diarrhea case treated as gastroenteritis after obstruction was ruled out|1|The veterinarian used imaging to clear the dangerous scenario and then kept the case on supportive outpatient care.|The discussion covered reassuring x-rays, anti-nausea medication, fluids, half meals, and warning thresholds if vomiting continued.|options,staged,risk,rep
257819|Nino|Cat|Handling-averse cat moved toward sedation-assisted grooming and future care|1|The veterinarian adapted the plan to the cat's handling barrier instead of forcing routine care in the room.|The discussion covered failed in-room vaccines, gabapentin previsit medication, and grooming under anesthesia for future maintenance.|options,staged,barrier
257938|Ursula Stark|Dog|Giant-breed wellness visit with practical supplement and testing-cost choices|1|The veterinarian kept the prevention plan practical while naming lower-cost ways to handle routine care.|The discussion covered send-out versus in-house heartworm testing, weight-loss counseling, and cheaper human glucosamine or Costco joint-support options.|options,money,pay,staged,rep
258008|Gizmo and Onyx|Cat|Two-cat wellness visit with vaccine pricing and optional thyroid screening|1|This was mainly preventive care with a small optional testing branch and explicit vaccine-cost choices.|The discussion covered one-year versus three-year rabies pricing and an optional thyroid test for the thinner cat.|money,nooption
258009|Gizmo and Onyx|Cat|Duplicate-like wellness capture with the same vaccine and thyroid discussion|1|This appears to preserve the same preventive visit rather than a distinct new treatment conversation.|The visible content repeats the vaccine-duration pricing and optional thyroid-screening logic from the paired file.|money,nooption
258067|Neeko|Dog|Chronic diarrhea case managed with GI support and cleanup before more medication|1|The veterinarian slowed the case down and emphasized practical gut support before reflexively stacking more treatment.|The discussion covered GI Biome, delaying further medication until fecal results, cleanup to avoid reinfection, and later food-transition choices.|options,staged,risk,rep
258087|Booger|Cat|Vomiting-prone cat kept on strict diet control with dental planning in reserve|1|The veterinarian tightened the conservative diet plan and only kept dental escalation in reserve.|The discussion covered staying strict on the ZD diet, watching vomiting response, and planning a dental only if oral inflammation worsened.|options,staged,nooption
258127|Moana|Dog|Mammary-mass crisis moved from support versus surgery into metastatic euthanasia counseling|0|The veterinarian initially laid out supportive care and surgery as the real choices, but chest imaging immediately changed the path.|The discussion moved from stabilizing vomiting and reviewing options to chest x-rays showing spread and a decision for euthanasia.|options,staged,risk,rep
258156|Mack|Dog|Blood-from-penis case worked up stepwise and narrowed to a bladder infection|1|The veterinarian started broad enough to catch the real cause and then narrowed the case to a treatable urinary source.|The discussion covered urine sampling, checking the penis and prostate, finding an inflamed bladder with bacteria, and starting antibiotics with a recheck sample planned.|options,staged,risk,rep
258200|Leeloo|Dog|Recurrent eyelid mass handled with ointment now and surgery only if it worsens|1|The veterinarian stayed conservative because the lesion was not actively inflamed and paired that with joint-support advice for aging hips.|The discussion covered repeat removal versus watchful management, antibiotic eye ointment, Costco-friendly joint supplements, and continuing the owner's bath routine for itch control.|options,staged,min
258203|Kiwi|Cat|Rubber-band ingestion managed with emesis first and scope or surgery held in reserve|1|The veterinarian used the least invasive time-sensitive option first and was explicit about what escalation would look like.|The discussion compared inducing vomiting against feeding through it, scoping the stomach, or surgery, and noted that successful emesis saves time and money.|options,money,staged,risk,rep
258212|Leo|Cat|Urinary-diet maintenance visit with vaccine updates and backup-food guidance|1|This was mainly routine maintenance rather than a real options conversation.|The discussion stayed on rabies and distemper updates, a urinary-diet prescription refill, and reassurance that a backup urinary formula was acceptable if the main food was out.|nooption
258219|Luna|Dog|Wellness visit with a small preventive-medication price discussion|1|This was largely preventive care with only a small affordability aside around parasite prevention.|The discussion covered routine vaccines and bloodwork for Luna plus one-dose versus six-pack Simparica pricing for the household dog.|money,pay,nooption
258234|Buster|Cat|Urinary flare treated before obstruction developed|1|The veterinarian treated the crystals-and-bacteria picture aggressively enough to prevent a male-cat emergency.|The discussion covered crystals, bacteria, an antibiotic injection, gabapentin, supportive supplementation, and stress-cystitis counseling.|options,staged,risk,rep
258237|Violet|Dog|Eye discharge sorted with stain-first logic and the simpler medication path|1|The veterinarian used the exam to justify the lower-intensity eye plan instead of over-treating the case.|The discussion showed no corneal ulcer, then moved to ointment and allergy-aware monitoring.|options,staged,min
258241|Sir Wellington|Cat|Torn nail and soft-tissue pain handled conservatively|1|The veterinarian kept the case on simple pain control and home restriction rather than widening the workup.|The discussion covered liquid pain medication, rest, and managing stairs and dog interaction during recovery.|staged,min,nooption
258246|Diesel|Dog|Minor lip wound treated as a simple outpatient oral injury|1|The veterinarian kept the plan minimal because the wound did not justify closure or a broader workup.|The discussion focused on antibiotics, softer food, and monitoring rather than stitches.|staged,nooption
258323|Elliot|Cat|Mild vaccine-reaction vomiting managed symptomatically|1|The veterinarian treated this as a straightforward short-term reaction rather than a broader GI mystery.|The discussion covered fluids, anti-nausea support, and monitoring appetite over the next one to three days.|staged,risk,nooption
258333|Socks|Cat|Forelimb limp sorted with x-rays before conservative care|1|The veterinarian used imaging to rule out the dangerous version of the problem and then kept care simple.|The discussion covered x-rays, pain medication, and a likely soft-tissue or ligament injury once fracture was excluded.|options,staged,risk,rep
258344|Millie|Dog|Foreign-body surgery was recommended early enough to avoid a worse bowel disaster|1|The veterinarian was direct that this had likely crossed beyond outpatient GI management and into surgery.|The discussion covered suspicious x-rays, the chance to milk the object through without cutting, the higher-risk bowel scenarios, overnight care, and a roughly 4,000-dollar estimate.|options,money,staged,risk,rep
258362|Millie|Dog|Exploratory-surgery dictation rather than an owner-facing care conversation|1|This is a procedural narrative, not a usable exam-room options transcript.|The file reads like operative documentation around intestinal surgery rather than a live owner decision sequence.|nooption
277374|Reni|Dog|Mild recurrent eye discharge treated like an allergy flare|1|The veterinarian matched the treatment intensity to a mild recurrent problem rather than widening the workup.|The discussion covered ointment as needed, Zyrtec, and watching a benign scab.|options,staged,min
277504|Ranger|Dog|Puppy yeast-ear case handled with direct topical treatment|1|The veterinarian treated the obvious ear problem without turning it into a larger workup.|The discussion focused on ear cleaning and a once-daily foam medication course.|options,staged
277601|Charlie|Dog|Third-eyelid issue managed palliatively because dental anesthesia is high risk|1|The veterinarian was honest that the likely root cause was dental but still built a safer day-to-day management path.|The discussion compared ointment with drops, named antibiotics as a backup, and explained why definitive dental care carried real heart-related risk.|options,staged,risk,rep
277862|Gemma|Dog|Wellness visit with home dental care and grain-free counseling|1|This was mostly preventive care with only light branching around what home care made sense.|The discussion covered brushing and dental chews, delaying a dental cleaning for now, grain-free diet risk, and a declined flu vaccine because exposure was low.|options,staged,nooption
278241|Pixie|Dog|End-stage diabetic decline managed with a time-buying comfort-care attempt|1|The veterinarian respected that the owners were not ready for goodbye and offered a limited comfort-care bridge.|The discussion covered fluids, anti-diarrheal support, and returning for euthanasia if the dog did not rebound.|options,staged,risk,rep
278860|Copper|Dog|Eye-discharge case handled with ointment first and bigger moves only later|1|The veterinarian kept the plan stepwise and reserved broader allergy or behavior medication for later if needed.|The discussion covered starting eye ointment, keeping Zyrtec as a backup, and preferring training or pack walks before anxiety medication.|options,staged,barrier
278997|Chloe|Dog|Allergy flare treated with local therapy and candid cost talk about Apoquel|1|The veterinarian built a workable allergy plan and was direct about the cost profile of the systemic option.|The discussion covered topical ear therapy, Apoquel as effective but expensive, and broader allergy and diet counseling.|options,money,staged,risk,rep
279618|Charlie|Dog|New kidney-disease diagnosis framed around long-term home management|1|The veterinarian moved the owners toward a chronic-management mindset instead of pretending this was reversible.|The discussion covered kidney diet, possible home fluids, and a realistic but variable long-term prognosis.|options,staged,risk,rep
279628|Lucy|Dog|Routine wellness visit with watchful dental guidance and vaccine maintenance|1|This was preventive care with only a small future dental branch rather than a live treatment-spectrum case.|The discussion stayed on routine vaccines, declining Bordetella based on lifestyle, monitoring one tooth, and using trazodone only for storms or fireworks.|options,nooption
279709|Roscoe|Dog|Wellness visit with bilious-vomiting counseling and routine vaccine care|1|The veterinarian kept the mild stomach issue conservative and folded it into an otherwise routine visit.|The discussion covered bedtime snacks for morning bile vomiting, routine vaccines, and general wellness reassurance.|staged,min,nooption
279728|Norman|Dog|Recurrent yeast-ear flare managed with foam and maintenance cleaner|1|The veterinarian used a practical recurrent-care plan rather than widening the case unnecessarily.|The discussion covered EZODIC foam, antifungal cleaner, and early intervention when flares start.|options,staged
279756|Mayo|Dog|Routine vaccine and prevention refill visit without a real care fork|1|This was straightforward preventive maintenance.|The discussion stayed on vaccines, Trio refill, and boarding paperwork.|nooption
279768|Willow|Dog|Eyelid-stye case nudged toward ointment because of where the irritation sat|1|The veterinarian used the anatomy of the problem to justify the simpler eye-medication route.|The discussion covered switching from drops to ointment and watching for thickening or progression.|options,staged,min
279823|George|Dog|Tail cyst treated medically before any amputation conversation became real|1|The veterinarian tried the lower-intensity path first while being honest that surgery could still be needed.|The discussion covered antibiotics, stronger anti-inflammatory medication, cone options, and the possibility that shrinking the cyst could avoid tail amputation.|options,staged,risk,rep
279859|Wrigley|Dog|Mild skin flare and soft stool handled with topical care and probiotics|1|The veterinarian kept the case low intensity and practical, even down to where to source medication.|The discussion covered ointment, Fortiflora, and an online-pharmacy price-match option.|options,pay,staged,min
280079|Michael|Cat|Male-cat urinary flare treated before it became an obstruction crisis|1|The veterinarian prioritized the urinary problem and deferred routine care instead of trying to do everything at once.|The discussion covered antibiotic injection, pain medication, fluids, urine recheck, and delaying rabies until stable.|options,staged,risk,rep
280113|Harley|Dog|Diabetic medical-boarding and monitoring used as the practical management plan|1|The veterinarian used boarding logistics and glucose monitoring to solve the real-world problem rather than change treatment blindly.|The discussion centered on boarding, a glucose curve, and keeping the insulin schedule stable during owner travel.|options,staged,barrier
280145|Ghost|Cat|Chronic sneezing after FIP kept on supportive long-term management|1|The veterinarian stayed conservative and focused on livable chronic management rather than aggressive escalation.|The discussion covered lysine, supportive supplements, and minimizing unnecessary vaccines in a medically fragile cat.|options,staged,risk,rep
280187|Missy|Dog|Hematuria case sorted stepwise before committing to diet or infection treatment|1|The veterinarian used testing to decide which branch of urinary disease this actually was.|The discussion compared treating infection against switching to a dissolution diet if crystals were the real driver.|options,staged,risk
280538|Layla|Dog|Front-limb limp tied to irritated nail-bed tissue and possible elbow arthritis|1|The veterinarian combined a simple skin fix with existing anti-inflammatory support instead of widening the case immediately.|The discussion covered shaving and treating the irritated digit, continuing the anti-inflammatory, and recognizing mild elbow crepitus as a likely contributor.|staged,risk,nooption
280690|Charlie|Dog|Hospital kidney-update call kept the dog inpatient until values plateaued|1|This was a hospitalization update rather than a live options conversation, but it still showed staged monitoring logic.|The discussion covered kidney values trending down, the expected plateau point, and keeping the dog one more day before discharge decisions.|staged,risk,nooption
280816|Cohen|Dog|Dental-day consult reframed gassiness, itchiness, eyes, and prevention into a practical home plan|1|The veterinarian stayed stepwise across multiple chronic issues instead of chasing every concern at once.|The discussion covered stopping treats before changing food, Cytopoint versus pills, eye-drop support, cheaper online pharmacy sourcing for prevention, and trimming nails instead of forcing a dental add-on.|options,money,pay,staged,risk,rep
281077|Cohen|Dog|Dental and GI consult balanced watchful waiting against using scheduled anesthesia efficiently|1|The veterinarian used the already-planned procedure as the decision point instead of inventing a separate workup now.|The discussion covered whether to ignore a suspicious incisor or x-ray it during the dental, plus psyllium and diet guidance for gas and loose stool.|options,staged,risk,rep
281301|Huey|Dog|Routine wellness visit with watchful monitoring of tiny masses|1|This was preventive maintenance rather than a real alternatives conversation.|The discussion stayed on vaccines and watching stable small lumps.|nooption
281778|Rocket|Dog|Cystotomy operative note rather than an owner-facing transcript|1|This file is a surgery dictation, not a usable exam-room conversation.|The visible content reads as procedural documentation rather than a live discussion of options.|nooption
281961|Castiel|Dog|Large-breed puppy wellness visit with delayed-neuter recommendation|1|The veterinarian used a long-horizon orthopedic framing rather than treating neuter timing like a trivial default.|The discussion covered waiting about a year for neuter, plus ordinary food, training, and socialization advice.|options,staged,nooption
282292|Houdini|Cat|Hyperthyroid-cat recheck stayed on medical adjustment before anything bigger|1|The veterinarian kept the case on medication refinement and only let cost enter around logistics.|The discussion covered continuing the current medicine a little longer, rechecking thyroid values, and a rough daily boarding cost.|options,money,staged,risk
282380|Archie|Cat|Semi-feral cat's neuter framed as a practical management step|1|This was mainly scheduling and handling planning rather than a deeper treatment-spectrum case.|The discussion centered on neuter timing, gabapentin, and settling the cat into indoor life.|staged,nooption
282515|Riley|Dog|Anxious young dog handled with training-first logic and previsit-medication backup|1|The veterinarian tailored the visit to the dog's handling limits instead of forcing every procedure today.|The discussion covered less-is-more restraint, food-based handling, calorie guidance, training, and using gabapentin plus trazodone if vaccines or nails proved too stressful.|options,staged,barrier,rep
282532|Cisco|Dog|Acute painful limp kept in the gray zone between x-rays and palliative care|0|The veterinarian leaned toward x-rays but openly acknowledged that conservative treatment was also defensible in this case.|The discussion compared radiographs against rest and dog-safe anti-inflammatory medication, then moved to injectable pain control and home meds after the owner chose the palliative route.|options,staged,risk,rep
282611|Winnie|Cat|Chin acne handled with simple topical treatment and bowl hygiene|1|The veterinarian kept the case simple because it did not justify a broader workup.|The discussion focused on Animax and cleaning food and water bowls.|nooption
282654|Scooby|Cat|FIP-like crisis managed with supportive care, estimate talk, and DNR counseling|1|The veterinarian balanced intensive support with realistic prognosis and direct hospitalization logistics.|The discussion covered fluids, anti-nausea support, avoiding abdominal drainage unless breathing worsened, estimate talk, and CPR or DNR decisions.|options,money,staged,risk,rep
287675|Morgan|Dog|Routine vaccine visit with a small chronic-eye aside|1|This was preventive care rather than a real treatment-spectrum conversation.|The discussion stayed on vaccines, a declined heartworm test, and using existing eye drops as needed.|nooption
287797|Sinister|Dog|Odd head and ear episodes treated like ear disease before seizure escalation|1|The veterinarian chose the more common and more manageable explanation first rather than jumping straight to anticonvulsants.|The discussion covered deep ear cleaning, ear medication, oral antibiotics, and rechecking before reframing the episodes as neurologic.|options,staged,risk,rep
288077|Lily|Dog|Senior-dog consult balanced benign lumps and ortho limits with cheaper arthritis meds later|1|The veterinarian named the higher-end orthopedic route but kept the working plan grounded in cheaper long-term management.|The discussion covered benign oral growth, wrist-bump monitoring, specialist arthroscopy only if needed, and switching from Galliprant to cheaper Rimadyl when appropriate.|options,money,staged,risk,rep
288306|Cooper|Dog|Mild ear flare given a real home-maintenance versus new-medication choice|1|The veterinarian offered a genuine two-path plan for a recurrent but not severe ear problem.|The discussion compared daily strong ear solution for two weeks against a newer medication with later recheck.|options,staged
288441|Murphy|Dog|Chronic cough case narrowed to sedated oral exam, referral, or comfort care|1|The veterinarian was direct about the limited next steps and did not pretend there was an easy hidden answer.|The discussion compared a sedated oral exam against internal-medicine referral and named owner finances openly while allowing symptomatic care if that was the limit.|options,money,staged,risk,rep
288730|Bentley|Dog|Senior weakness managed conservatively with cheaper pharmacy sourcing|1|The veterinarian kept the arthritis plan simple and made the medication-sourcing advice practical.|The discussion covered bloodwork for carprofen safety, routine rabies, and filling the medication through a cheaper pharmacy.|options,pay,staged,risk
289056|Delilah|Dog|Bleeding skin abscess treated medically, with seizure-med simplification through outside pharmacy|1|The veterinarian kept the skin problem on a straightforward antibiotic path while also solving a separate medication-burden issue.|The discussion covered leaving the abscess open to drain, oral antibiotics, extended-release Keppra, and using an outside pharmacy because it is cheaper than in-house.|options,money,pay,pharmacy,staged
289194|Bonnie|Dog|PU or PD workup started with urine and skin care before chasing Cushing's|1|The veterinarian kept the case stepwise and refused to jump straight into an endocrine rabbit hole.|The discussion covered urine testing first, Apoquel for lip-fold irritation, and broader Cushing's testing only if the simpler explanations fell away.|options,staged,risk
289550|Braxton|Dog|Mild ear case and refill logistics handled with low-intensity care|1|The veterinarian kept the management light and made medication sourcing more affordable.|The discussion covered weekly ear cleaner, keeping ears dry, and using GoodRx or outside pharmacy pricing for prednisone.|options,pay,staged
289586|Max|Dog|Wellness visit focused on obesity counseling and prevention refills|1|This was preventive care rather than a meaningful care-spectrum conversation.|The discussion stayed on food security, treat control, and Trio refills.|nooption
289919|Charlie|Dog|Bloody-nose case contrasted gold-standard referral against watchful palliative management|0|The veterinarian named the real gold-standard workup but did not pretend it was the only path the owner could take.|The discussion covered CT and rhinoscopy referral, the likely cost and yield, and a monitoring or symptomatic path when the owner declined escalation.|options,staged,risk,rep
290218|Dakota|Dog|Painful diarrhea case kept outpatient with targeted tests and direct medication-cost framing|1|The veterinarian used the one test that mattered to avoid unnecessary hospitalization and then built an aggressive home plan.|The discussion covered normal pancreatitis testing, fluids, multiple GI medications, GI Biome, and an explicit breakdown of medication cost.|options,money,staged,risk,rep
290256|Oliver|Dog|Perianal irritation handled topically before any expensive itch medication|1|The veterinarian started with the local low-intensity fix and kept the pricier systemic option in reserve.|The discussion covered spray, cone use, and Apoquel only if the problem persisted.|options,money,staged
290874|Kato|Dog|Minor bite wound treated as a simple outpatient case|1|The veterinarian kept the plan minimal because the injury did not justify a broader wound workup.|The discussion focused on Clavamox and watching for redness or discharge.|options,staged
291009|Chai|Dog|Giardia follow-up stayed on routine treatment and sanitation counseling|1|This was standard parasite management rather than a real options case.|The discussion covered medication, zoonosis risk, and fecal recheck timing.|staged,nooption
291078|Jack|Dog|Kidney-disease callback delayed treatment until urine clarified the picture|1|The veterinarian avoided committing to kidney therapy before the heart-versus-kidney balance was clearer.|The discussion covered getting a first-morning urine sample before acting on the bloodwork.|options,staged,risk
291118|Tilda|Dog|IBD or lymphoma diet callback kept to a probiotic-support add-on|1|This was a narrow phone follow-up rather than a live options conversation.|The discussion focused on trying Fortiflora with the current diet.|staged,nooption
291228|Duncan|Dog|Advanced disc-disease case stayed on maximal supportive care because surgery was no longer realistic|1|The veterinarian used medication layering and expectation-setting rather than promising an unrealistic fix.|The discussion covered amantadine, supplements, ongoing steroid and gabapentin use, and the limited chance of further improvement.|options,staged,risk,rep
291339|Tux|Cat|Out-of-box urination moved through medical rule-out before behavioral medication|1|The veterinarian refused to assume this was purely behavioral and built a sensible backup path.|The discussion covered blood and urine testing, litter-box changes, pheromones, and anti-anxiety medication only if medical causes fell away.|options,staged,barrier,rep
291789|Duke|Cat|Serious breathing and abdominal-fluid case advanced with a fluid tap as the next real answer|1|The veterinarian pushed the one next step that would actually clarify prognosis instead of guessing longer.|The discussion covered abdominal-fluid sampling and direct conversation about the seriousness of the case.|options,staged,risk,rep
291837|Amelia|Dog|Open-pyometra emergency moved directly to surgery with an explicit estimate|1|The veterinarian was direct that this had crossed out of watchful care and into urgent surgery.|The discussion covered bloodwork, likely overnight care, and a roughly five-thousand-to-nine-thousand-dollar cost range.|options,money,staged,risk,rep
291895|Darla|Dog|Wellness visit with preventive-med comparison and wart reassurance|1|This was largely preventive care with a small logistics-and-cost aside around prevention choices.|The discussion covered Trio versus heartworm-only prevention, price similarity, and watchful management of a benign skin lesion.|options,money,pay,nooption
291953|Shela|Dog|Vomiting and eye-discharge case kept stepwise with ultrasound reserved next|1|The veterinarian used bloodwork first and named imaging as the next move only if the first layer failed.|The discussion covered bland food, eye medication, and abdominal ultrasound if the initial testing did not explain the vomiting.|options,staged,risk,rep
291989|Gracie|Dog|Single seizure-like event handled with watchful monitoring|1|The veterinarian did not widen the case because the episode had fully resolved and the recent data were reassuring.|The discussion stayed on monitoring rather than immediate neurologic escalation.|nooption
292010|Adalai|Dog|Irritated eyelid mass cooled down medically before likely removal|1|The veterinarian used a calming step first while being honest that surgery may still be the longer-term fix.|The discussion covered stain testing, steroid-antibiotic ointment if no ulcer was present, and coordinating senior bloodwork with likely anesthesia later.|options,staged,risk
292019|Chula|Dog|Subtle vision-deficit case moved to ophthalmology referral|1|The veterinarian used the asymmetry on basic exam to justify specialty evaluation instead of pretending the room exam was enough.|The discussion covered decreased menace response and referral for a retinal exam.|options,staged,risk
294214|Tuxedo|Cat|Reassuring callback that only needed a repeat urine sample|1|This was a follow-up logistics call rather than a real alternatives conversation.|The discussion focused on normal bloodwork and the need for a urine sample.|nooption
294437|Gracie|Dog|Improved seizure-workup case allowed ultrasound now or recheck later|1|The veterinarian named a fuller next step but made space for a lighter follow-up path because the dog was improving.|The discussion covered abdominal ultrasound versus waiting for later bloodwork recheck after ALT elevation and mild anemia.|options,staged,risk
294463|Darla|Dog|High-ALP callback started with the simpler Cushing's test before ultrasound|1|The veterinarian kept the endocrine workup stepwise rather than jumping to imaging first.|The discussion covered confirmatory testing first, then abdominal ultrasound only if needed.|options,staged,risk
294543|Bonnie|Dog|PU or PD callback kept Cushing's workup stepwise and conservative|1|The veterinarian used urine-based screening before committing to a broader endocrine workup.|The discussion covered simple screening, hydration support, and deferring the bigger Cushing's path until the first layer came back.|options,staged,risk
302474|Archie|Cat|Urinary-obstruction emergency framed with estimate and future PU surgery logic|1|The veterinarian was direct about the immediate emergency path and the more definitive surgery that might follow later.|The discussion covered catheterization, bloodwork, hospitalization, a fifteen-hundred-to-four-thousand-dollar range, and additional PU cost if needed.|options,money,staged,risk,rep
302488|Dakota|Dog|GI Biome follow-up emphasized safe long-term use and practical sourcing|1|The veterinarian kept the ongoing GI plan practical and low drama.|The discussion covered using GI Biome long term, conservative Trio dosing, and getting the medication through a script or online pharmacy.|options,pay,staged
302521|Ellie|Cat|Vomiting PLE or IBD case ruled out obstruction before intensifying medical care|1|The veterinarian used testing to keep the case medical rather than surgical and then escalated treatment logically.|The discussion covered bloodwork, x-rays, supportive care, prescription diet, steroids, B12, and anti-nausea medication.|options,staged,risk,rep
302522|Ellie|Cat|Parallel capture of the same vomiting PLE or IBD medical-management plan|1|This paired file preserves the same basic medical-optimization path after obstruction was excluded.|The discussion again covered imaging, dropping albumin, diet change, and steroid-based management.|options,staged,risk,rep
302524|Sidney|Dog|Diabetic urgent call avoided panic dosing and waited for the safer morning plan|1|The veterinarian used the glucose number to justify a calmer, lower-risk path overnight.|The discussion covered a sugar around the low 400s, waiting until morning for insulin, and cheap treat ideas for medication delivery.|options,money,staged
305019|Gus|Dog|Senior wellness visit kept early arthritis on supplements and weight loss first|1|The veterinarian started with the lower-intensity changes that could matter before reaching for drugs.|The discussion covered calorie reduction, joint supplements, grain-free caution, and saving anti-inflammatories for later if needed.|options,staged,min
305152|Daisy|Dog|Large-breed spay timing framed around orthopedic risk rather than rescue timing alone|1|The veterinarian pushed back on the easy default and argued for the timing that better fit the dog's long-term health.|The discussion covered waiting until about one year to eighteen months for spay and using microchipping or other logistics if timing changed.|options,staged,risk
305195|Lucy|Cat|Senior-wellness screening declined on cost grounds|1|This was mostly preventive care, but it clearly showed a client choosing against optional screening because of cost.|The discussion covered routine vaccines and declining senior bloodwork because the cat seemed well and the cost did not feel justified.|money,nooption
305224|Yui|Cat|Giardia callback stayed on standard treatment and sanitation advice|1|This was routine parasite follow-up rather than a real alternatives conversation.|The discussion covered two liquid medications, zoonotic caution, and timing for repeat fecal testing.|staged,nooption
305406|Rajee|Dog|Wellness visit with stable lipoma monitoring|1|This was preventive maintenance rather than a meaningful care-spectrum case.|The discussion stayed on routine vaccines, heartworm and fecal screening, and monitoring an unchanged fatty mass.|nooption
305446|Callie|Dog|Chewed paw lesion treated topically with surgery held in reserve|1|The veterinarian kept the first step local and low intensity rather than rushing toward removal.|The discussion covered steroid-antibiotic cream, cone use, and removal only if the lesion kept reopening.|options,staged,min
305525|Lucy and Buddy|Dog|Two-dog wellness visit with only light senior-screening and weight-management planning|1|This stayed in preventive maintenance territory rather than becoming a real affordability or care-spectrum discussion.|The discussion covered vaccine records, a possible senior panel, weight-loss diet interest, and routine wellness follow-up.|nooption
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected',
    alternativeOnDecline: 'alternativeOnDecline'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 18',
      date: '2026-03-19',
      selectionSeed: '20260319-wave18',
      selectionMethod: 'Eighteenth non-overlapping 100-transcript backlog batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1700_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
