window.ANDY_ANALYSIS_BATCH12 = (() => {
  const rows = `
68162|Cleo|Dog|Tapeworm concern with deworming and prevention restart|1|This was a direct parasite-management visit rather than a broader options discussion.|The veterinarian focused on treating visible tapeworm segments, restarting prevention, and setting expectations about how the cycle happens when monthly prevention lapses.|min,nooption
68163|Cleo|Dog|Duplicate-like tapeworm visit with the same prevention-restart plan|1|This duplicate-like capture preserves the same straightforward parasite-management approach.|The discussion again centered on deworming, restarting prevention, and explaining why tapeworm segments show up after flea exposure and prevention gaps.|min,nooption
68208|Navin|Cat|Urinary-stone management with dissolution-first plan and ear-yeast treatment|1|The veterinarian used the lower-invasiveness urinary plan first while explaining when surgery would become necessary.|The discussion paired ear treatment with a bladder-stone workup and favored a prescription dissolution diet before moving to surgery unless the cat blocked or failed the diet.|options,staged,risk,rep
68209|Navin|Cat|Duplicate-like urinary-stone visit with the same dissolution-first reasoning|1|This duplicate-like capture reinforces the same urinary approach without materially changing the coding read.|The discussion again paired ear treatment with a bladder-stone workup and kept diet dissolution ahead of surgery unless the cat worsened or failed to improve.|options,staged,risk,rep
68318|Sweetie|Cat|First-seizure workup with send-out bloodwork and no seizure drugs yet|1|The veterinarian matched the plan to a first seizure by keeping the workup practical and delaying chronic medication.|The discussion used cheaper send-out bloodwork, addressed flea treatment, and explained that seizure medication usually waits unless events recur or cluster.|options,money,pay,staged,risk,min,rep
68361|Callie|Dog|Dark-stool and Rimadyl callback with urine check before restarting NSAIDs|1|The veterinarian kept the next step narrow around whether the current signs made anti-inflammatory use unsafe.|The discussion weighed restarting pain medication against getting a urine sample first and explained why melena-like stool changed the safety equation.|options,staged,risk,min
72414|Lucy|Dog|Vomiting-and-diarrhea visit with conservative care before x-rays|1|The veterinarian made imaging available but started with the smaller supportive plan because the exam still supported it.|The discussion used fluids, anti-nausea care, probiotic-fiber support, and fecal testing while holding x-rays in reserve unless recovery stalled.|options,staged,risk,min,rep
72417|Lucy|Dog|Duplicate-like GI visit with the same supportive-care-first plan|1|This duplicate-like capture preserves the same staged GI reasoning.|The discussion again favored fluids, anti-nausea care, and fecal testing first, with imaging left available if recovery stopped moving in the right direction.|options,staged,risk,min,rep
72484|Jasper|Dog|Painful eye visit with stain-first branching before medication choice|1|The veterinarian used the corneal stain result to decide how aggressive the eye treatment needed to be.|The discussion separated ulcer management from simple irritation and explained why the medication plan depended on whether the cornea was actually damaged.|options,staged,risk,min
72539|Chino|Dog|Hematuria visit with UTI treatment and allergy-medication branching|1|The veterinarian treated the likely urinary infection while still giving a practical itch-management alternative.|The discussion paired antibiotics and recheck plans for hematuria with the option of increasing Apoquel temporarily instead of jumping straight to a Cytopoint injection.|options,staged,risk
72549|Om|Dog|Ear-and-allergy follow-up with injection-versus-pill itch control|1|The veterinarian matched the allergy plan to what the owner could realistically maintain at home.|The discussion compared another injection against increasing Apoquel dosing while treating the ear infection and recognizing that repeated home handling was part of the challenge.|options,staged,barrier
72567|Wrigley|Dog|Lick-granuloma recheck with home management versus more intensive boarding support|1|The veterinarian kept the dog on the smaller plan because the lesion was already improving.|The discussion continued antibiotics and topical care, allowed regular boarding with monitoring, and reserved more medicalized boarding only if the area worsened.|options,staged,min
72601|Remington|Dog|New-dog check with hip-lump reassurance and breeder-counseling discussion|1|This visit was mostly education and reassurance rather than a true care-options encounter.|The conversation centered on a stable hip lump and on why backing out of a Doberman purchase with clear knuckling concerns was the responsible choice.|nooption
72606|Simba|Dog|Bite-wound treatment with rabies-quarantine logistics and direct wound care|1|This was an acute safety case where the core treatment path was fairly fixed.|The discussion focused on cleaning the wounds, pain control, antibiotics, and the legal and practical implications of bite-wound management and quarantine.|money,risk,nooption
72631|Stewie|Dog|Bite-wound case with sedated full cleanup versus cheaper limited care|0|This was a clear decline-triggered spectrum-of-care conversation under financial pressure.|The veterinarian explained why sedated clipping and cleaning was safer, then allowed antibiotics and pain control alone with weekly payment planning when the full option was too expensive.|options,money,pay,alt,staged,risk,rep
72653|Rocket|Dog|Abdominal-pain visit with x-ray-first reasoning and safer pain-med selection|1|The veterinarian narrowed the first step around whether this was GI pain or musculoskeletal pain.|The discussion favored imaging and a stomach-safer pain approach before deciding whether the problem was abdominal disease or back pain.|options,staged,risk,min
72666|Jasmine|Dog|Chronic regurgitation flare with elevated-feeding and megaesophagus guidance|1|The veterinarian separated regurgitation from vomiting and changed the plan accordingly.|The discussion reframed the episode around esophageal disease, recommended supportive care with smaller elevated meals, and suggested later workup for megaesophagus or myasthenia rather than treating it like simple vomiting.|options,staged,risk,rep
72667|Bailey|Dog|Localized skin-cyst visit with simple care and later-removal option|1|The veterinarian kept the plan small because the lesion still looked manageable locally.|The discussion focused on local treatment and monitoring, with formal removal left as a later step if the cyst stopped settling or became more bothersome.|min,nooption
72670|Bentley|Dog|Neck-pain visit with conservative treatment and incidental murmur staging|1|The veterinarian treated the painful neck strain first while flagging the heart murmur as a separate future decision.|The discussion used anti-inflammatories and gabapentin for likely cervical pain, then explained echocardiogram staging before any long-term heart medication would make sense.|options,staged,risk,min,rep
72679|Waffles|Dog|Vomiting case with blockage concern framed through staged escalation|1|The veterinarian organized the visit around how quickly the dog needed to move from home care to fuller obstruction workup.|The discussion balanced monitoring and supportive treatment against the risk of a foreign body, with clear red flags for when the plan had to escalate.|options,staged,risk,rep
73848|Dexter|Dog|Seizure-medication follow-up with murmur-monitoring discussion|1|The veterinarian kept the current neurologic plan steady while staging the heart follow-up separately.|The discussion focused on medication monitoring, explained when the murmur would warrant further cardiac imaging, and avoided jumping to more care than the dog needed that day.|options,staged,risk
73967|Campbell|Dog|Toe-mass and skin-itch visit with aspirate-first reasoning|1|The veterinarian used a stepwise lesion workup instead of jumping straight to removal.|The discussion framed fine-needle aspirate as the next move for the toe mass, addressed concurrent skin irritation, and reserved surgery for lesions that proved more concerning or kept growing.|options,staged,risk,min
73968|Campbell|Dog|Duplicate-like toe-mass visit with aspirate-first and monitor-versus-remove logic|1|This duplicate-like capture reinforces the same mass-workup approach without materially changing the coding read.|The discussion again used aspirate-first reasoning for the toe lesion while handling the accompanying rash and licking with smaller first-step care.|options,staged,risk,min
74037|Charlie|Dog|Luxating-patella consult with pain-first care and surgery only if needed|1|The veterinarian explained the orthopedic problem without overselling immediate surgery.|The discussion used a short anti-inflammatory course, set expectations for intermittent limping, and kept surgery as the threshold decision for dogs that worsen or stop bouncing back.|options,staged,risk,min
74063|Ivy|Dog|UTI follow-up with monitoring plan for residual stretching and hiccup-like behavior|1|The veterinarian stayed on the smallest plan that still made clinical sense.|The discussion used urine recheck and watchful monitoring, with extra medication only if the GI-like signs became more persistent or clearly uncomfortable.|options,staged,min
74114|Sam|Dog|Chronic allergy and ear visit with diet trial before long-term Apoquel cost|1|This was a strong example of cost-aware staged allergy care.|The discussion compared an expensive long-term Apoquel path against a hydrolyzed Ultamino diet trial, used leave-in ear medication to reduce home handling, and even discussed grinder-based nail care to work around fear reactions.|options,money,pay,staged,risk,barrier,rep
74173|Minnow|Cat|Dual-cat wellness visit with early dental-cleaning guidance|1|This was a routine wellness visit where alternatives were not really the issue.|The conversation centered on normal exams, weight checks, and early gingivitis that justified planning dental cleaning rather than on a broader spectrum-of-care decision.|nooption
74203|Mablr|Dog|Hematuria visit with ultrasound-guided urine attempt and empiric antibiotics|1|The plan stayed narrow around confirming the bladder source and treating the likely infection.|The discussion used ultrasound when a clean urine sample was hard to obtain, found crystalline debris, and moved ahead with antibiotics plus recheck instead of a larger same-day workup.|staged,risk,nooption
74204|Mablr|Dog|Duplicate-like hematuria visit with the same bladder-debris and recheck plan|1|This duplicate-like capture preserves the same narrow urinary-treatment logic.|The discussion again attempted urine collection, used ultrasound findings, and chose empiric antibiotics with a follow-up plan instead of expanding the workup immediately.|staged,risk,nooption
74258|Snowall|Dog|Drug-reaction skin flare with topical-first rescue plan|1|The veterinarian pivoted away from the offending medication and built a safer symptom-control plan.|The discussion stopped the suspected antibiotic trigger, used topical mousse and antihistamine support, and kept steroid and Cytopoint therapy in place with close short-term reassessment.|options,staged,risk,rep
74276|Vouri|Dog|Vomiting-after-deer-meat visit with surgery, scope, CPL, and emesis options|0|This was a strong cost-constrained foreign-body conversation with multiple real branches.|The discussion weighed supportive care, pancreatitis testing, scope or surgery, and even a low-cost attempt to induce vomiting while the owner worked through CareCredit limits.|options,money,pay,alt,staged,risk,rep
74285|Cosa|Dog|Perianal-mass visit with aspirate, antibiotics, and surgery held in reserve|1|The veterinarian used the smaller diagnostic and treatment step first.|The discussion paired a needle sample with antibiotics and monitoring, while explaining that persistent or suspicious change would move the case toward surgical removal.|options,staged,risk,min
74295|Mona|Dog|Bloody-diarrhea visit with direct GI support and safety-netting|1|This was mostly a straightforward acute-GI visit rather than a broad options discussion.|The plan centered on anti-nausea care, metronidazole, probiotic support, and instructions for when worsening signs would justify more workup.|risk,min,nooption
74297|Sophie|Dog|Potential foreign-body case with direct risk framing despite cost anxiety|1|The veterinarian treated this as a high-risk problem where cheaper choices had real downside.|The discussion focused on string-foreign-body concern, the limits of sedation and extraction, and why cost worry could not remove the need to protect the dog from a dangerous obstruction.|money,risk,nooption
74372|Koga|Cat|Chronic sneezing and dental disease visit with earlier-procedure recommendation|1|The veterinarian connected the respiratory signs and oral disease without pretending it could wait forever.|The discussion framed dental treatment and likely extraction as the meaningful next step while still acknowledging herpes or sinus inflammation as part of the background picture.|options,staged,risk,min
74450|Copper|Dog|Fearful-young-dog behavior visit with positive-reinforcement first steps|1|The veterinarian handled this as a confidence-building problem, not a punishment problem.|The discussion emphasized time, structured positive reinforcement, and realistic expectations for a fearful dog whose barking and handling problems were rooted in insecurity.|options,staged,barrier,rep
74451|Copper|Dog|Behavior follow-up focused on fear barking and neighbor-management pressure|1|This was another strong example of behavior advice being shaped around owner bandwidth and the dog's anxiety profile.|The discussion stayed on positive reinforcement, trigger management, and patient repetition because the dog's condo barking and fearfulness would worsen under harsh correction.|options,staged,barrier,rep
74481|Candy|Dog|Senior wellness visit with worsening murmur and echo-before-medication guidance|1|The veterinarian used the louder murmur to justify staging rather than starting expensive heart drugs blindly.|The discussion explained heart-disease stages, the role of echocardiography, and why pimobendan should wait until structural change was confirmed.|options,money,staged,risk,rep
74630|Selene and Michael|Dog|Paired puppy wellness visit with stool follow-up and routine guidance|1|This was mainly a preventive puppy visit rather than an options-heavy encounter.|The conversation focused on weights, treats, fecal follow-up, and routine puppy support rather than on a meaningful treatment fork.|nooption
74677|Isis|Cat|Blood-pressure recheck with stable-dose continuation and dental scheduling|1|This was a straightforward monitoring visit where the current plan was working.|The discussion confirmed improved blood pressure on the current dose and coordinated upcoming dental logistics without opening a new care branch.|min,nooption
74818|Bowie|Dog|Bite-wound visit with direct flush-and-medicate care|1|This was an acute wound-management case with a fairly fixed plan.|The discussion centered on cleaning the punctures, using pain control and antibiotics, and watching for pocketing or drainage that would change the aftercare.|risk,nooption
74821|Sadie|Cat|Dental recheck with simple diet adjustment and no larger intervention|1|This was a narrow post-procedure follow-up rather than a new options conversation.|The veterinarian confirmed healing, allowed return to crunchier food, and did not need to widen the plan beyond routine recovery guidance.|min,nooption
74855|Chocolate|Cat|Upper-respiratory case with x-ray-first rule-out before antibiotics|1|The veterinarian used imaging to distinguish a simple URI from deeper chest disease.|The discussion explained why chest radiographs mattered before labeling the whole problem herpes or upper-airway only, then kept the next step smaller if the lungs stayed clear.|options,staged,risk,min
74856|Chocolate|Cat|Duplicate-like upper-respiratory workup with the same x-ray-first logic|1|This duplicate-like capture preserves the same chest-rule-out reasoning.|The discussion again used x-rays to separate lower-airway concern from a simpler URI picture before choosing the least necessary treatment.|options,staged,risk,min
75052|Cacho|Dog|Ear recheck with maintenance cleaner and routine vaccine timing|1|This was mostly a simple maintenance follow-up.|The discussion moved the dog to weekly cleaner use and handled the rest as routine prevention planning rather than a broader treatment decision.|min,nooption
75118|Harley|Dog|Intermittent twitching concern with watch-and-record guidance only|1|The veterinarian avoided overreacting to a transient episode that had already settled.|The plan was simple monitoring, video capture if it recurred, and no bigger workup unless the pattern changed.|min,nooption
75157|Meatball|Dog|Wellness visit with flank-alopecia support and cheaper melatonin sourcing|1|This was mostly routine care, but the veterinarian still gave a practical low-cost supportive move.|The discussion treated the seasonal hair-loss pattern conservatively and noted that melatonin could be sourced more cheaply through regular retail pharmacy channels.|money,pay,pharmacy,min,nooption
75385|Meredith|Dog|ADR workup with send-out versus in-house labs and ultrasound check|1|This was a strong example of cost-aware stepwise workup in an older dog.|The discussion framed diabetes, kidney disease, anemia, and abdominal tumor as the major differentials, then let the owner choose cheaper send-out bloodwork while still checking the bladder and abdomen with ultrasound during urine collection.|options,money,pay,staged,risk,rep
75746|Charlie|Dog|Eye-ulcer recheck showing healing and short medication taper|1|This was a healing recheck with no need to widen care.|The veterinarian confirmed the ulcer was essentially resolved and only adjusted the medication timeline rather than adding new intervention.|min,nooption
75840|Lux|Dog|Incontinence management with medication-switch plan and cheaper send-out monitoring|1|The veterinarian handled the chronic issue by changing the formulation before escalating the whole workup.|The discussion switched from extended-release to immediate-release dosing, paired it with urine and wellness monitoring, and used send-out testing to keep the follow-up cheaper.|options,pay,staged,risk
75841|Lux|Dog|Duplicate-like incontinence follow-up with the same Proin-switch reasoning|1|This duplicate-like capture preserves the same medication-management logic.|The discussion again moved toward immediate-release dosing and send-out follow-up rather than building a larger same-day workup.|options,pay,staged,risk
75881|Teddy|Dog|Puppy visit with motion-sickness plan and cryptorchid follow-up logic|1|The veterinarian kept both issues on the least invasive track that still made sense.|The discussion compared travel-medication options, explained retained-testicle follow-up, and kept surgery contingent on whether the second testicle stayed absent.|options,staged,risk,min
75925|Jinx|Cat|Rabies-observation intake after a bite incident|1|This was a legal-hold case with a fixed protocol rather than a treatment-options conversation.|The discussion focused on the 10-day observation process, no-contact rules, and the final release exam and vaccine timing.|nooption
75932|Ellee|Dog|Recurrent UTI with dissolution diet now and surgery only if recurrence persists|1|This was a strong example of staged urinary care that acknowledged both weight and anatomy.|The discussion treated the active UTI, used a temporary urine-dissolving diet for crystals, planned later weight-loss food, and kept hooded-vulva surgery as an option if repeated infections continued.|options,money,pay,staged,risk,min,rep
75960|Jake|Dog|Tiny back-bump check with simple monitoring only|1|The veterinarian kept the plan minimal because the lesion was already shrinking.|The discussion treated the bump as a monitor-only issue with no sign that a larger workup or procedure was needed that day.|nooption
75961|Jake|Dog|Duplicate-like back-bump recheck with the same monitor-only plan|1|This duplicate-like capture does not materially change the coding read.|The discussion again kept the shrinking lesion on a simple watchful-monitoring path.|nooption
76006|Copper|Dog|Hookworm case with prevention choice based on what also clears parasites|1|The veterinarian used the preventive decision to solve more than one problem at once.|The discussion compared prevention products, noted that Trio would address the hookworm issue too, and paired the plan with repeat fecal timing rather than broader same-day escalation.|options,staged,min,rep
76027|Tucker|Dog|Lameness follow-up with x-ray optional and arthritis-first management|1|The veterinarian treated the improving limp like a chronic orthopedic problem before reaching for more workup.|The discussion kept x-rays optional, used anti-inflammatory management, and framed arthritis or partial ACL disease as the more likely explanation if the pattern persisted.|options,staged,risk,min
76077|Teddy|Dog|Tail-pain visit with fracture rule-out before happy-tail treatment|1|The veterinarian used imaging to make sure the simpler explanation was actually safe to assume.|The discussion compared fracture concern against happy tail, then paired the diagnosis with injection-now and oral-medication-later treatment.|options,staged,risk,min
76282|Snowball|Dog|Severe skin-disease flare with culture-now and biopsy-later escalation|1|The veterinarian built a real ladder of care rather than pretending the current plan had to be final.|The discussion used stronger antibiotics, bathing, and culture first, then kept biopsy as the next step if the skin disease failed to respond.|options,staged,risk,rep
76363|Ernie|Dog|Fearful-handling visit with sedate-now versus premedicate-and-retry plan|1|The veterinarian shaped the visit around what the dog could actually tolerate.|The discussion contrasted immediate sedation with sending home medications for a calmer later retry, making the handling barrier explicit instead of forcing the issue.|options,staged,barrier
76406|Hudson|Dog|Recurrent facial-lesion follow-up with wipe-first care and monitor-only escalation|1|The veterinarian kept the plan conservative because the lesion was minor and familiar.|The discussion used medicated wipes and early ear care, with broader dermatology explanations only if the pattern became more consistent or severe.|options,staged,min
76451|Momo|Dog|Hematuria visit with bladder ultrasound and urine sample before further decisions|1|The veterinarian started with the narrowest useful urinary workup.|The discussion used ultrasound and urine testing to look for bladder infection or other local causes before assuming the bleeding needed a larger immediate intervention.|staged,nooption
78350|Elsa|Dog|Diarrhea follow-up during deworming with direct supportive treatment|1|This was an acute GI case where the treatment path was fairly fixed.|The discussion focused on medication support and hydration rather than a broader spectrum-of-care decision.|risk,nooption
78454|Goldie|Dog|Chronic ear-infection visit with diet-trial branch for food allergy|1|The veterinarian treated the ears directly but still built a longer-term allergy path.|The discussion continued topical therapy and cleaner use while explaining why a hydrolyzed diet trial could answer the recurrent-allergy piece better than guessing.|options,staged,risk
78575|Willow|Cat|Chronic-vomiting workup with limited-funds choice short of full advanced diagnostics|0|This was a strong example of a realistic middle path after cost constrained the ideal workup.|The discussion weighed treatment trial, x-rays, ultrasound, and biopsy for likely IBD, and the owner selected the smaller imaging-plus-medication route because funds were limited.|options,money,alt,staged,risk,rep
78576|Willow|Cat|Duplicate-like chronic-vomiting visit with the same cost-limited middle path|0|This duplicate-like capture preserves the same partial-workup decision under financial constraint.|The discussion again stopped short of the fullest GI workup and used a smaller diagnostic-and-treatment step because the owner could not reasonably do everything at once.|options,money,alt,staged,risk,rep
78692|Wednesday|Dog|New-adoption wellness visit with routine preventive planning|1|This was primarily a standard new-patient wellness encounter.|The conversation centered on vaccines, routine exam findings, and normal puppy guidance rather than a meaningful treatment fork.|nooption
78831|Paris|Dog|Serious liver-disease conversation with hospitalization, medications, and euthanasia on the table|1|This was a high-stakes spectrum-of-care discussion with prognosis made explicit.|The discussion laid out hospitalization versus outpatient liver support and even humane euthanasia as legitimate branches once the liver values and overall condition looked this poor.|options,money,staged,risk,rep
78925|Archie|Cat|Urinary-stone surgery planning with pre-op bloodwork and direct next steps|1|This case had some staging, but the overall path was still fairly fixed.|The discussion centered on confirming bloodwork and organizing surgery and hospitalization rather than offering a wide range of alternative care paths.|staged,risk,nooption
78942|Katie|Dog|Senior wellness recheck with routine thyroid monitoring and refills|1|This was a stable monitoring visit without a fresh options conversation.|The discussion stayed on routine senior follow-up and maintenance rather than opening new branches of care.|nooption
80708|Harley|Dog|Wellness visit with skin-spot monitoring and routine updates|1|This was mostly maintenance care rather than a true spectrum-of-care encounter.|The discussion covered minor lesion monitoring, vaccines, and routine record cleanup without a broader treatment fork.|nooption
80818|Rudy and Tucker|Dog|Paired wellness visit with dental-treat counseling and routine preventive care|1|This was a routine multi-dog visit rather than an options-heavy conversation.|The discussion focused on preventive care and home dental guidance, not on cost or staged medical choices.|nooption
80894|Noodle|Dog|Senior wellness visit with cough check and routine prevention|1|This was mainly a straightforward senior preventive visit.|The discussion covered vaccines, heartworm testing, and a reassuring respiratory exam without a larger treatment branch.|nooption
81019|Jeff|Dog|Acute hind-limb pain visit with conservative knee and back pain management|1|The veterinarian used exam findings to justify a smaller pain-control first step.|The discussion treated the problem like a musculoskeletal pain event and paired anti-inflammatory support with monitoring rather than rushing to a larger same-day workup.|options,staged,risk,min
81047|Bonnie|Dog|Wellness visit with probiotic choice for mild GI upset|1|The veterinarian handled the digestive concern with a small, practical branch inside a routine visit.|The discussion stayed on vaccines and wellness but still compared simple probiotic options for mild stomach upset instead of overcomplicating it.|options,min
81150|Buddy|Dog|Boarding-cough visit with supportive care and delayed x-rays only if persistent|1|The veterinarian separated likely viral kennel cough from the much smaller group that truly needs more workup.|The discussion used cough tablets and supportive care first, with chest x-rays or antibiotics held for dogs that stop improving or develop stronger evidence of bacterial involvement.|options,staged,risk,min
81246|Ivy|Cat|Weakness and wound-history visit with bloodwork first and x-rays later if needed|1|The veterinarian organized the case around the next most informative first step.|The discussion started with bloodwork for weakness and infection concerns, then kept imaging as the later branch if the lab picture or clinical course warranted it.|options,staged,risk,rep
81298|Winston|Cat|Suspected-rubber-band follow-up with x-rays reassuring enough to avoid scope|1|The veterinarian used imaging and clinical context to stop short of unnecessary endoscopy.|The discussion showed a poop-filled colon and empty-looking stomach, then explained that scope was still possible in theory but not justified without symptoms or worse radiographs.|options,staged,risk,min
81382|Lilly|Dog|Perianal-support visit with supplement and cheaper refill-channel planning|1|The veterinarian kept the plan practical and owner-manageable.|The discussion used supportive gland or GI care and pointed the owner toward cheaper ongoing sourcing rather than jumping to a bigger intervention.|options,pay,pharmacy,min
81533|Murphy|Dog|Ear-pinna lump and yeast visit with local management before difficult removal|1|The veterinarian explained why surgical removal was possible but not the first or easiest choice.|The discussion treated the yeast component, sampled the pinna lump, and kept removal as a later step because healing on the ear would be hard and prone to dehiscence.|options,staged,risk,min
81569|Leo|Dog|Kennel-cough visit with supportive-care first and optional allergy injection|1|The veterinarian kept the respiratory plan small while still being explicit about when antibiotics would make sense.|The discussion used cough tablets and steam first, reserved doxycycline for colored discharge or worse progression, and separately priced out a Cytopoint injection for ongoing allergy discomfort.|options,money,pay,staged,risk,rep
81648|Mia|Dog|Laceration repair visit with local-first versus heavier sedation if needed|1|The veterinarian shaped the repair plan around the least intervention that would still safely close the wound.|The discussion compared local handling against more involved restraint or sedation, balancing wound care with how much the dog could tolerate.|options,staged,risk,min
81688|Mira and Magnus|Cat|Weight-loss workup with cheaper send-out thyroid testing and treatment paths|1|This was a clean, cost-aware hyperthyroid screening conversation.|The discussion used cheaper send-out bloodwork for the weight-losing cat, explained oral, ear, and radioactive-iodine options if hyperthyroidism was confirmed, and kept the healthy housemate on routine monitoring only.|options,money,pay,staged,risk,rep
81709|Koda|Dog|Post-op vomiting visit with supportive care and monitoring only|1|The veterinarian kept the plan small because the incision looked good and the main problem was nausea.|The discussion centered on anti-nausea support, fluids, bland diet, and observation rather than on a larger new workup.|min,nooption
81720|Cisco and Smoke|Cat|Paired wellness visit with straightforward calorie-reduction advice|1|This was a routine wellness encounter with practical weight guidance.|The discussion focused on maintenance care and modest calorie reduction for the heavier cat rather than on a broader treatment branch.|min,nooption
82356|Lenny|Dog|Surgery-candidate discussion with cheaper local echo before anesthesia and referral|1|This was a strong example of stepwise pre-surgical risk workup rather than rushing into a major procedure.|The discussion framed echocardiography as the cheaper and smarter first step before anesthesia for the ear mass, with referral and surgery decisions held until the cardiac risk was clearer.|options,money,pay,staged,risk,rep
82411|Ricci|Dog|Wellness visit with routine dental and murmur monitoring guidance|1|This was a stable preventive visit rather than a true options conversation.|The discussion stayed on routine exam findings and watchful monitoring of chronic issues without opening a larger treatment branch.|nooption
82462|Jinx|Dog|Rabies-observation intake after an out-of-home bite incident|1|This was a legal-hold protocol visit with little room for a broader option set.|The discussion focused on the 10-day observation rules, owner-visit limits, and what neurologic changes would matter during the hold.|nooption
82621|Mishio|Dog|Senior-patient PU-PD workup with cheaper send-out panel|1|The veterinarian used the cheaper lab route because the question was broad but not immediately emergent.|The discussion explained kidney disease, diabetes, and urinary infection as the main causes of the increased drinking and noted that sending the panel out would save money before deciding anything further.|money,pay,staged,nooption
82893|Jax|Dog|Arthritis-and-soft-stool visit with dose-splitting and Biome diet trial|1|This was a good example of staged GI and pain management inside one chronic-care visit.|The discussion lowered and split the Rimadyl dosing to protect the stomach, kept the pain relief available, and added a prescription Biome trial rather than pretending one change solved both issues alone.|options,money,staged,risk,rep
85572|Anna|Dog|CKD phone follow-up with kidney-diet brand options and supplement planning|1|The veterinarian treated early kidney disease as a long-term management problem, not an emergency.|The discussion recommended unlimited water, trying several kidney-diet brands in small amounts, and later supportive supplements or fluids only if the lab trend worsened.|options,staged,risk,min
85590|Titan|Dog|Acute back-pain visit with direct pain control and monitoring|1|This was a musculoskeletal pain case where the core first-step plan was fairly fixed.|The discussion focused on exam-based localization, anti-inflammatory plus gabapentin treatment, and what neurologic decline would mean for escalation.|risk,min,nooption
87894|Mia|Cat|Annual visit with one-year rabies choice after prior vaccine reaction|1|The veterinarian used the vaccine history to justify the safer shorter interval.|The discussion centered on routine annual care and why the previous reaction made a one-year rabies plan more sensible than a longer interval vaccine.|risk,nooption
87926|Pepper|Dog|Medical-boarding clearance visit with regimen confirmation and no major branching|1|This was mostly a stability check around an already-complex chronic regimen.|The discussion confirmed that the dog could continue the current plan and did not really open a new options conversation.|nooption
87953|Copper|Dog|Reactivity visit with collar, CBD, and training-path comparisons|1|This was a real behavior spectrum-of-care conversation rather than a single-plan visit.|The discussion compared sound or citronella collars, CBD, bitter apple, and training approaches while keeping the dog's barking and household disruption in the center of the decision.|options,staged,barrier,rep
87988|Rocko Grant|Cat|Thyroid recheck with cheaper send-out lab and murmur-watch logic|1|The veterinarian used the cheaper lab route because the cat was clinically stable enough to wait.|The discussion explained that the low-grade murmur might improve once the thyroid normalized and chose send-out thyroid monitoring instead of more expensive in-house testing.|money,pay,staged,min
88004|Frozen|Dog|Thyroid-maintenance visit with no recheck needed now and pharmacy price shopping|1|This was a strong example of cost navigation inside a stable chronic-care visit.|The discussion confirmed the current thyroid level was adequate, avoided an unnecessary recheck, and compared GoodRx, Chewy, Walmart, and in-clinic dispensing to lower the long-term refill cost.|options,money,pay,pharmacy,staged,min,rep
88061|Nico|Dog|Final puppy-shot visit with Trio-now versus ProHeart-later guidance|1|The veterinarian matched prevention timing to what the puppy could actually receive today.|The discussion used Simparica Trio now, explained why the injectable option had to wait until six months, and kept the tiny umbilical hernia on monitor-until-neuter status.|options,staged,risk,min
88102|Toast|Cat|Wellness visit with nose-crusting support and freeze-dried-raw risk guidance|1|The veterinarian answered the raw-feeding question with a more nuanced risk conversation than a blanket yes or no.|The discussion suggested probiotics and saline for mild chronic crusting, leaned away from chicken or turkey raw because of current bird-flu risk, and said freeze-dried beef was a safer version of the same idea.|options,risk,min
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 12',
      date: '2026-03-18',
      selectionSeed: '20260318-wave12',
      selectionMethod: 'Twelfth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1100_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
