window.ANDY_ANALYSIS_BATCH16 = (() => {
  const rows = `
173125|Layla|Dog|Tick-related pain follow-up kept on a narrow outpatient path|1|The veterinarian treated the flare as a focused medical problem rather than an affordability standoff.|The discussion stayed on likely tick-borne pain, a stepwise test plan, and simple follow-up rather than a broad option menu.|staged,risk,min,nooption
175314|Rigatoni|Unknown|Nonstandard internal-style mouth-injury dictation instead of a clean visit|1|This file does not read like a normal owner-facing cost-of-care conversation.|The capture behaves like a demo or internal treatment recap, so there was no meaningful option-setting sequence to code.|nooption
175316|Rigatoni|Unknown|Second internal-style mouth-injury dictation without a real owner discussion|1|This file likewise does not function like a normal exam-room transcript.|It reads like another nonstandard internal note, not a usable affordability or alternatives conversation.|nooption
186838|Chance|Dog|Routine wellness and vaccine visit without a real care-spectrum fork|1|This was a preventive maintenance encounter rather than an options case.|The conversation stayed on vaccines, bloodwork, and routine wellness tasks with no substantive treatment branch.|nooption
186875|Recon|Dog|Cluster-seizure hospitalization update with medication and itch-control branching|1|The veterinarian built a practical inpatient spectrum instead of pretending there was only one next step.|The discussion moved across phenobarbital threshold changes, safer itch control, and discharge timing while keeping the case medically grounded.|options,staged,risk,rep
187024|Miguel|Dog|Acute head-tilt visit balancing vestibular disease, blood pressure, and bigger neurologic concern|1|The veterinarian used a stepwise outpatient plan while naming the more serious possibilities clearly.|The discussion compared blood pressure, bloodwork timing, and supportive care against the risk of strokes or intracranial disease.|options,staged,risk,rep
187166|Willow|Dog|Routine preventive visit with dental planning deferred to a later step|1|The veterinarian kept the visit in maintenance territory while flagging the next issue honestly.|The conversation stayed on vaccines and routine screening, with future dental work noted rather than expanded into a large decision tree.|staged,nooption
187266|Kirby|Dog|Cancer-dog logistics visit built around transfer requirements and comfort support|1|The veterinarian translated a hard situation into practical next steps instead of offering empty escalation.|The discussion covered rabies requirements for acute care, a possible medical exemption, and anti-inflammatory support for worsening hind-end discomfort.|options,staged,risk,barrier
187336|Kelly|Dog|Forelimb soft-tissue injury visit using rest and pain control before imaging|1|The veterinarian resisted over-testing and kept the first move conservative because the dog was already improving.|The discussion compared x-rays against supportive care, used gabapentin as a calmer add-on, and emphasized rest as the highest-value intervention.|options,staged,risk,min,rep
187470|Mary Jane|Cat|Diabetic ketoacidosis hospitalization with explicit cost and prognosis framing|1|The veterinarian was unusually direct about the financial and medical stakes while still offering a real path forward.|The discussion covered ICU-style care, likely days hospitalized, insulin expectations, and a realistic estimate range for a critically ill cat.|options,money,pay,staged,risk,rep
187527|Layla|Dog|Positive tick-panel callback with active-infection testing and treatment sequencing|1|The veterinarian added the next diagnostic step rather than assuming any positive tick history meant the same thing.|The discussion moved from prior exposure to reflex C6 testing, antibiotics if active infection was confirmed, and prevention follow-through.|options,staged,risk
187919|Simba|Dog|Wellness visit with heartworm-testing and prevention hesitancy addressed in real time|1|The veterinarian did offer a preventive path, but the friction was more about owner skepticism than money.|The conversation stayed on vaccine updates and heartworm prevention while working around a hesitant owner perspective.|options,staged,barrier
188065|Sugar|Dog|Tick-exposure wellness visit with active-infection testing priced transparently|1|The veterinarian used a lower-cost diagnostic pathway instead of defaulting to the most expensive version of the workup.|The discussion compared Lyme testing approaches, explained what a reflex C6 adds, and tied the decision to whether the current exposure looked active.|options,money,pay,staged,risk,rep
188145|Reggie|Dog|Rabies-duration discussion with clear price differences between vaccine options|1|The veterinarian made the cost and duration tradeoff visible rather than hiding it behind routine recommendations.|The discussion compared one-year and three-year rabies coverage, answered effectiveness questions, and let price be part of the decision.|options,money,staged
188207|Pepper|Cat|Dental-pain and arthritis visit using symptom relief before bigger dental work|1|The veterinarian chose a workable bridge plan while still making the likely dental source explicit.|The discussion paired antibiotic support and soft food with later dental care and broader pain-management thinking for an older cat.|options,staged,risk,rep
188246|Lola B|Dog|Painful-mouth visit using interim care while likely extractions were discussed|1|The veterinarian used a realistic bridge rather than pretending the dog needed immediate definitive care that day.|The discussion centered on infected or loose teeth, home-feeding adjustments, and planned dental follow-through.|options,staged,risk,rep
192159|Patrick|Cat|Chronic-GI visit handled with imaging, supportive care, and targeted gut support|1|The veterinarian built the workup around the most likely causes without overcommitting too early.|The discussion used x-rays, probiotics, nausea control, and B12 support to separate constipation from primary intestinal disease.|options,staged,risk,rep
192206|Winnie|Dog|Nosebleed visit using local control, OTC support, and escalation only if needed|1|The veterinarian chose a low-intensity first plan while still naming the threshold for doing more.|The discussion included calming medication, Yunnan Baiyao, optional OTC allergy support, and a scope-first escalation only for recurrence.|options,pharmacy,staged,risk,min,rep
192254|Noelle|Cat|Simple forelimb soft-tissue injury managed without a larger workup|1|The veterinarian kept the plan at the minimum responsible level because the exam fit a mild strain.|The discussion stayed on rest, pain relief, and ordinary follow-up without opening a broader option set.|staged,min,nooption
192390|Naka|Dog|Routine puppy visit with house-soiling explained as a behavior pattern|1|This stayed in preventive and training territory rather than becoming a live medical tradeoff case.|The conversation focused on vaccines, stool recovery, and likely excitement urination with no major treatment branch.|staged,nooption
192470|Kirby|Dog|Cancer-dog recheck centered on transfer paperwork and comfort medication|1|The veterinarian kept the visit practical and goal-directed for a dog with limited reserve.|The discussion covered rabies documentation, transfer logistics, and anti-inflammatory support rather than a bigger diagnostic expansion.|options,staged,risk,barrier
192507|Scooter|Dog|Anal-gland and broken-nail visit handled with local care and simple support|1|The veterinarian kept the problem small because it already fit straightforward outpatient care.|The discussion stayed on gland expression, paw protection, and a supplement suggestion for recurrence without broader branching.|staged,min,nooption
192874|Larry|Cat|Resolving eye irritation visit offering treatment now or simple monitoring|1|The veterinarian offered a real but low-stakes choice because the problem looked self-limited.|The discussion compared supportive treatment against watchful waiting for a cat already improving on its own.|options,staged,min
193162|Sophie|Dog|Vaccine-reaction recheck using medication and local care rather than a larger workup|1|The veterinarian treated the complication conservatively while still naming the secondary infection risk.|The discussion moved across antibiotics, Benadryl, warm compresses, and simple monitoring for a localized vaccine-site flare.|options,staged,risk,min
193214|Dory|Dog|Urinary-incontinence visit reframed around liver-safe medication choice|1|The veterinarian changed the plan because the comorbidities made the obvious drug less attractive.|The discussion compared Proin against Incurin, tied the choice to liver concerns, and kept blood pressure and urine findings in the decision.|options,staged,risk,rep
193259|Lily|Cat|Weight-loss and PU-PD workup built around the big senior-cat differential list|1|The veterinarian used a broad but orderly diagnostic frame rather than jumping to one disease label.|The discussion centered on kidney disease, thyroid disease, and diabetes while explaining why a send-out workup was the next responsible step.|options,staged,risk,rep
194176|Cassis|Cat|Constipation-diarrhea visit treated as a senior-cat motility problem with hydration questions|1|The veterinarian treated the GI pattern as a real management issue instead of a quick one-note diagnosis.|The discussion linked constipation and diarrhea to arthritis and hydration, kept probiotics in play, and worked through practical next steps with the family.|options,staged,risk
194292|Rex|Dog|Luxating-patella lameness visit handled with conservative support before surgery|1|The veterinarian framed the knee problem honestly but resisted pushing an operation too early.|The discussion graded the patella, used anti-inflammatories now, and left surgery for a more advanced stage.|options,staged,min
194345|Rylee|Dog|Contralateral ACL injury visit with swelling, laxity, and surgery context explained clearly|1|The veterinarian treated the new lameness like the next likely orthopedic chapter, not a mystery injury.|The discussion tied the sudden non-weight-bearing pattern to a likely cruciate tear and explained why surgery often follows once the tear is complete.|options,staged,risk,rep
194374|Mr. Mittens|Cat|Urinary-crystal visit managed preemptively when the bladder was too empty to sample|1|The veterinarian offered a true fork between waiting for a sample and treating the most likely problem immediately.|The discussion compared fluids-and-observation against preemptive treatment, then used urinary diet and an antibiotic injection to cover crystals and possible infection.|options,staged,risk,rep
194410|Lucy|Dog|Tooth-root abscess visit with cheaper pills and echo-gated dental planning|1|The veterinarian built a bridge plan that respected both the heart murmur and the owner's financial friction.|The discussion covered antibiotics, liver-safer pain control, pill-versus-liquid cost, and echocardiography before definitive dental care.|options,money,pay,staged,risk,rep
194424|Rhea|Dog|Straightforward UTI treated with first-line medication and culture only if needed|1|The veterinarian kept the case narrow because the urine findings already gave a workable answer.|The discussion centered on amoxicillin now, culture later only if improvement failed, and no diet change because crystals were not actually driving the picture.|staged,nooption
194444|Bear|Dog|Intestinal-tumor consult weighing referral surgery against doing nothing for now|0|The veterinarian was direct about the stakes while admitting the outcome depended on what surgery would actually find.|The discussion contrasted specialty surgery, recovery expectations, and the possibility of wider disease against the option of not intervening.|options,staged,risk,rep
194453|Bo|Dog|Cervical-disc follow-up built around long-term management and rehab realism|1|The veterinarian shaped the chronic plan around what the dog had actually responded to instead of starting from scratch.|The discussion covered long-term gabapentin, safer use of Rimadyl, confirmatory thyroid testing, and rehab support for muscle rebuilding.|options,staged,risk
194461|Bruno|Dog|Pancreatitis hospitalization update focused on supportive care and expected recovery|1|The veterinarian treated the case as a known inpatient problem rather than reopening the whole differential.|The discussion stayed on appetite stimulation, pain control, bland feeding, and why pancreatitis often just needs time and support.|staged,risk,nooption
196525|Dakota|Dog|Vomiting and odd-breathing visit using x-rays and supportive GI logic|1|The veterinarian framed x-rays as a safety check while still leaning toward outpatient stomach care.|The discussion contrasted imaging with symptomatic treatment and named pancreatitis as the main concern behind the nausea and appetite loss.|options,staged,risk,rep
196735|Mia|Dog|Routine vaccine and screening visit without a live medical decision fork|1|This was preventive maintenance rather than a transcript about affordability or alternatives.|The conversation stayed on vaccines, testing, and routine exam findings with no substantive branching care plan.|nooption
197132|Ghost|Unknown|Mixed internal capture combining an IMHA call and side conversations about other cases|1|This file is too blended and nonstandard to treat as a clean exam-room option-setting transcript.|The usable content is mostly clinician-to-clinician management talk and hallway case discussion rather than a coherent owner-facing visit.|nooption
197256|Elvis|Dog|Vaccine-reaction prevention visit handled with premedication and reduced intensity|1|The veterinarian kept the visit narrow and protective because the dog already had a known pattern of reacting.|The discussion focused on Benadryl timing, steroid premedication for later vaccines, and keeping the preventive plan light.|staged,risk,nooption
197567|Bentley|Dog|Conjunctivitis visit using stain-first logic before steroid-based eye treatment|1|The veterinarian preserved the faster-healing option by first ruling out the reason it would be dangerous.|The discussion centered on checking for an ulcer, then using steroid-containing eye drops and catching up vaccines in the same visit.|options,staged
197705|Sofie|Cat|Chronic sneezing visit treated as likely herpes with low-intensity support first|1|The veterinarian used the common cat explanation and a simple supplement plan before anything more aggressive.|The discussion framed the pattern as feline herpes, recommended lysine-style support, and kept antibiotics in reserve for worse flares.|options,staged,risk,min
198076|Om|Dog|Boarding-behavior visit centered on sedation strategy and practical handling barriers|1|The veterinarian focused on what would actually help the dog function in the real boarding context.|The discussion moved across gabapentin, trazodone, CBD habits, eye and ear cleanup, and the possibility of Prozac for a chronically stressed dog.|options,staged,barrier
198174|Iggy Mae|Dog|Heart-disease staging call tied directly to safer dental planning|1|The veterinarian turned the echo result into a concrete next step rather than a vague warning.|The discussion explained stage B2 disease, the role of pimobendan, and how dental disease and cardiac management now had to be linked.|options,staged,risk,rep
198188|Ghost|Unknown|Duplicate mixed internal IMHA and mast-cell capture without a clean owner visit|1|This duplicate file is not a normal exam-room transcript for cost-of-care coding.|The content remains mostly clinician discussion, so it does not add a distinct owner-facing option sequence.|nooption
198189|Ghost|Unknown|Second duplicate of the same mixed internal IMHA and mast-cell capture|1|This file again behaves like a duplicated internal conversation rather than a visit transcript.|The record is too blended to code as a separate affordability conversation beyond noting that it is nonstandard.|nooption
198190|Ghost|Unknown|Third duplicate of the same mixed internal case discussion|1|This file also reads like a duplicate internal capture, not a discrete visit.|There is no additional clean owner-facing option sequence here beyond the already mixed case-management talk.|nooption
198268|Kino|Dog|Acute red-eye visit using stain-first logic to separate allergy from an ulcer|1|The veterinarian sorted the eye by risk before reaching for the medication that would otherwise heal it fastest.|The discussion compared allergic irritation, foreign material, and corneal ulcer while tying treatment choice to the stain result.|options,staged,risk
200388|Henry|Dog|Seasonal allergy visit with diet and long-term itch-control options discussed openly|1|The veterinarian treated the eye and skin pattern like chronic allergy management rather than a one-off flare.|The discussion stayed on Apoquel, Cytopoint as a possible next step, probiotic support, and whether a different diet would help the gas.|options,staged
201632|Ash|Dog|Bloody-discharge workup that quickly shifted toward ovarian-remnant disease|1|The veterinarian escalated from ordinary causes to the rare surgical explanation without overcomplicating the path.|The discussion moved from urine and cytology to ovarian-remnant testing, antibiotics for possible vaginitis, and possible corrective surgery if confirmed.|options,staged,risk,rep
201890|Ozzy|Dog|Reactive-dog vaccine visit with medication and prevention timing adjusted pragmatically|1|The veterinarian used a practical medication sequence to avoid waste and reduce handling friction.|The discussion covered Bravecto now, Simparica Trio later, owner-applied muzzle logistics, and a back-room handling plan for a reactive dog.|options,pay,staged,barrier
201903|Ellie|Dog|Possible baby-wipe ingestion handled with x-rays before anything invasive|1|The veterinarian picked the moderate diagnostic step rather than jumping straight to anesthesia.|The discussion compared x-rays, bulk-diet monitoring, and endoscopic retrieval while explaining what vomiting had or had not already ruled out.|options,staged,risk,rep
201955|Nala|Dog|Forelimb tricep strain treated with medication and joint support instead of imaging|1|The veterinarian localized the problem enough to keep the plan simple and conservative.|The discussion stayed on anti-inflammatories, a joint supplement, and the expectation of quick improvement for a muscle injury.|options,staged,min
202188|Braxton|Dog|Addisonian recheck focused on potassium trend and home medication continuity|1|The veterinarian treated the case as a known endocrine problem with one final discharge checkpoint.|The discussion centered on potassium normalization, Percorten timing, daily prednisone, and what ongoing refill support would look like.|staged,risk,nooption
202239|Teddy|Dog|Liver-value follow-up using diet adjustment, anti-nausea support, and later ultrasound if needed|1|The veterinarian let the improving trend justify a staged approach instead of forcing imaging immediately.|The discussion covered bland or prescription diet options, anti-nausea medication, and ultrasound later if the liver values rose again.|options,staged,risk,rep
202284|Penny|Dog|Rabies-only follow-up without a substantive treatment or affordability branch|1|This was a straightforward preventive recheck rather than an options conversation.|The discussion stayed on the rabies vaccine and ordinary recovery questions after prior surgery.|nooption
202328|Cooper|Dog|Explosive-diarrhea recheck using fiber-forward diet support before anything more invasive|1|The veterinarian pushed the highest-yield gut support rather than widening the workup too early.|The discussion added GI Biome, paste support, and fecal testing while keeping the rest of the plan conservative because the dog still felt okay.|options,staged,rep
202368|JJ|Dog|Kennel-cough visit using cough tablets and harness changes instead of antibiotics|1|The veterinarian treated the likely viral case with the least necessary intervention while naming the warning signs.|The discussion covered cough suppressants, harness use, daycare restriction, and how fever or yellow discharge would change the plan.|options,staged,risk,min
202418|Leo|Dog|Single-vomiting visit that shifted attention toward a likely infected mass or abscess|1|The veterinarian kept the immediate care simple while pushing the owner to take the swelling more seriously than the vomiting.|The discussion used an anti-nausea injection and antibiotics, with ultrasound or sampling later if the lump failed to shrink.|staged,risk,nooption
202468|Weedle|Dog|Routine Bordetella visit with only a brief luxating-patella counseling aside|1|This remained a maintenance visit rather than a meaningful spectrum-of-care conversation.|The discussion focused on a kennel-cough vaccine, routine exam findings, and reassurance about a low-grade patella issue.|nooption
202530|Buzz|Dog|Stress-colitis visit that expanded into chronic dry-eye management and GI support|1|The veterinarian built a practical home plan because the dog still fit outpatient care.|The discussion covered GI Biome, probiotic support, possible stress colitis, and a more effective dry-eye medication sequence.|options,staged,risk,rep
202619|Snow|Cat|IMHA recheck focused on steroid tapering after a strong hematocrit recovery|1|The veterinarian narrowed the visit to safe tapering because the key number had improved dramatically.|The discussion centered on reducing prednisone, timing the next CBC, and maintaining the current plan unless the numbers fell again.|staged,risk,nooption
202713|Sam|Dog|UTI and crystal visit combining antibiotics, x-rays, and a dissolving diet|1|The veterinarian treated the urinary problem as both an infection and a urine-environment issue.|The discussion covered bacteria, two crystal types, stone screening, diet restriction, and why treats had to be limited during dissolution.|options,staged,risk,rep
202846|Minnie|Dog|Wellness visit that surfaced murmur and arthritis concerns needing separate follow-through|1|The veterinarian turned a routine visit into a staged senior-care plan without forcing everything at once.|The discussion moved from vaccines and lumps to echocardiography for the murmur and possible arthritis support for slowing down.|options,staged,risk,rep
203010|Charlie|Dog|Acute weakness workup that quickly became a surgery-versus-euthanasia cancer conversation|0|The veterinarian moved straight to the hard truth once imaging showed a large abdominal mass.|The discussion contrasted surgery against euthanasia and framed the dog's sudden collapse as a likely cancer-driven crisis rather than a simple stomach upset.|options,staged,risk,rep
203031|Nicole|Dog|Low-thyroid callback using confirmatory testing instead of immediate lifelong treatment|1|The veterinarian avoided overcalling a single lab value and kept the next step diagnostic.|The discussion centered on euthyroid-sick syndrome versus true hypothyroidism and recommended the more complete thyroid panel before committing to supplements.|options,staged,risk
203256|Alfie|Dog|Routine prevention visit with vaccine and refill logistics but no major care fork|1|This was a straightforward wellness encounter rather than a live affordability case.|The discussion stayed on vaccines, heartworm testing, and routine Simparica Trio refill questions.|nooption
203388|Tinkerbell and Fozzie|Unknown|Two-pet wellness visit where the dog's anxiety and allergy support opened the only real branch|1|The medically interesting part of the visit was the dog's chronic anxiety and itch management, not the cat's routine vaccine update.|The discussion covered CBD options, ear cleaning, Cytopoint timing, and handling anxiety in a dog already doing well otherwise.|options,staged,barrier
203485|Charlie|Dog|Routine diabetic wellness visit with vaccines and screening only|1|This remained a maintenance encounter rather than a conversation about treatment alternatives.|The discussion stayed on vaccines, heartworm screening, insulin continuity, and routine exam findings.|nooption
203561|Ghost|Dog|IMHA follow-up with cheaper OTC GI support added to an already-complex plan|1|The veterinarian combined close disease monitoring with a practical lower-cost medication route for the GI side effects.|The discussion covered improving red-cell trends, Cerenia refill, cheaper OTC omeprazole, and ongoing immunosuppression for a complicated IMHA case.|options,money,pay,pharmacy,staged,risk,rep
203681|Dixie|Dog|Chronic-pancreatitis callback using anti-nausea bridging while ultrasound was considered|1|The veterinarian used symptom control now while still pointing toward imaging for the deeper answer.|The discussion tied chronic pancreatitis to diet sensitivity, explained why ultrasound was the next structural check, and bridged with crushable anti-nausea meds.|options,staged,risk,rep
203801|Luna|Dog|Skin-tag visit with cytology now and low-stakes treatment choices afterward|1|The veterinarian made the lesion more knowable right away and kept the likely interventions proportional.|The discussion compared ointment, local removal, and simple monitoring, while also answering a side question about a much more expensive eye procedure on another dog.|options,money,staged,risk
203829|Fox|Dog|Gastric-bleed consult weighing surgery now versus a short ulcer-healing trial|1|The veterinarian gave the family a real wait-versus-act choice instead of pretending the stomach nodule had only one answer.|The discussion covered cancer versus stubborn ulcer, surgical referral, expected costs, and what improvement over two weeks would mean diagnostically.|options,money,staged,risk,rep
203869|Shah|Cat|Travel-rabies visit with sedation planning as the main problem to solve|1|The veterinarian treated travel stress as the real barrier and offered a practical medication answer.|The discussion stayed on the rabies certificate, Bonqat timing, and routine annual-care expectations for a healthy indoor cat.|options,staged,barrier
208548|Jane|Dog|High-fever workup that led to hospitalization for a likely infection of unknown source|1|The veterinarian did not pretend to know the source yet, but still made the inpatient recommendation concrete.|The discussion compared outpatient support against hospitalization, tied the decision to the persistent 105 fever, and kept a fever hunt frame around the next diagnostics.|options,money,staged,risk,rep
208644|HB Dickens|Dog|Tracheitis visit using cough tablets and routine vaccine updates in one stop|1|The veterinarian treated the airway irritation conservatively because the dog still fit a mild tracheitis pattern.|The discussion tied the coughing to tracheal irritation from pulling, recommended cough tablets, and folded in the overdue preventive care.|options,staged,min
208791|Louise and Thelma|Cat|Two-cat wellness visit without a substantive illness or affordability branch|1|This was a paired preventive visit rather than an options-heavy medical case.|The conversation stayed on routine vaccines, weights, and ordinary home-life questions for otherwise healthy cats.|nooption
209116|Cassis|Cat|Follow-up visit after fecal plugging used hygiene and as-needed pain control rather than escalation|1|The veterinarian kept the plan practical because the cat was already improving once the blockage was cleared.|The discussion centered on sanitary clipping, gabapentin as needed, probiotic and hydration support, and keeping the rear end easier to manage.|options,staged,risk,rep
209455|Zelda|Dog|Marijuana-ingestion visit handled with supportive care instead of an expensive workup|1|The veterinarian recognized the classic tox pattern and treated it as a time-and-support problem.|The discussion stayed on fluids, anti-nausea medication, monitoring, and why the wobbling and urine dribbling fit marijuana exposure.|options,staged,risk,min
209582|Bentley|Dog|Persistent allergy and skin-itch visit shifting from Cytopoint alone to Apoquel too|1|The veterinarian moved to the next itch-control layer because the first one helped but had not solved it.|The discussion focused on lingering skin irritation, Cytopoint response, ear debris, and adding Apoquel plus topical support.|options,staged
214438|Lily|Dog|Post-boarding stress-colitis visit treated with GI support and anti-nausea care|1|The veterinarian treated the problem like a typical stress-gut flare while still naming the warning signs.|The discussion used metronidazole, a probiotic, anti-nausea medication, fluids, and bland diet support instead of opening a larger workup immediately.|options,staged,risk,min
214443|Puddles|Cat|Outdoor-cat wound visit weighing natural healing against more procedural repair|1|The veterinarian offered a true low-intensity alternative because the wound had already started to granulate.|The discussion contrasted sedation and closure against an antibiotic injection plus watchful healing, while also checking that the earlier urinary concern had resolved.|options,staged,risk,min
214472|Ally|Dog|Chronic tracheitis visit managed with cough tablets and harness changes first|1|The veterinarian treated the airway noise conservatively because the heart and lungs still sounded good.|The discussion framed the cough as tracheal irritation or collapse, used cough tablets, and recommended harness-only walking before anything stronger.|options,staged,risk,min
214473|Dozer|Dog|Acute facial-swelling visit treated as an allergic reaction with emergency basics|1|The veterinarian did not broaden the case because the treatment path was already clear.|The discussion centered on epinephrine, dexamethasone, higher Benadryl dosing, and observation for a likely bite-driven allergic reaction.|staged,risk,nooption
214477|Nero|Dog|Back-pain flare treated with familiar medications rather than a larger new workup|1|The veterinarian treated the episode like another disc-related pain event that still fit outpatient care.|The discussion used Rimadyl, gabapentin, and a starter injection while tying the trigger to rough play and prior spine history.|staged,risk,nooption
214482|Luna|Dog|Bloody-vomit and bloody-diarrhea visit balancing outpatient support against hospitalization|1|The veterinarian gave a real inpatient-versus-outpatient fork while explaining why the bleeding looked less exotic than the owners feared.|The discussion covered anti-nausea treatment, fluids, blood in vomit versus stool, and the possibility of hospitalization if the dog could not turn around at home.|options,staged,risk,rep
214527|Daisy|Dog|Hemorrhagic-diarrhea visit treated as an immediate hospitalization case|1|The veterinarian was clear that the level of bloody diarrhea moved the case out of routine outpatient care.|The discussion framed acute hemorrhagic diarrhea syndrome, the dehydration risk, and why IV fluids and monitoring were the safer path than sending her home.|options,staged,risk,rep
214537|Bear|Dog|Thong-ingestion visit using x-rays and induced vomiting before surgery was even considered|1|The veterinarian chose the least invasive useful path and then successfully cleared the stomach.|The discussion moved from localization on x-ray to induced vomiting, anti-nausea support, and normal feeding again once the material was out.|options,staged,risk,min
214540|Enzo|Dog|Tick-removal visit focused on prevention, surveillance, and no premature overtreatment|1|The veterinarian kept the response proportionate because recent tick attachment does not equal immediate Lyme disease.|The discussion covered pulling the ticks, staying on Trio, checking Lyme status later, and only treating if later signs or testing justified it.|options,staged,risk,min
214541|Bruno|Dog|Dental-pain consult framed around anesthesia risk, seizure history, and short-term comfort|1|The veterinarian kept the dog safe in the short run while being honest that a full dental still needed anesthesia somewhere.|The discussion covered why mask sedation does not solve dental access, why the dog still looked stable overall, and how Rimadyl could bridge the pain until the scheduled dental.|options,staged,risk,rep
214544|August|Cat|Diabetic cat with nausea treated as a stomach-upset flare rather than ketoacidosis|1|The veterinarian first ruled out the dangerous diabetic branch and then treated the more likely GI one.|The discussion covered normal ketones, anti-nausea treatment, fluids, diet consistency, probiotic support, and only giving insulin if the cat actually ate.|options,staged,risk,min
214545|Max|Dog|Bulldog breathing revisit using repeat x-rays before changing pneumonia treatment|1|The veterinarian used side-by-side imaging and a calmer overnight plan instead of jumping straight to major escalation.|The discussion compared repeat x-rays, stronger antibiotics, and sedation for rest while keeping the bulldog airway context front and center.|options,staged,risk,rep
214546|Princess|Dog|Collapse visit revealing pericardial effusion and likely heart-base cancer|0|The veterinarian moved rapidly from symptom history to a true end-of-life versus specialty-rescue conversation.|The discussion covered draining the pericardium, likely heart-base tumor, referral to cardiology, and euthanasia as the humane alternative if they did not want to pursue heroic care.|options,staged,risk,rep
214547|Abby|Dog|Open-pyometra visit where antibiotics and low-cost surgery logistics replaced emergency surgery|0|The veterinarian named emergency surgery as the cleanest answer but still translated the case into a lower-cost path once that was the owner's reality.|The discussion confirmed pyometra on x-ray, explained open versus closed risk, and shifted to antibiotics plus next-day low-cost clinic planning when immediate surgery was declined.|options,money,pay,staged,risk,rep,alternativeOnDecline
214551|Cheech|Dog|Back-pain revisit managed with more aggressive home medication timing and gut support|1|The veterinarian treated the shaking like pain first while still covering the possibility that stress had upset the gut too.|The discussion increased gabapentin, refilled Rimadyl, added a probiotic, and explained why back pain and stomach stress can look similar.|options,staged,risk,rep
216492|Mya|Cat|Chronic GI and weight-loss case moved toward ultrasound rather than reflex steroids|1|The veterinarian protected the diagnostic yield of the next test instead of masking it with premature treatment.|The discussion linked B12 history, possible IBD or lymphoma, anti-nausea support, and delayed steroids until after abdominal ultrasound.|options,staged,risk,rep
216966|Hans|Dog|Reactive-dog vaccine and boarding-prep visit solved through handling and topical allergy support|1|The veterinarian turned a hard handling problem into a practical boarding-clearance plan.|The discussion covered vaccines, fecal clearance, trazodone and gabapentin for future visits, and a mousse for itchy skin once the dog proved calmer in back.|options,staged,barrier
217050|Paris|Cat|Routine vaccine and matting visit where future grooming logistics were the only real branch|1|The main issue was not medical complexity but how to handle future grooming without overusing sedation.|The discussion stayed on vaccines, mild mat trimming, and whether a higher gabapentin dose before a tech appointment would make home or clinic grooming workable.|options,staged,barrier
217183|Drake|Dog|Conjunctivitis visit using a stain and steroid-antibiotic drops with allergy context|1|The veterinarian treated the eye as a real but manageable local problem and kept the allergy frame visible.|The discussion used a corneal stain, confirmed no ulcer, chose steroid-containing drops, and tied the flare to seasonal skin and eye sensitivity.|options,staged,risk
217223|Kenobi|Dog|GI-upset visit handled with anti-nausea care and fluids instead of immediate imaging|1|The veterinarian stayed at the minimum responsible level because the dog still fit straightforward gastroenteritis.|The discussion focused on nausea control, subcutaneous fluids, bland feeding, and return precautions after likely grass or chemical irritation.|staged,risk,min,nooption
217808|Blue|Dog|Classic kennel-cough visit treated conservatively because the dog was vaccinated and stable|1|The veterinarian stayed with supportive care while naming the signs that would justify antibiotics later.|The discussion covered cough tablets, harness use, daycare restriction, and the meaning of green discharge in an otherwise mild kennel-cough case.|options,staged,risk,min
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected',
    alternativeOnDecline: 'alternativeOnDecline'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 16',
      date: '2026-03-19',
      selectionSeed: '20260319-wave16',
      selectionMethod: 'Sixteenth non-overlapping 100-transcript backlog batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1500_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
