window.ANDY_ANALYSIS_BATCH10 = (() => {
  const rows = `
27150|Indy|Dog|Vomiting visit with vaccine and Librela staging|1|The veterinarian staged care around what could safely wait while the dog was sick.|The discussion held vaccines, kept Librela available, and added blood work and anti-nausea support rather than treating everything as urgent.|options,staged,risk
27196|Blackie|Cat|Chronic skin and eye flare with pain-versus-allergy framing|1|The veterinarian treated the case as a layered chronic problem instead of defaulting to one explanation.|The discussion moved through eye care, pain versus allergy reasoning, and a possible Solensia path while keeping steroid timing and prior history in view.|options,staged,risk
27221|Rigatoni|Dog|Boarding-related diarrhea with conservative GI first step|1|The veterinarian used a minimum-responsible outpatient plan before moving to heavier diagnostics.|The discussion centered on bland diet and probiotic support, held metronidazole and diagnostics in reserve, and gave clear monitoring boundaries.|options,staged,min
27260|Maru|Cat|Ear recheck with narrowed continuing-care plan|1|This was a simple follow-up that still adjusted the plan rather than reflexively restarting everything.|The discussion focused on improvement, one more week of drops, and whether the ear and hematoma were healing as expected.|options,staged
27444|Rocky|Dog|Arthritis visit with Librela and rehab branches|1|The veterinarian handled mobility decline as a multi-path chronic-care problem.|The discussion compared Librela, other pain-control paths, and rehab-style support while keeping expectations realistic for an older dog.|options,staged,risk
27530|Marty|Dog|Wellness visit with ear care and optional dental deferral|1|This was mostly preventive care with one small practical branch about whether dental work could wait.|The encounter centered on vaccines, ear cleaning, screening blood work, and reassurance that dental timing could reasonably slide a year.|nooption
27592|Millie and Ozzie|Cat|Routine kitten vaccine and sex-confirmation visit|1|This was a preventive kitten visit where alternatives were not really the issue.|The discussion focused on vaccine timing, post-spay healing, and clarifying that both kittens were female rather than opening a real care-path decision.|nooption
27593|Millie and Ozzie|Cat|Duplicate-like kitten preventive follow-up|1|This duplicate-like file still reads as a routine preventive visit rather than an options conversation.|The usable material stays with vaccine completion, incision healing, and sex clarification instead of affordability or staged treatment choices.|nooption
27617|Sigma|Cat|Post-vaccine illness with optional imaging and supportive care|1|The veterinarian offered a real diagnostic branch while still trying to keep the first step practical.|The discussion contrasted supportive care against an x-ray with the cost made visible, and it kept obstruction and worsening risk explicit.|options,money,staged,risk
29560|Odin|Dog|Puppy diarrhea with outpatient support and fecal later|1|The veterinarian kept the plan narrow and outpatient for a still-stable puppy GI case.|The discussion used probiotics, bland diet, and delayed fecal testing until the stool was more workable instead of escalating immediately.|options,staged,min
29586|Luna|Cat|Urinary infection discussion with oral-versus-injection treatment|1|The veterinarian used a small but meaningful treatment branch once the likely diagnosis was clearer.|The discussion moved through urine findings, explained the likely infection, and compared oral medication against a one-time injection.|options,staged,risk
29649|Ricky|Dog|Acute pain visit with injectable-first comfort plan|1|The veterinarian treated a painful small-dog episode as likely back pain and kept the plan conservative.|The discussion used an in-clinic pain shot, next-day oral medication, and monitoring for vomiting or diarrhea rather than jumping to a larger workup.|options,staged,risk,min
29678|Squeaky|Cat|Urinary-versus-GI case with urine-first workup|1|The veterinarian separated the urinary concern from the diarrhea concern and kept antibiotics conditional.|The discussion prioritized urine testing, bladder support, and probiotic care while explaining why unnecessary antibiotics could worsen the stool problem.|options,staged,risk,min
29840|Lucy|Dog|Reverse-sneeze and allergy visit with cough tablets held in reserve|1|The veterinarian chose anti-itch treatment first and left stronger cough suppression as a later step.|The discussion contrasted collapsing-trachea versus allergy irritation, added Benadryl guidance, and kept cough tablets for worsening frequency only.|options,staged,risk,min
29852|Tsunami|Cat|Stable chronic-care and vaccine follow-up|1|This was mainly a chronic-maintenance visit where alternatives were not really the issue.|The encounter focused on cardiac and kidney medication continuity, vaccines, and routine blood work rather than on a meaningful care-path branch.|nooption
29887|Felix|Cat|Diabetic cat with arthritis-versus-skin reasoning|1|The veterinarian used a staged approach to limping and scabbing in a medically constrained cat.|The discussion compared Solensia against further workup, explained why steroids were off the table, and tied the skin changes back to likely self-trauma from pain.|options,staged,risk
30110|Bentley|Dog|Large leg laceration with closure-versus-open-management framing|1|This was a strong urgent-care discussion that still preserved the difference between the best case and the fallback plan.|The veterinarian explained sedation and suturing as the likely path, but also prepared the owner for prolonged wet-to-dry bandaging if tension prevented closure.|options,staged,risk,rep
30131|Ivy|Dog|Situational-anxiety visit with trazodone dose testing|1|The veterinarian gave a practical branch for a real-life behavior problem rather than overcomplicating it.|The discussion focused on trazodone timing, dose testing before holiday gatherings, and keeping the dog calmer without over-sedating her.|options,staged,min
30237|Ivy|Cat|Mixed chronic-sneeze and dental-planning capture|1|Even as a somewhat blended file, the visit still shows staged chronic-care reasoning.|The discussion moves through upper-respiratory management, dental planning, and medication timing rather than presenting one rigid all-at-once answer.|options,staged,risk
30255|Teddy|Dog|Routine wellness and weight-counseling visit|1|This was a preventive visit where alternatives were not really the issue.|The encounter focused on vaccines, calorie guidance, and minor maintenance questions rather than on a meaningful affordability or spectrum-of-care discussion.|nooption
32069|Charles|Dog|Recurring ear infection with clinic-based treatment barrier|1|The veterinarian matched the plan to the fact that home ear medication is hard in this dog.|The discussion used clipping, deep cleaning, and an ear-pack style medication because repeated at-home treatment was not realistic for the owner.|options,staged,barrier
32148|Om|Dog|Too-fragmentary shepherd preventive capture|1|The available source is too staff-heavy to support nuanced option coding.|Most of the usable text is setup chatter around a shepherd wellness visit rather than a developed owner-facing care-path discussion.|nooption
32196|Calvin|Cat|Vomiting cat with string concern and x-ray-first plan|1|The veterinarian used imaging first and only then planned supportive care if the study was clean.|The discussion explained what would make the cat a surgery concern, contrasted x-rays against fluids and anti-nausea treatment, and kept obstruction risk visible.|options,staged,risk,rep
32197|Calvin|Cat|Duplicate-like vomiting and possible-string workup|1|This duplicate-like capture still reflects staged obstruction reasoning rather than reflex treatment.|The veterinarian again moved from oral exam to x-rays first, with fluids and anti-nausea support held for the non-obstructive branch.|options,staged,risk
32286|Margaret|Cat|Eye squint visit with stain-first treatment branch|1|The veterinarian used the stain result to determine how simple the treatment path could stay.|The discussion ruled out a scratch first and then moved to drop therapy once the eye looked more like conjunctivitis than ulceration.|options,staged
32325|Ziggy|Dog|Allergy-heavy visit with ears eyes skin and limp in play|1|Even as a messy capture, the file still shows stepwise problem sorting rather than one blanket answer.|The discussion moved through tear testing, ear treatment, skin support, Cytopoint, and a possible x-ray path for the leg if pain persisted.|options,staged,risk
32477|Selene and Michael|Dog|Puppy visit with vaccine sequencing and neuter timing|1|The veterinarian used straightforward staging around age and reproductive timing rather than treating everything as due now.|The discussion set the vaccine schedule, explained safe socialization boundaries, and planned spay-neuter timing around sexual maturity and an undescended testicle check.|options,staged,risk
32526|Louie|Dog|Eye redness visit with stain-guided drop choice|1|The veterinarian used the corneal check to decide whether a steroid-containing eye medication was safe.|The discussion explained scleritis, linked it to irritation or rubbing, and kept the stronger antibiotic-steroid drop contingent on a clean stain result.|options,staged,risk
32549|Prevenza|Cat|Severe trauma case with prognosis and euthanasia path|1|This was a serious prognosis conversation where real options were still laid out plainly.|The case centered on traumatic injury, likely internal damage, and the difference between further imaging or treatment attempts versus humane euthanasia.|options,staged,risk,rep
32876|Lexie|Dog|Cough and allergy visit with anti-itch first and cough tabs later|1|The veterinarian chose the smaller allergy-targeted move first and reserved cough medicine for persistence.|The discussion tied the episodes to likely itch or airway irritation, added anti-itch medication and Benadryl, and kept cough tablets as a later branch.|options,staged,min
32919|Bella|Dog|Routine wellness and bordetella update|1|This was a straightforward preventive visit where alternatives were not really the issue.|The encounter focused on routine vaccination, prevention refills, and a normal wellness check rather than on a meaningful care-path discussion.|nooption
32967|Stella|Dog|Senior diarrhea workup with x-ray and GI Biome fallback|1|The veterinarian used imaging to rule out the bigger problem before leaning into supportive care.|The discussion found no mass or obstruction, explained gastroenteritis on x-ray, and moved to GI Biome, anti-nausea support, and ultrasound only if recurrence continued.|options,staged,risk,rep
33001|Leo|Dog|Dental planning changed by new heart-murmur finding|1|The veterinarian kept the dental plan but inserted the right cardiac checkpoint before anesthesia.|The discussion identified one dead tooth, explained the new murmur, and moved the case toward an echocardiogram before scheduling the next dental event.|options,staged,risk
33037|Hank|Dog|Routine vaccine visit with weight and cyst counseling|1|This was mainly a maintenance visit where alternatives were not really the issue.|The encounter focused on routine vaccines, calorie measurement, and reassurance about a small cyst rather than on a meaningful spectrum-of-care choice.|nooption
33052|Nala|Dog|Soft-stool and itch visit with probiotic and injection branch|1|The veterinarian used simple supportive care and matched the itch treatment to what the owner could actually do.|The discussion paired probiotic paste and bland diet with an injectable allergy option because pills were unlikely to work well at home.|options,staged,min
33228|Lucy|Dog|Head hot spot or abscess with shave-and-treat plan|1|The veterinarian started with the smallest practical wound plan and escalated only as needed.|The discussion framed the lesion as a hot spot versus abscess, used clipping and topical plus oral antibiotics, and warned that the wound might look worse once fully exposed.|options,staged,risk,min
33259|Tazz|Dog|Perianal mass visit with monitor-versus-removal reasoning|1|The veterinarian explained why watchful waiting was reasonable before pushing surgery.|The discussion framed the lesion as most likely a benign perianal adenoma, kept other differentials in mind, and reserved removal for growth or stool interference.|options,staged,risk,min
33310|Daisy|Dog|Prednisone-side-effect review with slow taper planning|1|The veterinarian used a staged taper and practical monitoring around a dog already paying for treatment side effects.|The discussion covered steroid-related muscle loss and urination, infection worries in an immunosuppressed dog, and a careful plan to back down the prednisone instead of stopping abruptly.|options,staged,risk,barrier
33334|Sixx|Dog|Allergic paw flare with layered itch-control plan|1|The veterinarian treated the case as allergy-driven licking with secondary infection, not as one isolated lesion.|The discussion combined Apoquel, oral antibiotics, and continued mousse use while explaining why the itch cycle had to be broken first.|options,staged,min
33346|Harley|Dog|Torn dewclaw visit with open-versus-wrapped care decision|1|The veterinarian adjusted the nail plan to the dog's actual licking behavior rather than following a default script.|The discussion favored antibiotics and pain control either way, but switched from open management to a bandaged plan once the owner described how much the dog licks.|options,staged,risk
33354|Leo|Cat|Recurring pink-eye flare with ointment and lysine plan|1|The veterinarian treated the episode as another stress-linked flare rather than a brand new mystery.|The discussion moved from ulcer check to Terramycin-style ointment, added lysine support, and explained the latent-herpes pattern that makes these cats recur.|options,staged,risk,min
33549|Bonnie|Dog|Post-dental recheck with retained-suture irritation|1|This was mostly a focused follow-up rather than a new options conversation.|The veterinarian found one dissolving stitch likely causing the rubbing, advised finishing the existing antibiotic course, and otherwise reassured the family that healing looked good.|nooption
33598|Lucy|Dog|Ear infection attributed to moisture and bathing routine|1|The veterinarian used a simple local plan and preventive explanation for a very common problem.|The discussion paired ear cleaning and daily medication with practical advice about drying the ears after baths rather than opening a broader workup.|options,staged,min
33673|Luna|Dog|Routine vaccine and heartworm screening visit|1|This was a preventive visit where alternatives were not really the issue.|The encounter focused on routine wellness tasks for a shy dog rather than on affordability or care-path negotiation.|nooption
33723|Cocoa|Dog|Car-anxiety and holiday-cat planning visit|1|The veterinarian offered practical behavior branches instead of an all-or-nothing sedation answer.|The discussion used trazodone for car rides, gradual baby-gate introductions for visiting cats, and positive-reinforcement advice for both household dogs.|options,staged,min
33782|Jingles|Dog|Fresh wound visit with puncture-versus-surface branch|1|The veterinarian held the final plan until the hair was clipped and the true wound depth was visible.|The discussion contrasted oral antibiotics for a puncture against topical treatment for a superficial cut and explained the short healing window either way.|options,staged,risk,min
33878|Hannah|Dog|Wellness visit with benign lump monitoring advice|1|The veterinarian kept the visit light while still giving a concrete plan for a low-concern mass.|The discussion recommended photo-based monitoring of a slow-growing chest lump and reassured the owner that the teeth and overall condition looked good.|options,staged,min
33961|Hiro|Dog|Newly adopted dog with behavior and orthopedic questions|1|The veterinarian treated this as an acclimation case with both behavioral and physical unknowns still settling out.|The discussion covered truck and child reactivity, probable minor scar or tick-related lesions, and a possible luxating-patella style hind-limb issue without overreacting early.|options,staged,risk,barrier
34014|Kenai|Dog|Puppy visit with training, feeding, and neuter timing guidance|1|The veterinarian used sequencing guidance rather than just a one-visit checklist.|The discussion focused on the next fear period, keeping the dog lean for future joint health, and delaying neutering until musculoskeletal development was further along.|options,staged,min
34023|Robin|Cat|Obesity-related grooming problems with sanitary-care plan|1|The veterinarian matched the plan to the cat's size and self-grooming limit rather than pretending it was simple hygiene failure.|The discussion used sanitary shaving, dry shampoo, combing before painful mats form, and continued weight loss as the real path to fixing the problem.|options,staged,min,barrier
34038|Teddy|Dog|Tick exposure visit with deferred testing and prevention choice|1|The veterinarian staged the response so testing would happen when it could actually be informative.|The discussion delayed the tick panel until enough time had passed, compared monthly trio against other prevention, and explained why early testing would be falsely reassuring.|options,staged,risk,min
35371|Reagan|Dog|Routine two-dog vaccine visit|1|This was a straightforward preventive visit where alternatives were not really the issue.|The encounter focused on vaccine timing, routine exams, and minor weight feedback rather than on a meaningful spectrum-of-care conversation.|nooption
35432|Elizabeth|Cat|Routine cat wellness and vaccine visit|1|This was a preventive visit where alternatives were not really the issue.|The discussion stayed with annual exam findings, dental reassurance, and small weight adjustments rather than any real treatment-path negotiation.|nooption
35518|Lexie|Dog|Prednisone side-effect visit with stop-and-support plan|1|The veterinarian treated the new lethargy and polyuria as medication fallout rather than new disease.|The discussion stopped the prednisone, added fluids and probiotics, and clearly framed the heavy breathing and stool changes as expected steroid side effects.|options,staged,risk,min
35522|Phoebe|Dog|Fragmentary preventive capture|1|The available text is too broken to support nuanced coding beyond noting it reads like routine care setup.|The source is mostly staff chatter and partial rooming language rather than a usable owner-facing discussion of options or constraints.|nooption
35607|Luca|Dog|Chronic diarrhea case with biome diet over steroids|1|The veterinarian leaned on diet and fecal testing before reaching for stronger anti-inflammatory control.|The discussion framed the pattern as chronic GI disease, recommended a microbiome-focused prescription food, and explicitly kept steroids in reserve because of side effects in a fragile little dog.|options,staged,risk,rep
35852|Winnie|Cat|Young-cat spay planning with retained baby canines|1|The veterinarian used staged timing around the next surgery rather than treating the mouth and spay as unrelated events.|The discussion planned an upcoming spay, explained why the retained canines would likely be removed at the same time, and reviewed how heat behavior could emerge if they waited too long.|options,staged,risk
35887|Casper|Dog|Too-short intake-only ear note|1|This file is too abbreviated to support nuanced option coding.|The available text is limited to rooming context about a possibly dirty ear and never develops into a real owner-facing plan.|nooption
35889|Casper|Dog|Duplicate-like intake-only ear note|1|This duplicate-like file is too abbreviated to support nuanced option coding.|The content remains a rooming summary about possible ear debris without a developed exam-room discussion.|nooption
35890|Casper|Dog|Second duplicate-like intake-only ear note|1|This second duplicate-like file is also too abbreviated to code as a full care-path conversation.|The usable material stays at the intake-summary level and does not preserve the owner-facing treatment discussion.|nooption
35901|Casper|Dog|Ear-debris visit managed with cleaner rather than medication|1|The veterinarian kept the plan narrow once the ears looked more dirty than infected.|The discussion used a deep clean and a yeast-focused ear cleaner for a few days instead of pushing straight to stronger medication.|options,staged,min
36009|Brody|Dog|Wellness visit with lean-body and diet reassurance|1|This was mainly a preventive visit where alternatives were not really the issue.|The encounter focused on body condition, food balance, and routine vaccine timing rather than on a real options discussion.|nooption
36788|Osco|Cat|Vomiting diabetic cat with ketoacidosis risk ruled out first|1|The veterinarian cleared the high-stakes diabetes complication first and then widened back out to more ordinary causes.|The discussion ruled out euglycemic ketoacidosis, compared blood work against supportive care, and tied the flare back to IBD triggers and kitten-food exposure.|options,staged,risk,rep
36982|Lily|Cat|Recurring eye flare treated as stress-linked herpes pattern|1|The veterinarian treated the eye as another predictable flare rather than a brand new problem each time.|The discussion moved through ulcer check, repeat topical and oral treatment, and preventive lysine guidance for future flare-ups.|options,staged,risk
37006|Prince|Dog|Loose-stool case with prostate rule-out before antibiotics|1|The veterinarian resisted reflex antibiotics until the prostatitis question was clearer.|The discussion treated the stool change and rear-limb discomfort as possibly prostate related, examined that pathway first, and explained why the wrong antibiotic could worsen the diarrhea.|options,staged,risk
37032|Stella|Dog|Sensitive small-dog pancreatitis and diarrhea follow-up|1|The veterinarian simplified the plan so the owner was not forced to pile every medication on at once.|The discussion clarified which medications were safe on an empty stomach, kept pain and anti-diarrheal support targeted, and added an appetite stimulant only as a backup if eating still failed.|options,staged,risk
37119|Hiro|Cat|Outdoor rescue-cat intake with vaccine and spay sequencing|1|The veterinarian sequenced the plan around uncertain outdoor future and upcoming spay rather than doing everything immediately.|The discussion covered vaccines, future FeLV vaccination if outdoor life continued, age estimation, and the practical timing of the spay.|options,staged,risk
37155|Johnny|Cat|Annual urinary-cat follow-up with slow-feeder advice|1|This was mainly a maintenance visit with one practical adjustment for a new feeding problem.|The discussion stayed focused on routine blood and urine rechecks and used a slow feeder as the first move before treating regurgitation like a deeper GI disease.|options,staged,min
37256|Arizona|Dog|Hit-by-car triage with imaging-first trauma logic|1|This was a clear emergency-staging conversation rather than a single-path script.|The veterinarian explained the difference between the reassuring initial ultrasound and the still-needed chest and spine imaging to rule out hidden trauma.|options,staged,risk,rep
37309|Abaagail|Cat|Routine cat vaccine visit with future dental timing|1|This was mainly preventive care where alternatives were not really the issue.|The discussion centered on vaccine updates, nail trims, and the fact that one cat was approaching dental timing rather than on a real treatment-path decision.|nooption
37382|Frannie|Dog|Conjunctivitis visit with stain-first eye-drop choice|1|The veterinarian used the stain result to keep the treatment simple and safe.|The discussion ruled out a corneal cut, explained pink-eye style conjunctivitis, and then moved to steroid-containing drops once ulcer risk was off the table.|options,staged,risk
37479|Big baby|Cat|Senior cat wellness with kidney-screening reassurance|1|This was a maintenance visit where alternatives were not really the issue.|The encounter focused on a broad chemistry screen for kidney peace of mind, with the exam otherwise reading as very reassuring routine care.|nooption
37588|Frankie|Dog|Tick-bite visit with delayed panel and prevention choice|1|The veterinarian explained why the right test today was actually no test today.|The discussion delayed the tick-borne screen until the antibodies could show up, reviewed monthly prevention, and kept the local bump in a conservative watch lane.|options,staged,risk
37624|Daisy|Dog|Senior-seizure consultation with medication choice and rescue plan|1|This was a strong example of staged neurologic management with explicit tradeoffs between options.|The veterinarian compared Keppra against phenobarbital, added gabapentin for travel or high-stress periods, and framed the likely brain-tumor versus epilepsy differential plainly.|options,staged,risk,rep
39069|Kris|Dog|Mock diarrhea role-play rather than a real visit|1|This file reads like a training or demonstration script, not an owner-facing transcript.|The content is a short mock exchange about diarrhea management and does not preserve a genuine exam-room conversation to analyze.|nooption
39130|Rigatonk|Dog|Mock allergy dictation note|1|This file reads like a dictated training example rather than a real owner-facing conversation.|The available text is a scripted plan about paw allergies and medications, not a preserved in-room discussion with a client.|nooption
39133|Rigatoni|Dog|Mock flea-note dictation|1|This file reads like a narrated chart note rather than a real exam-room exchange.|The content documents a flea-related plan in dictation form and does not show a client conversation to analyze directly.|nooption
39489|Oliver|Dog|Chronic wound with culture and tie-over-bandage plan|1|The veterinarian did not pretend the wound was ready for closure and instead built a more realistic healing path.|The discussion added culture-guided antibiotic planning, a tie-over bandage, and repeated recheck changes because the tissue was still too infected for simple closure.|options,staged,risk,rep
40102|Kona|Dog|Allergy flare and anxiety visit with training-plus-trazodone plan|1|The veterinarian handled itch and social overreaction as two problems that needed different levels of intervention.|The discussion reloaded Apoquel for the allergy cycle, added wipes and an antibiotic for the vulvar irritation, and paired training advice with as-needed trazodone for the anxiety piece.|options,staged,risk
40242|Bali|Cat|Vomiting and coughing cat with aspiration concern|1|The veterinarian treated aspiration as the dangerous branch that had to be checked before settling for nausea control alone.|The discussion moved to chest x-rays first, explained why vomiting plus coughing changes the stakes, and only then turned back to pills or supportive care if the lungs looked okay.|options,staged,risk,rep
40288|Chloe|Dog|Heart-failure recheck with x-ray comparison and Lasix thresholds|1|This was a strong chronic-cardiology conversation built around trend monitoring rather than guesswork.|The veterinarian compared serial chest films, explained what resting respiratory rate means at home, and kept a third daily Lasix dose as the escalation point if breathing worsened.|options,staged,risk,rep
40310|Oscar|Dog|Intermittent skin-scab visit with topical and diet support|1|The veterinarian kept the plan narrow and preventive rather than turning a minor skin issue into a major workup.|The discussion used topical antibiotic ointment, linked the lesions to rubbing or mild allergy, and suggested a salmon-based food if the skin barrier kept failing.|options,staged,min
40354|Willow|Dog|Routine senior rabies visit with age-change counseling|1|This was mainly a maintenance visit where alternatives were not really the issue.|The encounter focused on rabies vaccination, expected hearing and vision aging, and general reassurance about an old small dog doing well.|nooption
40388|Heidi|Dog|Chronic matted sores with probable infection and open tumors|1|The veterinarian recognized this as more than simple grooming fallout and moved toward true wound care.|The discussion used clipping and inspection first, but the visible concern was infected open masses that likely needed antibiotics and more than cosmetic cleanup.|options,staged,risk,rep
40597|Envy|Dog|Bleeding lump aspirate with antibiotics before surgery|1|The veterinarian used the cytology result to stay conservative while still keeping excision on deck.|The discussion found inflammatory rather than cancerous cells, added a short antibiotic course, and kept surgery only for a lesion that failed to settle or started growing again.|options,staged,min
40616|Jordie|Cat|Routine Bengal wellness with nail-chewing history|1|This was a maintenance visit where alternatives were not really the issue.|The encounter focused on an annual exam, a likely ingrown-style nail issue, and routine record support rather than on a meaningful care-path decision.|nooption
40617|Jordie|Cat|Duplicate-like Bengal wellness follow-up|1|This duplicate-like file still reads as a routine annual exam rather than an options conversation.|The usable material stays with annual wellness and a minor nail issue, not with a developed staged-care decision.|nooption
41404|Sese|Dog|Too-fragmentary preventive puppy capture|1|The available source is too incomplete to support nuanced option coding.|What remains is mostly staff chatter around routine vaccines and prevention rather than a usable owner-facing discussion.|nooption
41473|Bailey, Lucy, Henry|Dog|Multi-dog preventive visit with minimal clinical branching|1|This was mainly a preventive multi-pet visit where alternatives were not really the issue.|The discussion centered on vaccine records, scheduling, and routine wellness findings rather than on a meaningful care-path conversation.|nooption
41714|Gracie|Dog|Wellness visit with seasonal sneezing and mild forelimb concern|1|The veterinarian stayed conservative and practical on both side concerns.|The discussion framed the sneezing as likely seasonal and the front-leg issue as minor enough for watchful care rather than aggressive workup.|options,staged,min
41804|Bonnie|Dog|Post-dental face rubbing traced to lip irritation rather than retained tooth pain|1|The veterinarian narrowed the problem to local lip irritation once the mouth itself looked sound.|The discussion used topical treatment, a little extra pain control, and clearer urine-protein follow-up rather than reopening the whole dental concern.|options,staged,risk
41805|Bonnie|Dog|Duplicate-like post-dental irritation follow-up|1|This duplicate-like file still supports the same narrowed read of the problem.|The veterinarian again localizes the rubbing to lip irritation and uses topical plus short pain support instead of treating it like an unresolved extraction failure.|options,staged,risk
41845|Nate|Dog|Young-dog lameness with elbow-dysplasia workup pathway|1|This was a clear staged orthopedics discussion with a defined conservative window before advanced imaging.|The veterinarian interpreted the gait as bilateral elbow pain, added strict rest plus gabapentin and anti-inflammatories, and set CT referral as the next step if the month of rest failed.|options,staged,risk,rep
41886|Mya|Cat|Facial scab visit with shave-and-antibiotic plan|1|The veterinarian treated the lesion as likely self-trauma or secondary infection and kept the intervention simple.|The discussion paired clipping, inspection, shorter nail trims, and an antibiotic plan rather than jumping to a more invasive workup immediately.|options,staged,min
41900|Juliette|Dog|Dead-tooth recognition with dental scheduled quickly|1|The veterinarian identified one clearly dead tooth and moved quickly instead of pretending the smell would settle on its own.|The discussion tied the bad breath and food aversion to the dead tooth, used anal-gland care as a separate issue, and scheduled another dental without much delay.|options,staged,risk
41906|Leo|Dog|Allergy flare with Apoquel loading and rural-move planning|1|The veterinarian handled the case as a straightforward atopy flare and matched the plan to a family about to relocate.|The discussion used Apoquel loading, checked that the eye discharge still fit allergy, reviewed vaccine timing, and added refills and prevention support before the move.|options,staged,risk
43140|Bruno|Cat|Urine-marking cat with anxiety medication and box-management plan|1|This is a strong behavior-case transcript where the veterinarian treats the marking as anxiety until proven otherwise.|The discussion used Clomicalm over fluoxetine for faster effect, reviewed box count and Feliway support, and prepared the owner for dose adjustment if sleepiness replaced normal personality.|options,staged,barrier,rep
43220|Pqzzo|Dog|Chronic cough framed as tracheal sensitivity rather than pneumonia|1|The veterinarian used simple airway support first and kept stronger treatment only for a worsening course.|The discussion explained why the cough looked like kennel-cough style tracheal sensitivity, added cough tablets and a harness, and asked for a two-week update before escalating.|options,staged,min
43221|Pqzzo|Dog|Duplicate-like cough follow-up with the same tracheal-support plan|1|This duplicate-like file still shows a conservative airway plan rather than a broad infectious workup.|The veterinarian again uses cough tablets, harness advice, and watchful follow-up as the first move for a mild but persistent cough.|options,staged,min
43269|Mia|Dog|Chronic loose stool after parasite treatment with GI Biome reset|1|The veterinarian used a targeted diet reset instead of piling on more overlapping gut medications.|The discussion stopped the extra probiotic, moved straight to GI Biome, and explained why this food could normalize the stool more cleanly than mixing multiple support products.|options,staged,min
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 10',
      date: '2026-03-18',
      selectionSeed: '20260318-wave10',
      selectionMethod: 'Tenth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_900_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
