window.ANDY_ANALYSIS_BATCH13 = (() => {
  const rows = `
88116|Lulu|Dog|End-stage liver failure with euthanasia versus limited diagnostics|1|The veterinarian made clear that aggressive care was unlikely to change the outcome and treated euthanasia as a humane option.|The discussion contrasted brief confirmatory testing with supportive care and kept suffering and prognosis in the foreground.|options,staged,risk,rep
88137|Ginger|Dog|Senior wellness with feeding and weight maintenance guidance|1|This stayed in routine-care territory without opening a real treatment branch.|The visit focused on preventive care and modest nutrition advice rather than on a larger medical decision.|min,nooption
88144|Lucy|Dog|Painful eye visit with stain-first medication branching|1|The veterinarian used the stain result to decide whether this was an ulcer case or a simpler irritation case.|The plan split medication choice by corneal damage and explained why the eye could not be treated blindly.|options,staged,risk,min
88340|Merlin|Dog|Status epilepticus crisis with hospitalization versus euthanasia|1|The veterinarian explained that prolonged seizure activity and hyperthermia made recovery unlikely and that euthanasia was medically reasonable.|Hospital care and stronger seizure control were discussed, but the likely brain injury and poor prognosis drove the final decision.|options,staged,risk,rep
88482|Prada|Dog|Breakthrough seizure visit with Keppra add-on and home versus hospital loading|1|The veterinarian offered both overnight monitoring and a lower-cost loading-dose discharge plan while still escalating seizure control.|The discussion covered GoodRx, a rough estimate, and why bloodwork was lower value than getting the seizure cluster controlled.|options,money,pay,pharmacy,staged,risk,min,rep
88548|Dakota|Dog|PU-PD workup with cheaper send-out screening for Cushings or kidney disease|1|The veterinarian kept the next step narrow and chose the cheaper send-out lab path because the dog was otherwise stable.|Urine ruled out infection and diabetes, so the conversation focused on economical bloodwork before any more specialized testing.|options,money,pay,staged
88586|Finnegan|Dog|Dental consult with pre-op bloodwork now versus the morning of anesthesia|1|The veterinarian gave the owner a real scheduling and cost choice instead of assuming one pathway.|The conversation balanced a cheaper day-of screen against earlier bloodwork that would lock in the dental plan with fewer surprises.|options,money,pay,staged
88618|Ricki grant|Dog|Thyroid callback with dose increase and recheck plan|1|This was a straightforward chronic-care adjustment rather than a broader options encounter.|The veterinarian increased the thyroid dose, explained the target range, and planned one more recheck before settling into yearly monitoring.|staged,nooption
88666|Carlos and Uzi|Cat|Paired cat wellness visit with routine vaccines and mild weight counseling|1|This was preventive care rather than a real cost-of-care decision point.|The discussion stayed on routine vaccines, basic dental monitoring, and modest weight guidance for an otherwise stable pair.|min,nooption
88697|Cosmo|Dog|Severe eye emergency with immediate ophthalmology referral planning|1|The veterinarian treated the bleeding eye as urgent and organized referral options instead of pretending routine care was enough.|The discussion centered on protecting the remaining vision, arranging specialist access, and avoiding delay in a one-eyed dog.|options,risk,rep
88780|Finn|Dog|Routine wellness visit with a benign-appearing lump and vaccines|1|This stayed in routine preventive territory without a meaningful treatment branch.|The visit focused on vaccines, weight monitoring, and reassurance that the lump was not affecting the dog day to day.|nooption
88908|Coco|Dog|Puppy wellness with eye-care advice and microchip timing options|1|The veterinarian kept the visit practical by folding small owner questions into routine care choices.|The discussion covered benign eye discharge management, nail handling, and whether to microchip at the last vaccine visit or at spay.|options,staged,min
89121|Cheddar|Cat|Sick-cat workup for anemia, weight loss, ear disease, and systemic decline|1|The veterinarian laid out several plausible causes but kept the immediate plan on bloodwork and ear diagnostics before promising anything larger.|The discussion walked through kidney disease, thyroid disease, diabetes, infection, and cancer while holding prognosis until the lab picture was clearer.|options,staged,risk,rep
89312|Desecrater|Cat|Routine vaccine visit with urinary-diet continuation and no new illness|1|This was a stable maintenance visit rather than a larger options conversation.|The discussion stayed on routine preventive care and continuing the urinary plan without introducing a new medical branch.|min,nooption
89816|Rigatoni|Dog|Internal surgery-note demo rather than a true owner-care encounter|1|This file read as internal documentation workflow content, not a live spectrum-of-care discussion.|The capture did not contain a meaningful exam-room decision about options, costs, or client constraints.|nooption
89828|Rigatoni|Dog|Internal callback-note demo rather than a true owner-care encounter|1|This file read as a documentation exercise rather than a real medical conversation.|The capture did not surface a live care branch or owner-facing decision around alternatives.|nooption
89836|Rigatoni|Dog|Internal dental-charting demo rather than a true owner-care encounter|1|This file functioned like a charting workflow sample, not a treatment-options conversation.|There was no substantive exam-room choice structure to code beyond the fact that it was not a live care discussion.|nooption
89848|Rigatoni|Dog|Internal wellness-note demo rather than a true owner-care encounter|1|This was another documentation-style sample instead of a real client-care conversation.|It did not provide a live treatment choice or meaningful affordability discussion to code.|nooption
90143|Gracie|Dog|Brief callback with normal results and a blood pressure recheck|1|This was a short result communication rather than a broader options discussion.|The veterinarian simply relayed reassuring results and kept the next step narrow.|staged,nooption
90167|Dakota|Dog|Cushings follow-up with low-dose dex suppression as the next step|1|The veterinarian moved from screening toward a more specific confirmatory test rather than broadening the plan all at once.|The discussion framed endocrine workup stepwise and explained why the next test mattered more than guessing.|options,staged,risk,min
100732|Zuko|Dog|New-patient puppy wellness with routine vaccines and record review|1|This was a standard establish-care visit without a meaningful treatment branch.|The conversation stayed on vaccine timing, record clarification, and routine puppy care.|nooption
100766|Storm|Dog|Chest-lump visit with likely cyst assessment and optional next diagnostics|1|The veterinarian kept the mass workup conservative because the lesion still behaved like a benign superficial process.|The discussion left room for sampling or later intervention while avoiding a more aggressive response up front.|options,staged,risk,min
100803|Oscar|Dog|Wellness visit with mast-cell concern and sampling discussion|1|The veterinarian did not ignore the boxer lump risk, but also did not jump straight to a maximal plan.|The conversation tied breed risk to a measured next step and kept the workup proportional to the finding.|options,staged,risk
100895|Cooper|Dog|Foreign-material recheck with small meals and monitoring rather than a bigger workup|1|The veterinarian kept the plan narrow because the dog was already improving and the stomach looked empty.|The discussion emphasized red flags and incremental feeding instead of layering on unnecessary intervention.|staged,risk,min
100909|Shadow|Dog|Allergy follow-up with Cytopoint restart and local-clinic access instead of dermatologist travel|1|The veterinarian matched allergy control to what the owner could realistically maintain close to home.|The discussion kept the chronic plan simple by offering in-clinic injections and monitoring rather than forcing specialty follow-up every time.|options,staged
100912|Shadow|Dog|Duplicate-like allergy follow-up with Cytopoint restart and local-clinic access|1|This duplicate-like capture preserved the same practical allergy-management reasoning.|The discussion again emphasized in-clinic Cytopoint access and incremental control rather than a more burdensome specialty path.|options,staged
100925|Bailey|Dog|Routine wellness visit with basic vaccines and scripts only|1|This was a preventive-care visit rather than a treatment-options encounter.|The discussion stayed on heartworm testing, vaccine updates, and refill logistics for an otherwise stable dog.|nooption
100952|Pilot|Dog|Post-op swelling visit with longer antibiotics, more anti-inflammatory coverage, and home icing|1|The veterinarian treated the incision as cellulitis and escalated supportive care without overcalling it as a surgical failure.|The plan extended antibiotics, added more anti-inflammatory support, and set clear red flags for worsening tissue color or swelling.|staged,risk,min
100967|Ruby|Dog|Puppy visit with mild ear yeast, grooming guidance, and skin-support add-ons|1|The veterinarian kept the problem small and practical rather than medicalizing a mild early skin issue.|The conversation centered on light ear treatment, home grooming, and nutrition support rather than a more aggressive allergy workup.|staged,min
100991|Bo|Dog|Recurrent neck or back strain with symptom-first treatment instead of immediate MRI|1|The veterinarian treated the pattern like a soft-tissue or spinal pain flare and explained why advanced imaging was not the first move.|The conversation used Rimadyl and gabapentin, restricted activity, and reserved MRI for a dog that stopped functioning more dramatically.|options,staged,risk,rep
100997|Tubby too cute|Cat|Urinary obstruction visit complicated by a newly detected heart murmur|1|The veterinarian treated the obstruction as the immediate threat while being candid about the added anesthesia and fluid risk from the heart.|The discussion covered bloodwork, hospitalization, long-term diet change, and a rough emergency cost range without pretending the case was simple.|options,money,staged,risk,rep
101077|Pickles|Dog|Post-emesis foreign-material visit with anti-nausea care and monitoring|1|The veterinarian treated this like a resolved stomach event unless further vomiting proved otherwise.|The plan emphasized partial meals, supportive care, and clear red flags instead of jumping straight to more diagnostics.|staged,risk,min
101080|Bella|Dog|Nonlethal mushroom ingestion with supportive care and food-transition guidance|1|This was supportive care with monitoring rather than a broader care-spectrum conversation.|The veterinarian focused on anti-nausea treatment, fluids, bland feeding, and yard cleanup because the mushroom risk looked GI-related rather than fatal.|risk,min,nooption
101082|Themj|Cat|Acute soft-stool and lethargy visit with probiotics and appetite support|1|The veterinarian treated this like an upset-stomach flare while keeping re-escalation available if the cat did not bounce back.|The plan used fluids, Fortiflora, and appetite support, with more workup held in reserve if recovery stalled.|staged,risk,min
101086|Fiona|Cat|Lethargic-cat visit with staged diagnostics instead of one fixed explanation|1|The veterinarian kept multiple causes in play and built the plan around whichever first-line answers came back fastest.|The conversation weighed blood pressure, bloodwork, and a near-term recheck path while avoiding a premature diagnosis.|options,staged,risk,rep
101161|Maddie|Dog|Older-dog discomfort visit with trial pain control before expanding the workup|1|The veterinarian used a therapeutic trial first because the presentation still fit a lower-intensity pain picture.|The discussion stayed practical around anti-inflammatory treatment and reassessment instead of immediately building a large diagnostic plan.|staged,min
101289|Pikka|Cat|First-cat wellness visit with mild dental-home-care advice|1|This was a straightforward preventive visit without a meaningful options branch.|The discussion focused on routine vaccination and basic home dental support for a young cat.|min,nooption
101352|Ambry|Cat|New-adoption recheck with collar and skin reassurance|1|The veterinarian kept the visit on simple home-management adjustments because the findings stayed minor.|The conversation focused on basic reassurance and low-intensity care rather than a larger workup.|min,nooption
101409|Yankee|Dog|Routine annual with vaccines and maintenance advice|1|This was standard preventive care rather than a treatment-options encounter.|The conversation stayed on vaccines, routine monitoring, and home maintenance.|nooption
101548|Yajima|Dog|Annual visit with paw-licking spot treated topically|1|The veterinarian treated the sore paw as a small local issue and kept the plan narrow.|The discussion centered on once-daily ointment, keeping the dog from licking it, and routine vaccine care.|min,nooption
101623|Bella|Dog|Diabetic ketoacidosis hospitalization with estimate and guarded optimism|1|The veterinarian framed DKA stabilization as the immediate job and did not hide the time, risk, or cost involved.|The discussion covered slow insulin correction, electrolyte support, a multi-day stay, and the possibility that another problem could still emerge afterward.|options,money,staged,risk,rep
101761|Mazie|Dog|Behavior visit with training, chronic fluoxetine support, and as-needed trazodone|1|The veterinarian treated the problem like a management spectrum rather than a single medication answer.|The discussion combined existing behavior medication with training realities and careful use of added anxiolytics when needed.|options,staged,barrier,rep
101949|Dudley|Dog|Ear-infection visit with home cleaning versus leave-in treatment|1|The veterinarian let the owner choose between more home work and a one-time clinic treatment.|The discussion made the tradeoff explicit and still protected against resistant infection with recheck instructions.|options,staged,min
102028|Oliver|Dog|Ear and lump visit with sampling and monitoring choices|1|The veterinarian kept the plan incremental because the findings still supported a smaller first step.|The discussion left room for more diagnostics while still addressing the ear issue and mass concerns practically.|options,staged,risk,min
102076|Ramses|Dog|Painful posture visit with stifle and heart findings managed conservatively first|1|The veterinarian treated the intermittent pain like kneecap or orthopedic irritation and used short anti-inflammatory therapy before chasing more imaging.|The discussion also surfaced a heart murmur and explained what to watch, but kept the immediate plan focused on the more likely painful problem.|options,staged,risk,min
102150|Recon|Dog|Seizure-control decline with Keppra XR add-on and pharmacy price guidance|1|The veterinarian moved to combination seizure therapy rather than waiting for the pattern to get worse.|The discussion compared simply increasing phenobarbital against adding Keppra, explained the brain-tumor concern in an older dog, and pointed the owner toward GoodRx for the human medication.|options,money,pay,staged,risk,rep
102265|Veeno|Dog|Early arthritis discussion with standby anti-inflammatory support and prevention simplification|1|The veterinarian treated the stiffness as mild enough for practical home management rather than a bigger workup.|The conversation paired joint supplements with as-needed pain relief and simplified flea, tick, and heartworm prevention.|options,staged,min
102287|Luna|Dog|Elevated liver values with ultrasound-first reasoning before supplements|1|The veterinarian refused to guess at the cause of the liver changes and pushed imaging before treatment decisions.|The discussion used abdominal ultrasound as the key fork between finding a structural problem and moving to supportive liver supplementation.|options,staged,risk,rep
102320|Ashoka|Cat|Roundworm visit with deworming now and fecal follow-up later|1|The veterinarian treated the most likely parasite immediately while leaving room to pivot if the fecal showed something less covered by the first drug.|The plan used broad deworming, warned about diarrhea and household hygiene, and kept the recheck anchored to the fecal result.|staged,risk,min,nooption
102336|Ace|Dog|Acute respiratory distress with oxygen, diuretic support, and guarded heart-failure assessment|1|The veterinarian treated stabilization as more important than perfect diagnostics because the dog was too unstable for normal imaging flow.|The discussion centered on oxygen, diuresis, rapid x-rays when safe, and probable hospitalization for first-time heart failure.|options,staged,risk,rep
103722|Adelaide and Eli|Dog and Cat|Paired wellness visit with routine screening and no major branching|1|This was mostly preventive care and mild reassurance across two stable pets.|The discussion stayed on routine testing, vaccines, and everyday management rather than on a larger care-spectrum decision.|nooption
103852|Roxy|Dog|Lameness workup that escalated from torn-ACL concern to likely osteosarcoma|0|The veterinarian started with a common orthopedic theory but shifted hard once the x-rays suggested a malignant bone process.|The discussion ultimately framed amputation versus euthanasia, and the owner left to talk it through before choosing a next step.|options,staged,risk,rep
103881|Coco|Dog|Routine vaccine visit with anal-gland expression added for licking|1|This was standard preventive care with one small comfort intervention, not a larger options encounter.|The conversation stayed on vaccines, heartworm screening, and anal-gland care for a dog that otherwise looked great.|nooption
104037|Mia|Dog|Post-splenectomy GI episode with observation and repeat x-ray versus immediate discharge|1|The veterinarian treated the unusual gas pattern seriously enough to watch, but not seriously enough to jump straight to surgery.|The discussion balanced fluids and anti-nausea care against a short in-hospital recheck to make sure the gas was moving and not twisting.|options,staged,risk,rep
104322|Ziggy|Dog|Chronic itchy-skin flare with stronger topical therapy before more oral escalation|1|The veterinarian stayed topical-first and diet-focused instead of reflexively piling on more systemic medication.|The discussion moved from weaker sprays to medicated topical therapy, food simplification, and possible fish-based diet support.|options,staged,rep
104619|Biggie|Cat|Post-exposure GI upset with deworming, probiotic support, and fecal follow-up|1|The veterinarian treated the new outdoor-cat exposure like the most likely explanation without overselling a more serious infectious disease.|The discussion combined symptomatic care, deworming, fecal testing, and low concern for FeLV or FIV without a fight history.|options,staged,risk,rep
104668|Bambino|Dog|Geriatric mobility decline with pain-management layering and no more forced exercise|1|The veterinarian treated this like advanced musculoskeletal aging and did not pretend there was a restorative option left.|The discussion kept realistic limits on exercise, explained muscle loss, and added another pain-control layer instead of escalating diagnostics aggressively.|options,staged,risk,rep
104724|Yogi|Dog|Routine puppy finish-up with product choice for household parasite prevention|1|The veterinarian kept the medical side routine but still gave the owner a real convenience choice for prevention.|The discussion covered final vaccines, puppy development, and whether the house cat should get a monthly or every-eight-weeks flea product.|options,staged,min
104911|Wolfie|Dog|Progressive weakness and likely cancer with euthanasia chosen over more diagnostics|1|The veterinarian treated the dog as both functionally declining and likely cancer-positive, and did not hide that euthanasia was a reasonable endpoint.|X-rays were mentioned as possible, but the combination of immobility, coughing, and probable lung metastasis made a humane end-of-life plan the practical recommendation.|options,staged,risk,rep
104999|Maya|Dog|Senior wellness with elective wellness panel and Cytopoint added to routine care|1|The veterinarian folded a slightly bigger preventive panel into an otherwise straightforward wellness visit.|The conversation kept everything elective and maintenance-oriented rather than opening a more serious care branch.|options,staged,min
105099|Ernie|Dog|Senior exam with perianal lesion evaluation and ongoing Rimadyl monitoring|1|The veterinarian kept the painful rear-end issue on a local-management track while still checking the safety of chronic pain medication.|The discussion combined anal-gland care, lesion monitoring, bloodwork for long-term NSAID use, and routine preventive updates.|staged,risk,min
105206|Mojo|Dog|Wellness visit with calorie reduction, thyroid check, and prevention simplification|1|The veterinarian treated the weight problem practically and did not overmedicalize it before basic calorie correction and follow-up bloodwork.|The discussion covered cheaper and simpler preventive-med choices, optional Lyme vaccination, and whether to switch to a lower-calorie or weight-management diet.|options,staged,min
105518|Graham|Dog|Pneumonia visit with outpatient support now and hospitalization if still not eating|1|The veterinarian offered a coherent middle path before jumping to inpatient care.|The plan layered an antibiotic injection, appetite stimulation, food experimentation, and a short clock before IV hospitalization became the next step.|options,staged,risk,rep
105779|Graham|Dog|Chronic itch and cough visit with Pimobendan start and stepwise itch control|1|The veterinarian used the worsening murmur as a reason to start heart medication before overt heart failure showed up.|The discussion paired Pimobendan with low-cost antihistamine options and a prescription anti-itch fallback rather than jumping straight to the most intensive approach.|options,staged,risk,rep
105832|Riley|Cat|Painful loose-tooth visit with comfort meds now and dental planning next|1|The veterinarian kept the immediate problem small because the tooth was already close to falling out on its own.|The discussion used gabapentin and wet food for short-term comfort while pushing a future dental to evaluate the rest of the mouth properly.|options,staged,risk,min
105918|Taiga|Cat|Chronic soft-stool visit with probiotic first and diet change only if the fecal is clean|1|The veterinarian kept the plan ordered and conservative rather than changing everything at once.|The discussion prioritized fecal testing and a probiotic, with salmon-based diet change held as the next move only if the first step failed.|options,staged,min
108163|Cubby|Dog|Painful eye visit with stain-based treatment and oral pain control|1|The veterinarian separated corneal injury from conjunctivitis so the medication choice would not make the eye worse.|The discussion used a stain test to guide therapy, kept the cone on until pawing stopped, and emphasized quick follow-up on any worsening.|options,staged,risk,rep
108229|Juneau|Dog|ITP recheck with GI-liner addition rather than a broader change in the whole protocol|1|The veterinarian recognized that the bloodwork was improving but still adjusted the plan around the likely upper GI irritation.|The discussion kept the steroid response in view, added sucralfate, and stretched the next recheck only because the counts were finally moving the right direction.|staged,risk,nooption
108379|Loki|Dog|Head-tremor visit with monitor-versus-MRI framing and cheaper send-out labwork|1|The veterinarian treated idiopathic head tremor syndrome as the leading explanation but still preserved a path to deeper neurologic workup.|The discussion contrasted MRI with careful monitoring and chose cheaper send-out screening because the dog otherwise looked normal between episodes.|options,money,pay,staged,risk,rep
108765|Callie|Dog|Puppy vaginitis visit with antibiotics and routine vaccine completion|1|The veterinarian kept the problem on a simple local-infection track and did not validate the vision concern as a larger neurologic issue.|The discussion used urine results to narrow the cause, treated the vulvar irritation, and folded spay timing into the plan.|risk,min,nooption
108824|Riley|Dog|Chest-mass visit with cyst interpretation and watchful monitoring|1|The veterinarian treated the lump as a likely dermal cyst and explicitly resisted making it a cancer scare without reason.|The discussion used sampling, mobility of the mass, and serial size checking to justify leaving it alone unless it changed.|options,risk,min
108900|Capone|Dog|ITP recheck with medication trimming only after counts normalized|1|The veterinarian protected the improvement by keeping most of the regimen in place and only removing the least necessary piece first.|The conversation celebrated the platelet recovery but still treated the case as fragile enough for another week of close recheck.|staged,risk,nooption
109012|Ivy|Dog|Young-dog urinary-accident callback with reassurance and watchful waiting|1|The veterinarian ruled out UTI and refused to overwork up a very young dog before the pattern proved persistent.|The discussion centered on the normal urine, continued house-training reinforcement, and the low odds of endocrine disease at this age.|risk,nooption
112130|Topaz|Dog|Chronic muzzle dermatitis with topical escalation and calorie correction|1|The veterinarian stayed local and practical rather than jumping straight to systemic therapy or a deep allergy workup.|The plan paired a stronger spray and fish oil with weight-loss math because the dog's skin and joints were both being asked to carry too much.|options,staged,min
112239|Kanet|Dog|Dry-eye follow-up with medication adherence rather than a broader care branch|1|This read as a short chronic-care management touchpoint, not a larger options conversation.|The focus stayed on tacrolimus, lubricant use, and keeping the eye-medication routine consistent.|nooption
112357|Daisy|Dog|CHF and kidney recheck with ongoing balance between Lasix and renal stress|1|The veterinarian framed this as a maintenance-balance problem rather than a new diagnostic mystery.|The discussion stayed on watching drinking, urination, energy, and repeat kidney values while keeping the current heart medications in place.|staged,risk,nooption
112430|Daisy|Dog|Wellness visit with lipoma reassurance and routine chronic monitoring|1|This remained a stable preventive visit without a real options branch.|The conversation centered on chronic-issue monitoring and routine preventive care.|nooption
112764|Oslow|Dog|Morning bile vomiting syndrome with bedtime snack rather than a bigger workup|1|The veterinarian solved the likely mechanism simply before escalating to diagnostics.|The discussion used a small late snack as the first-line fix, with routine screening and supportive guidance wrapped around it.|staged,min,nooption
112796|Lily|Dog|Skin-flare visit with antibiotics, short anti-inflammatory support, and cone management|1|The veterinarian treated the immediate lesion as secondary inflammation or infection rather than as a full allergy reinvention.|The discussion balanced oral meds, cone use, and food-history context while keeping the plan narrow enough to see if the skin could settle first.|staged,risk,rep
112817|Zoe|Dog|UTI visit with short pain control, antibiotics, and supplements before stronger arthritis medication|1|The veterinarian treated the infection and discomfort while still keeping longer-term joint care on the lower-intensity side first.|The discussion used Rimadyl briefly for immediate relief, antibiotics for the UTI, and supplements before considering heavier chronic arthritis therapy.|options,staged,risk,min
112980|Mouse sack|Cat|Vomiting visit with x-rays, anti-nausea care, and constipation management kept separate|1|The veterinarian refused to treat the constipation as the full answer until the vomiting question was safer to leave alone.|The discussion used x-rays, anti-nausea medication, fluids, and possible future MiraLAX while avoiding an enema the owners felt would be too traumatic.|options,staged,risk,rep
113060|Coffee|Dog|Senior grooming-clearance visit with routine bloodwork and no major branch|1|This was a stable senior maintenance visit rather than a care-spectrum decision.|The discussion stayed on cough monitoring, blindness adaptation, vaccine updates, and routine bloodwork.|nooption
114206|Rigatoni|Dog|Internal allergy-demo transcript with conservative itch management|1|This file was a VetSOAP-style demo capture rather than a normal owner encounter, but it still showed a clear conservative-care logic.|The conversation favored withholding a suspected treat trigger and using Apoquel before reflexively adding antibiotics.|options,staged,min
114670|Wednesday|Dog|Puppy recheck with resolved stool issue and minor head-bump monitoring|1|The veterinarian kept the visit small because the main GI concern had already improved.|The conversation centered on routine puppy care and a low-intensity watch on the minor head spot.|min,nooption
114697|Lola|Dog|Wellness visit with Lyme testing layered into routine care because the housemate turned positive|1|The veterinarian added the relevant screening without turning the whole visit into a bigger workup.|The discussion stayed preventive, covering routine labs, Lyme context, and standard vaccine timing.|options,staged,min
114729|Eve|Dog|Routine vaccine update with standard screening and no meaningful branching|1|This was straightforward preventive care without a real treatment-choice conversation.|The discussion stayed on heartworm testing, fecal results, vaccine timing, and a refill script.|nooption
114760|Banks|Dog|Torn-nail visit with nail removal, bandage, and infection prevention|1|The veterinarian treated the injury directly and focused on keeping the exposed quick from getting contaminated.|The discussion covered topical numbing, bandage timing, pain meds, antibiotics, and why a cone worked better than a sock for most dogs.|staged,risk,min
114797|Cookie|Dog|Rescue-dog vaccine catch-up with Lepto add-on and fecal-first diarrhea workup|1|The veterinarian used a preventive-care visit to add a regionally relevant vaccine and defer food-allergy guesses until parasite screening was done.|The discussion contrasted mild extra cost for the Lepto combo with the larger value of broader protection and kept the loose-stool workup fecal-first.|options,money,staged,risk
114804|Cookie|Dog|Duplicate-like vaccine catch-up visit with Lepto and fecal-first diarrhea logic|1|This duplicate-like capture preserved the same preventive and diagnostic reasoning as the paired file.|The discussion again kept the diarrhea workup anchored to a fecal sample before escalating toward food-allergy thinking.|options,money,staged,risk
114908|Otto|Dog|Routine wellness visit with barking behavior note and mild dental-home-care advice|1|This was a preventive visit with small maintenance issues, not a broader treatment-spectrum conversation.|The discussion stayed on vaccines, heartworm screening, and basic home dental care around an otherwise stable dog.|nooption
114957|Zoe|Dog|Urinary-stone obstruction with catheter reduction now and surgery planning next|1|The veterinarian explained that immediate relief and definitive management were different steps and priced the difference openly.|The discussion covered sedation to push the stones back, possible specialist escalation, stone-type differences, and the much lower cost of elective bladder surgery if the urethra could be cleared.|options,money,staged,risk,rep
115033|Aimee|Dog|Dental consult with morning-of bloodwork as the cheaper safe-screen option|1|The veterinarian kept the dental planning pragmatic and used cost-conscious pre-op screening instead of extra work before it was needed.|The discussion focused on tartar removal, likely tooth preservation, and a lower-cost anesthesia check on the day of the dental.|options,money,pay,staged,min
115226|Daisy|Dog|Ear recheck with normal cytology and anal-gland education|1|This was a straightforward improvement visit rather than a new care branch.|The conversation confirmed the ears were clear and used the extra time to explain when anal-gland expression is actually useful.|nooption
115342|Ludi|Dog|Oral-abscess recheck with continued dual antibiotics and dental confirmation next|1|The veterinarian treated the improvement as good evidence that the culture-guided antibiotics were finally the right fit.|The discussion kept the current meds in place and saved the deeper look for the already scheduled dental rather than changing direction again.|staged,risk,nooption
115471|Sosa|Dog|Intermittent hind-limb pain with x-rays ruling out major orthopedic disease and shifting suspicion to nerve pain|1|The veterinarian used imaging to clear the big structural problems and then moved the case toward long-term nerve management.|The discussion supported gabapentin as the better chronic answer, used Rimadyl only around flare days, and kept MRI as the only way to see the suspected source directly.|options,staged,risk,rep
115494|Tango|Dog|Eye-ulcer recheck with continued antibiotic and added ocular gel|1|The veterinarian kept the recheck conservative because the ulcer looked to be healing on the current path.|The discussion focused on continuing the existing eye treatment, adding surface support, and planning one more check rather than widening the plan.|staged,risk,min
115587|Juneau|Dog|ITP recheck with counts improving and one more week before taper decisions|1|The veterinarian stretched the recheck interval only because both red cells and platelets were finally moving the right way.|The discussion kept the case in cautious maintenance mode and did not rush the taper just because the latest result looked better.|staged,risk,nooption
115656|Wilson|Dog|Facial-abscess recheck with dental still planned and optional no-charge endoscope training while anesthetized|1|The veterinarian treated the infection as settling and used the upcoming dental as the real decision point for the tooth root question.|The discussion kept the abscess on its current course, explained why the tooth could still be the source, and offered a no-charge scope opportunity during anesthesia.|options,staged,risk,min
115712|Lunar|Dog|Toe-lesion visit with topical protection, oral meds, and calorie adjustment|1|The veterinarian treated the paw lesion like a healing inflammatory problem and paired it with a practical weight-loss adjustment.|The discussion combined bandaging guidance, antibiotics, pain relief, and lower-calorie feeding rather than turning the lesion into a larger oncologic concern.|options,staged,risk,min
115742|Bruce|Dog|Short incision-recheck visit for a possibly opened surgical site|1|This capture was too short to show a deeper branch, but it clearly functioned as a focused wound check.|The visible discussion centered on inspecting the wet opening and then returning with a plan rather than on a larger options conversation.|nooption
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 13',
      date: '2026-03-19',
      selectionSeed: '20260319-wave13',
      selectionMethod: 'Thirteenth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1200_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
