window.ANDY_ANALYSIS_BATCH9 = (() => {
  const rows = `
13443|Gigi|Dog|Routine vaccine update and anal-gland check|1|This was a preventive visit where alternatives were not really the issue.|The encounter focused on overdue vaccines, food consistency, a minor follicle-like bump, and checking whether the groomer had been right to flag the anal glands.|nooption
13476|Simba|Dog|Severe chronic allergy flare with topical and injection support|1|The veterinarian treated a difficult skin case as a layered long-term problem, not a one-step fix.|The discussion paired local antibiotic mousse, Cytopoint, diet consistency, and realistic expectations for a dog whose skin had stayed severe despite spotty prior management.|options,staged,risk,barrier
13495|Envy|Dog|Tail wart with surgery-versus-management discussion|1|The veterinarian compared monitoring against removal and explained why surgery becomes the cleaner long-term answer.|The discussion framed the tail lesion as likely benign, explained why it keeps reopening, and contrasted anti-itch management with anesthetized removal if the cycle continues.|options,staged,risk
13549|Yoli|Dog|Collapsing-trachea follow-up with medication tradeoffs|1|The veterinarian kept the plan conservative while still explaining why the cough management had to be tailored carefully.|The discussion centered on cough control, harness use, and medication choices while explaining why anti-inflammatory choices were shaped by the dog's other drugs and chronic airway disease.|options,staged,risk,rep
13623|Maeve|Cat|Jaundice workup with hospitalization estimate|1|This was a serious staged-care discussion with explicit estimate framing rather than false reassurance.|The veterinarian outlined likely liver or pancreatic disease, explained the need for inpatient support and diagnostics, and made the likely hospitalization range visible without downplaying risk.|options,money,staged,risk,rep
14165|Marley|Dog|Diarrhea visit with outpatient GI support|1|The veterinarian stayed minimum-responsible and outpatient for a common but uncomfortable GI problem.|The discussion used conservative diet support, GI medication, and monitoring boundaries rather than jumping straight to a heavier workup.|options,staged,min
14209|Winnie|Dog|Episodic wobbliness with monitor-first neurologic discussion|1|This was mainly a risk-framing visit rather than a large options conversation.|The veterinarian talked through possible vestibular, seizure, or intoxication causes, emphasized video capture and blood-pressure context, and kept the family's attention on concerning neurologic signs.|nooption,risk
14221|Goghy|Dog|Diarrhea and stress-colitis follow-up|1|The veterinarian used a practical outpatient GI plan rather than escalating reflexively.|The discussion stayed with bland diet, probiotic support, and monitoring while keeping pancreatitis and worsening GI signs available as the next step if needed.|options,staged,min
14230|Tosai|Cat|Eye lesion visit with drops-versus-injection choice|1|The veterinarian offered a real treatment branch even in a relatively small problem visit.|The discussion compared a local eye-medication path with a longer-acting antibiotic injection and then layered in home-care support.|options,staged
14232|Jack|Dog|Tail and back pain with imaging held in reserve|1|The veterinarian localized the problem first and kept x-rays as the next step rather than the automatic one.|The discussion favored pain control and short-term monitoring while explaining when worsening signs would justify imaging.|options,staged,risk
14234|Tia|Dog|Tail amputation procedure note|1|This file reads like a procedure-focused note rather than a meaningful owner-facing options discussion.|The available text centers on the surgical event itself, not on a developed affordability or spectrum-of-care conversation.|nooption
14305|Goghy|Dog|Severe diarrhea with staged workup and Scratchpay mention|1|This is a strong example of cost-visible staged care rather than withheld options.|The veterinarian compared blood work, x-rays, and outpatient GI support, named the financial burden directly, and surfaced Scratchpay while still explaining why worsening GI disease had to be taken seriously.|options,money,pay,staged,risk,barrier,rep
14371|Goose|Dog|Merged routine wellness capture with unrelated appended content|1|The source is too blended to support a strong options reading beyond noting it was largely preventive.|Most of the usable material is a routine large-dog wellness and vaccine discussion, while later sections appear to drift into another dog's anxiety conversation.|nooption
14400|Quinn and Riley|Dog|Merged GI follow-up and acute limp visit|1|Even as a mixed capture, the file still shows stepwise care rather than all-at-once escalation.|The discussion adds omeprazole to Quinn's chronic GI plan and uses short anti-inflammatory support with x-rays held in reserve for Riley's acute limp.|options,staged
14401|Quinn and Riley|Dog|Duplicate-like merged GI and limp follow-up|1|This duplicate-like capture still reads as staged management rather than aggressive escalation.|The veterinarian adds one medication to the chronic GI regimen, then handles the limp conservatively with medication first and x-rays only if weight-bearing fails.|options,staged
14449|Gizmo|Dog|Routine chronic-care and wellness follow-up|1|This was mainly a maintenance visit where alternatives were not really the issue.|The encounter centered on ongoing medications, preventive care, and routine chronic-disease follow-up rather than a meaningful cost-of-care branch.|nooption
14508|Walker|Dog|Heart-failure recheck with cardiology and monitoring choices|1|The veterinarian managed a chronic cardiac case through staged follow-up rather than a dramatic reset.|The discussion balanced medication monitoring, kidney-value checks, and whether cardiology or echo changes would actually alter what the family was doing at home.|options,staged,risk
15290|Charlie|Cat|Urinary obstruction workup with hospitalization path|1|This was a strong triage conversation that kept both risk and logistics explicit.|The veterinarian distinguished supportive care from catheterization and hospital treatment, explained the danger of obstruction clearly, and made the likely estimate visible while moving toward the safer plan.|options,money,staged,risk,rep
15297|Duncan|Cat|Constipation with enema and MiraLAX outpatient plan|1|The veterinarian used minimum-responsible supportive care for a first-time constipation episode.|The discussion contrasted basic enema-and-fluids support against more chronic constipation pathways and kept heavier medications for future recurrence, not for the first event.|options,staged,min
15319|Yoshi|Dog|Bloody-discharge question with limited workup plan|1|The veterinarian kept the case narrow and conservative once the likely source looked reproductive rather than GI.|The discussion used basic confirmation and monitoring instead of over-escalating a problem that no longer looked like a true GI bleed.|options,staged,risk
15320|Buddy|Dog|Degraded acute-pain transcript|1|The available text does not preserve enough of the medical plan to support nuanced options coding.|The source clearly involves a painful hindlimb or back episode, but the visit quickly degrades into off-topic conversation before the clinical branching is fully captured.|nooption
15321|Miles|Dog|Stick-ingestion and diarrhea visit with x-ray branch|1|The veterinarian compared supportive care and imaging rather than assuming the dog needed a full workup immediately.|The discussion treated the episode as likely GI irritation, kept x-rays available if the obstruction concern rose, and stayed conservative while the dog still looked stable enough for outpatient care.|options,staged,risk,min
15322|Ela Sopel|Dog|Dystocia triage with medical-versus-surgical delivery options|1|This is a high-stakes staged decision rather than an all-or-nothing script.|The veterinarian compared medical induction against surgical delivery, explained fetal stress and time sensitivity, and moved toward the intervention most likely to protect both dam and pups.|options,staged,risk,rep
17276|Jangles|Dog|End-of-life mobility decline and euthanasia discussion|1|This was a quality-of-life conversation more than a branching affordability visit.|The discussion centered on advanced decline, suffering, and whether euthanasia had become the kindest path rather than on a wide spectrum of medical alternatives.|nooption,risk
17277|Pal|Dog|Geriatric episode with blood-pressure-first workup|1|The veterinarian used a narrow first-step medical check rather than a large immediate workup.|The discussion focused on blood pressure, possible gabapentin support, and deferred broader testing to the regular veterinarian because the dog was stable enough to stage the next step.|options,staged,risk,min
17280|Scooby|Dog|Toe injury with wound care and recheck guidance|1|The veterinarian treated a painful foot injury through staged local management.|The discussion kept wound care and follow-up at the center while explaining why toe loss or further intervention could still become relevant if healing stalled.|options,staged,risk
17284|Pixie|Dog|Anal-gland abscess with medical-first treatment|1|The veterinarian chose a minimum-responsible first step instead of jumping directly to more invasive care.|The discussion favored antibiotics, pain control, and stool support first while reserving heavier local intervention if the abscess failed to settle.|options,staged,risk,min
17301|Walnut|Dog|Lethargy and back-pain rule-out visit|1|The veterinarian used staged diagnostics to separate musculoskeletal pain from a more serious abdominal problem.|The discussion moved through x-rays and pain control while explaining why the dog's quieter behavior still had to be checked carefully before defaulting to a back-pain answer.|options,staged,risk
17302|Teddy|Cat|Arterial thromboembolism with euthanasia-versus-escalation framing|1|This was a severe prognosis conversation where real options were still laid out plainly.|The veterinarian explained the clotting emergency, contrasted aggressive intervention with euthanasia, and kept the poor prognosis visible rather than softening the decision.|options,staged,risk,rep
17317|Franklin|Dog|Abdominal-pain versus back-pain visit|1|The veterinarian staged the workup to rule out the dangerous abdominal explanation before treating comfort alone.|The discussion paired diagnostic screening with pain support and made clear why the dog could not simply be assumed to have routine back pain.|options,staged,risk
18152|Doodle|Cat|Routine kitten vaccine and neuter-planning visit|1|This was a straightforward preventive visit where alternatives were not really the issue.|The encounter focused on normal kitten care, vaccine timing, and routine procedure planning without a meaningful affordability branch.|nooption
18153|Doodle|Cat|Duplicate-like kitten preventive visit|1|This reads like a duplicate routine preventive capture rather than a fresh options conversation.|The available material stays within ordinary kitten maintenance and does not show a meaningful alternative-path discussion.|nooption
18162|Lou|Dog|Routine vaccine visit for a nervous dog|1|This was mainly a preventive handling visit where alternatives were not really the issue.|The encounter centered on completing vaccines safely and keeping the nervous dog calm, not on affordability or care-path negotiation.|nooption
18173|Coco B|Cat|Recurrent urinary blockage with catheter and surgery planning|1|This is a strong example of recurrent disease forcing real spectrum-of-care decisions.|The veterinarian discussed hospitalization, catheterization, urinary-diet support, and eventual PU surgery while keeping both relapse risk and quality-of-life implications visible.|options,staged,risk,rep
18248|Ember|Cat|Vomiting and weight-loss case with estimate and escalation path|1|The veterinarian used serious staged care rather than pretending there was one simple answer.|The discussion compared outpatient treatment against hospitalization, serial imaging, and possible surgery, and made the likely financial range visible while emphasizing the risk of obstruction or infiltrative disease.|options,money,staged,risk,rep
18281|Ember|Cat|Ear-infection recheck|1|This was a straightforward follow-up where alternatives were not really the issue.|The encounter focused on whether the ear was healing and whether medication should simply continue rather than opening a new affordability or care-path discussion.|nooption
18291|Digregorio / Lexi and Luna|Dog|Routine household-dog maintenance visit|1|This was a preventive household visit where alternatives were not really the issue.|The conversation stayed around routine vaccine and minor wellness follow-up items rather than a meaningful options discussion.|nooption
18292|Penelope|Dog|Puppy vomiting after likely dietary mishap|1|The veterinarian used a minimum-responsible first step for a puppy that still sounded stable enough for outpatient care.|The discussion contrasted anti-nausea support and watchful waiting against heavier escalation, keeping the family alert to worsening signs without over-treating the first pass.|options,staged,risk,min
19789|Elsa|Dog|Recurrent vomiting with hospitalization-versus-outpatient choice|1|The veterinarian kept a real hospital branch open while still trying to make outpatient care possible.|The discussion compared repeat imaging and inpatient support against home care, explaining why foreign-body or worsening GI disease would push the dog into a different level of treatment.|options,staged,risk,barrier
19930|Buttermilk|Dog|Diarrhea with bland-diet and probiotic support|1|The veterinarian stayed conservative and outpatient for a common GI flare.|The discussion centered on diet, probiotic help, and short-term monitoring rather than a broad immediate workup for a dog that still sounded otherwise stable.|options,staged,min
20613|Ludi|Dog|Neck-pain visit with imaging held for failure|1|The veterinarian used supportive care first while keeping the next step visible.|The discussion paired an anti-inflammatory and gabapentin-style comfort plan with monitoring boundaries that would justify x-rays if the dog stopped improving.|options,staged,risk
20625|Lucky|Dog|Chemical eye irritation with stain-guided treatment|1|The veterinarian used a simple but meaningful treatment branch based on the stain result.|The discussion explained why a steroid-containing route was off the table when stain uptake was present and instead built a safer antibiotic-plus-pain-control plan.|options,staged,risk
20634|Lexie|Dog|Chronic cough with x-ray-first respiratory plan|1|The veterinarian ruled out the more serious respiratory path before treating it like a routine cough.|The discussion framed chest x-rays and likely medication changes around the risk of deeper airway or pulmonary disease rather than assuming this was only kennel cough or irritation.|options,staged,risk
20640|Tito|Cat|Escapee infectious-disease screening with limited first step|1|The veterinarian chose the smallest responsible workup rather than the biggest possible one.|The discussion kept more extensive blood work and imaging available but started with targeted infectious screening because the cat otherwise looked good and the immediate concern was disease transmission risk.|options,staged,min
20644|Peanut|Dog|Intermittent hindlimb limp with rest-first plan|1|The veterinarian stayed minimum-responsible while keeping x-rays as the next step if the limp persisted.|The discussion used rest and pain control first rather than forcing immediate imaging in a dog whose signs still fit a soft-tissue injury.|options,staged,min
20861|Luna|Cat|Bladder-mass case with referral and surgery estimate|1|This is a strong example of a serious referral discussion with visible financial reality.|The veterinarian explained why the bladder findings likely represented a mass, outlined anti-inflammatory support versus specialty surgery, and named the likely cost range without pretending the prognosis was simple.|options,money,staged,risk,barrier,rep
20862|Nala|Dog|Ear infection with cytology and topical treatment|1|The veterinarian used a straightforward staged ear plan rather than guessing at treatment blindly.|The discussion paired cytology, cleaning, and targeted medication choice around the actual material in the ear.|options,staged
20863|Kyrie|Cat|Intestinal surgery procedure note|1|This file reads like a procedure note rather than a meaningful exam-room care-path discussion.|The content documents surgery itself, not a developed owner-facing conversation about options, affordability, or staged care.|nooption
20865|Taco|Cat|Fever and likely infection with blood-work-first approach|1|The veterinarian used staged medical reasoning instead of jumping to a broader speculative workup.|The discussion started with blood work, fluids, and likely infectious-disease treatment while keeping the bigger differential in view if the cat failed to respond.|options,staged,risk
20866|Violet|Dog|Hit-by-car triage with chest x-ray before pain meds|1|The veterinarian insisted on the key safety check before relaxing into outpatient pain control.|The discussion used chest imaging first to rule out life-threatening thoracic injury and then built the rest of the treatment plan once the bigger danger looked lower.|options,staged,risk,rep
20962|Champa|Cat|Torn nail visit with sedation and x-ray branching|1|The veterinarian matched the next step to how much pain and structural concern the foot still carried.|The discussion compared simple local care against a more complete sedated exam and imaging path if the claw injury appeared deeper than it first looked.|options,staged,risk
20970|Odin|Cat|Stress-cystitis visit with pain and anxiety support|1|The veterinarian used a practical minimum-responsible plan for a cat whose bladder signs still fit a stress pattern.|The discussion stayed with supportive urinary care, pain control, and anxiety-aware management rather than over-expanding the workup on the first pass.|options,staged,min,barrier
21470|Nyla|Dog|Vomiting history with bloodwork and pancreatic-lipase staging|1|The veterinarian used a serious but stepwise GI workup rather than treating the dog as either trivial or catastrophic.|The discussion paired blood work and pancreatic screening with fluids and anti-nausea support while keeping foreign-body and pancreatitis concerns visible.|options,staged,risk
21557|Oscar, Milo, Felix|Cat|Routine multi-cat annual visit|1|This was a straightforward preventive visit where alternatives were not really the issue.|The encounter focused on vaccines, routine exams, and minor chronic-maintenance questions for multiple cats rather than on a real options conversation.|nooption
21582|Fredo|Dog|Routine annual preventive visit|1|This was mainly a maintenance visit where alternatives were not really the issue.|The encounter centered on vaccines, screening, and calorie guidance without a meaningful affordability or care-path branch.|nooption
21704|Maru|Cat|Ear-hematoma and ear-infection recheck|1|The veterinarian adjusted treatment rather than resetting the whole case.|The discussion centered on whether the ear should simply continue medical care or needed another procedure, while keeping medication changes practical for home management.|options,staged
21723|Griffin|Cat|Rescue-kitten visit with URI and parasite support|1|The veterinarian kept the plan conservative and practical for a newly transitioned kitten.|The discussion stayed with local care, lysine-style support, ear cleaning, and basic parasite follow-up rather than a bigger immediate workup.|options,staged,min
21965|Lizzy|Dog|Multiple lump aspirates with mast-cell concern|1|This was a strong mass-sampling visit that still preserved the difference between benign and concerning findings.|The veterinarian aspirated several lesions, distinguished likely cystic and fatty changes from more worrisome cells, and clearly flagged the elbow lesion as the one most likely to need surgery.|options,staged,risk,rep
22001|PJ|Cat|Asthma follow-up with murmur and echo-monitoring branch|1|The veterinarian layered new findings into a chronic case without overreacting to them.|The discussion balanced ongoing respiratory management against the significance of the new murmur and used monitoring and future echo referral as staged next steps.|options,staged,risk
22049|Iggy Mae|Dog|Inguinal mass with monitoring-versus-surgery framing|1|The veterinarian used a benign-neglect branch once imaging lowered the concern for a true emergency.|The discussion compared imaging paths, explained why the mass looked more like a lipoma than a hernia, and left surgery as a choice rather than a mandate.|options,staged,min
22151|Tyson|Dog|Puppy establish-care visit with lepto and neuter timing|1|Routine puppy care still involved practical sequencing rather than a one-shot plan.|The discussion added lepto for the new region, reviewed retained baby teeth and neuter timing, and used treats and cheese to make the nervous puppy's preventive care workable.|options,staged
22313|Yoli|Dog|Fragmented collapsing-trachea follow-up with staged support|1|Even with partial source quality, the usable material still reflects conservative staged care.|The transcript mixes cough-management material with later appended content, but the visible veterinary reasoning still centers on stepwise support rather than aggressive escalation for a chronic trachea case.|options,staged,risk
22369|Mackenzie|Cat|Open-mouth breathing from likely dental and sinus disease|1|This is a strong example of a veterinarian finding the painful driver and moving quickly but still stepwise.|The discussion linked the respiratory-looking signs to severely infected teeth, used a Convenia bridge, and pushed toward urgent dental extraction while keeping the risk of open-mouth breathing in view.|options,staged,risk,rep
23669|Frankie|Dog|Routine heartworm and prevention refill visit|1|This was a routine preventive visit where alternatives were not really the issue.|The encounter focused on heartworm screening, refills, and a smooth handling plan for a nervous dog rather than on a meaningful care-path branch.|nooption
23716|Sophie|Dog|Heart-failure flare with hospital-versus-home diuretic plan|1|This is a clear staged-cardiology conversation rather than an all-or-nothing message.|The veterinarian compared hospitalization and CRI-style diuresis against increased home Lasix, explained the kidney-heart balancing act, and kept prognosis and quality-of-life framing visible.|options,staged,risk,rep
23777|Mya|Cat|Senior wellness visit with thyroid screening and B12 follow-up|1|This was a chronic-screening visit that still used staged next steps rather than a scattershot workup.|The discussion tied weight loss and appetite change to thyroid testing while maintaining the existing B12 support plan and routine blood-work follow-up.|options,staged
23804|Newt|Dog|Behavior visit with fluoxetine and baseline lab plan|1|The veterinarian treated the aggression case as a staged medication-and-monitoring problem.|The discussion reviewed fluoxetine timing, contrasted it against the trazodone experience, and used blood work only as the appropriate safety screen before staying the course.|options,staged,risk
23857|Sierra|Dog|Ear infection and vaccine update visit|1|The veterinarian handled a routine ear problem with simple local care rather than a larger workup.|The discussion paired cytology-confirmed ear treatment with cleaning, home instruction, and routine vaccine maintenance.|options,staged
23896|Curly|Dog|Pancreatitis and gastroenteritis with supportive outpatient care|1|The veterinarian used symptom control and fluids first while keeping more serious abdominal causes visible.|The discussion explained why pancreatitis and gastroenteritis fit the presentation, added anti-nausea and pain control, and kept escalation thresholds clear if the dog stopped improving.|options,staged,risk
23939|Pepper|Dog|Acute limp with anti-inflammatory and local foot care|1|The veterinarian used a minimum-responsible orthopedic first step once the pain localized to a small area.|The discussion found one irritated spot, shaved the matted hair, gave pain control, and reserved x-rays for a case that later stopped behaving like a soft-tissue irritation.|options,staged,min
23965|Papito|Dog|Ear-scratch visit with cytology-guided treatment|1|The veterinarian used a focused ear workup instead of guessing at the cause of the behavior.|The discussion linked the head shaking to likely ear irritation, checked for infection or parasites, and built the home plan around what the ear sample showed.|options,staged
23978|Max|Dog|Hemoabdomen discussion with surgery-versus-euthanasia decision|1|This is one of the clearest transcripts of serious risk explanation in the room.|The veterinarian explained splenic bleeding, emergency surgery, likely hemangiosarcoma, and the poor expected outcome plainly enough for euthanasia to become the most defensible option.|options,staged,risk,rep
24023|Willow and Sophie|Dog|Routine Rimadyl monitoring and wellness follow-up|1|This was mainly a chronic-maintenance visit where alternatives were not really the issue.|The encounter focused on blood-work monitoring for long-term anti-inflammatory use and routine preventive questions rather than on a meaningful affordability or spectrum-of-care branch.|nooption
24060|Ivy|Dog|Dark-stool concern with fecal-first conservative plan|1|The veterinarian used a narrow check first rather than reacting to a low-signal concern with a big workup.|The discussion emphasized fecal screening and stool monitoring, explaining what truly black tarry stool would mean while keeping the current findings in a lower-risk outpatient lane.|options,staged,min
24262|Lincoln|Dog|Inappropriate urination with urine-versus-behavior framing|1|The veterinarian explicitly separated possible medical disease from pure behavior rather than assuming one or the other.|The discussion compared urine sampling methods, explained why a urinary problem still had to be ruled out, and only then pointed back toward household-behavior management.|options,staged,risk
24280|Layla|Dog|Routine vaccines with allergy support and trazodone-cost discussion|1|This was a routine visit, but it still included practical medication and pricing branches.|The discussion moved through topical scab care, as-needed Apoquel use, and a trazodone refill where the veterinarian explicitly explained that a larger quantity would be more cost-efficient long term.|options,money,pay,staged
24316|Stella|Dog|Tail cyst with oral-versus-injectable antibiotic discussion|1|This is a clean example of route and cost shaping the final plan without changing the medical goal.|The veterinarian explained why the long-acting antibiotic shot would be much pricier in a large dog, recommended oral medication first, and left the shot available if home dosing failed.|options,money,staged,min
24342|Herman|Dog|Chronic diarrhea with blood work and outpatient support|1|The veterinarian used staged diagnostics while still trying to improve the stool right away.|The discussion paired blood work with antibiotic, fiber paste, and bland diet support, and explicitly named the lab cost before moving ahead.|options,money,staged,risk
24368|Hurricane|Cat|Senior cat exam with optional timing for rabies update|1|This was largely a routine wellness visit where alternatives were not really the issue.|The main branch was whether to do the rabies update now or wait until February, but the rest of the visit stayed within normal senior preventive care.|nooption
24416|Bear|Dog|Puppy vaccines with cryptorchid surgery timing|1|The veterinarian used staged planning for a puppy likely needing abdominal neuter surgery later.|The discussion covered vaccine timing, stool follow-up, and why retained testicles change the future surgery plan even though nothing urgent had to happen that day.|options,staged,risk
24570|Rascal|Dog|Senior wellness and travel-vaccine visit|1|This was a straightforward preventive visit where alternatives were not really the issue.|The encounter focused on vaccine updates, ProHeart, heartworm screening, and travel paperwork for a senior dog already stable on his chronic heart medication.|nooption
24615|Bonnie|Dog|Abused rescue with mouth pain and recurrent neck bump|1|This was a handling-limited case where the veterinarian still tried to preserve a staged medical plan.|The discussion balanced oral pain, a recurrent draining bump, anesthesia planning, and the reality that the dog's abuse history and trazodone paradoxical reaction sharply constrain what can be done awake.|options,staged,risk,barrier
25494|Missy|Dog|Vomiting with x-rays plus supportive care|1|The veterinarian offered both the safe diagnostic path and the symptom-control path instead of forcing one route.|The discussion compared immediate abdominal x-rays against supportive fluids and anti-nausea care, then layered both together once the owner chose the more cautious approach.|options,staged,risk
26004|Jessie|Dog|Old-dog vestibular disease workup with blood-pressure branch|1|The veterinarian used staged neurologic reasoning rather than calling the episode a stroke by default.|The discussion explained vestibular disease, checked for high blood pressure as the key branch that might change the interpretation, and paired the plan with anti-nausea and calming support.|options,staged,risk
26015|Bane|Dog|Hematuria workup with ultrasound and urine testing|1|The veterinarian started with the most useful urinary diagnostics instead of speculating about stones or age alone.|The discussion used bladder ultrasound and urine testing to separate infection, sludge, stones, and tumor possibilities before any treatment path was chosen.|options,staged,risk
26016|Bane|Dog|Duplicate hematuria workup capture|1|This duplicate-like file still reflects staged urinary reasoning rather than reflex treatment.|The visible plan again centers on bladder ultrasound and urine testing to sort infection from stones, sludge, or tumor before committing to therapy.|options,staged,risk
26120|Lola|Dog|Routine senior vaccines with wellness blood-work add-on|1|This was mainly a preventive visit where alternatives were not really the issue.|The encounter centered on overdue vaccines, mild intermittent vomiting, and sending senior blood work rather than on a larger affordability or spectrum-of-care discussion.|nooption
26164|Bruiser|Dog|Ear itch plus lump aspirate and Cytopoint plan|1|The veterinarian used multiple small diagnostic and treatment branches in one visit without overcomplicating them.|The discussion checked whether the ear issue was true infection versus allergy debris, aspirated the flank lump because of boxer risk, and layered Cytopoint into the itch plan.|options,staged,risk
26242|Maui|Dog|Increased drinking with blood-work-versus-urine choice and price|1|This was a clean example of small but real cost-visible diagnostic staging.|The veterinarian compared urine and blood work, explained that the price difference was modest but the information gap was meaningful, and then moved to the larger panel as the better value for the concern at hand.|options,money,staged
26264|Amber|Dog|Travel anxiety with trazodone-versus-daily-Prozac discussion|1|The veterinarian matched the medication choice to the fact pattern instead of defaulting to a lifelong behavior drug.|The discussion contrasted situational trazodone with daily fluoxetine, explained why the intermittent travel stress favored the shorter-acting route, and then layered routine vaccines around that plan.|options,staged
26379|Zoe|Cat|Chronic vomiting with probiotic-first sensitive-stomach plan|1|The veterinarian stayed conservative and minimum-responsible while still explaining the next rung up the ladder.|The discussion emphasized food consistency, FortiFlora, slow-feeding, and stool testing first while reserving steroid treatment only for a cat that failed the simpler chronic-GI plan.|options,staged,min
26380|Zoe|Cat|Duplicate-like chronic vomiting and probiotic plan|1|This duplicate-like file still shows a minimum-responsible chronic-GI approach.|The discussion again centers on keeping the food consistent, adding probiotic support, and holding stronger chronic-vomiting medication in reserve unless the simple plan fails.|options,staged,min
26405|Max|Dog|Eye infection with stain-guided stronger drop choice|1|The veterinarian used the stain result to decide whether a steroid-containing eye medication was safe.|The discussion linked swelling and discharge to likely bilateral eye irritation, explained why staining mattered, and then moved toward the stronger drop only if the cornea looked clear.|options,staged,risk
26880|Axel|Dog|Early ear infection with cleaning and pump medication|1|The veterinarian caught the problem early and used a straightforward local treatment path.|The discussion compared mild debris in one ear against clear early infection in the other and used cleaning plus pump medication rather than broader escalation.|options,staged
26906|Rigatoni|Dog|Diarrhea visit with medication-first outpatient plan|1|The veterinarian used a minimum-responsible GI plan and held imaging for failure to improve.|The discussion paired metronidazole, probiotic support, and a short recheck window rather than moving immediately to x-rays or a larger workup while the dog still sounded stable.|options,staged,min
26907|Rigatonk|Dog|Too-short fragmentary transcript|1|The available text is too incomplete to support a real option analysis.|The file contains only a stub line and does not preserve a meaningful exam-room conversation to code.|nooption
26908|Rigatonk|Dog|Too-short fragmentary transcript|1|The available text is too incomplete to support a real option analysis.|This file is another stub capture without enough clinical content to code as an actual care-path conversation.|nooption
26909|Rigatonk|Dog|Too-short fragmentary transcript|1|The available text is too incomplete to support a real option analysis.|This file again reads like a failed capture rather than a usable conversation about options, costs, or staged care.|nooption
26910|Rigatoni|Dog|Boarding-related diarrhea with bland-diet outpatient plan|1|The veterinarian kept the plan conservative while leaving a bigger workup available if the dog failed to settle down.|The discussion used bland diet, probiotic paste, and metronidazole first, with x-rays and blood work moved to the follow-up tier rather than the opening move.|options,staged,min
27121|Roxy|Dog|Parvo hospitalization with home-protocol discussion|1|This is a strong transcript of serious disease management under real practical strain.|The veterinarian compared continued hospitalization against an outpatient home protocol, explained the role of pain control, fluids, anti-nausea support, antibiotics, and probiotics, and stayed candid about how poor the dog's odds still were.|options,staged,risk,barrier,rep
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 9',
      date: '2026-03-18',
      selectionSeed: '20260318-wave9',
      selectionMethod: 'Ninth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_800_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
