window.ANDY_ANALYSIS_BATCH2 = {
  meta: {
    title: "Andy Hand-Coded Batch 2",
    date: "2026-03-18",
    selectionSeed: "20260318",
    selectionMethod: "Second non-overlapping 50-transcript hand-coded batch from the Transcripts folder using a reproducible seeded sample.",
    memoPath: "Andy_100_Transcript_Analysis.md",
    ids: [
      "458","880","1005","1982","2708","4517","4667","5436","7517","9301",
      "26037","27526","32120","32586","57177","75979","80607","100882","120931","143661",
      "194462","198453","201511","202195","216650","221526","279093","307684","312320","343446",
      "372631","379165","385130","389311","407989","453574","468892","509384","529996","533267",
      "548624","560599","567506","569836","620984","637192","665683","667613","739999","805770"
    ]
  },
  transcripts: [
    {
      id: "458",
      pet: "Poppy",
      species: "Dog",
      visit: "New puppy wellness / spay timing / vaccine consult",
      firstRecommendationAccepted: true,
      takeaway: "A routine puppy visit with prevention and developmental guidance, not a cost-sensitive negotiation.",
      notes: "The visit focused on spay timing, feeding amount, hips, eyes, and vaccine planning for a giant-breed puppy. The veterinarian offered routine guidance and reassurance, but affordability did not shape the plan.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/458-transcript.txt"
    },
    {
      id: "880",
      pet: "Pip",
      species: "Dog",
      visit: "Annual vaccines / weight check",
      firstRecommendationAccepted: true,
      takeaway: "This was a straightforward vaccine visit where options were not really the issue.",
      notes: "The veterinarian confirmed ideal body condition, gave routine annual vaccines, and reviewed vaccine reactions. The only explicit money language was that some vaccines were free.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/880-transcript.txt"
    },
    {
      id: "1005",
      pet: "Wyla",
      species: "Cat",
      visit: "Chronic vomiting / weight loss",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian laid out a staged GI workup and empiric treatment path rather than pushing straight to invasive diagnostics.",
      notes: "The veterinarian explained IBD versus GI lymphoma, contrasted intestinal biopsy with an empirical steroid-and-diet approach, suggested senior blood work, and offered wet-food alternatives. It is a strong example of contextualized, staged care without explicit money talk.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/1005-transcript.txt"
    },
    {
      id: "1982",
      pet: "Rome",
      species: "Dog",
      visit: "Annual rabies / heartworm test",
      firstRecommendationAccepted: true,
      takeaway: "A routine preventive visit where affordability and alternatives were not meaningful issues.",
      notes: "The visit covered rabies vaccination, heartworm testing, and routine wellness discussion. There was no real decline conversation and no meaningful lower-cost branching.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/1982-transcript.txt"
    },
    {
      id: "2708",
      pet: "Two Paws / Black Fox",
      species: "Dog",
      visit: "Vaccine update for relocated rescue dogs",
      firstRecommendationAccepted: true,
      takeaway: "This was mainly a straightforward vaccine catch-up visit, not a cost-of-care negotiation.",
      notes: "The veterinarian updated routine vaccines and checked one dog’s oral bump. There was no real budget discussion and no meaningful branching beyond standard preventive care.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/2708-transcript.txt"
    },
    {
      id: "4517",
      pet: "Teddy",
      species: "Dog",
      visit: "Limping forelimb / lump concern",
      firstRecommendationAccepted: true,
      takeaway: "This is a clear cost-and-choice case: in-house versus send-out blood work, immediate x-rays, and outpatient pain control.",
      notes: "The veterinarian localized the pain to the wrist, offered x-rays, separated blood work from the lameness concern, and explicitly contrasted in-house versus send-out lab work with an approximately $40 difference. Travel plans and home-medication logistics shaped the final plan.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: true,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/4517-transcript.txt"
    },
    {
      id: "4667",
      pet: "George",
      species: "Cat",
      visit: "Male cat urinary signs / suspected FLUTD",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian framed urinary workup and treatment as a stress-linked, medically reasoned spectrum rather than a one-shot answer.",
      notes: "The veterinarian explained why male cats often have FLUTD rather than a simple UTI, linked the problem to stress, and paired diagnostics with gabapentin and Dasuquin. It is a good example of options and contextual explanation without overt price talk.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/4667-transcript.txt"
    },
    {
      id: "5436",
      pet: "Ace",
      species: "Dog",
      visit: "Chronic ruptured tail cyst follow-up",
      firstRecommendationAccepted: true,
      takeaway: "The transcript is mostly handoff and treatment-note material rather than a clean exam-room conversation.",
      notes: "The available text is fragmentary and centers on chronic cyst management, culture, and antibiotic changes. It did not read like a meaningful affordability or alternative-offering encounter.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/5436-transcript.txt"
    },
    {
      id: "7517",
      pet: "Odie",
      species: "Dog",
      visit: "Gastrotomy / enterotomy surgical dictation",
      firstRecommendationAccepted: true,
      takeaway: "This transcript is a surgical dictation, not an owner-facing care-options conversation.",
      notes: "The text is essentially an operative note describing gastrotomy and enterotomy for foreign material. It is not useful as a cost-of-care conversation sample beyond showing no option discussion was present.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/7517-transcript.txt"
    },
    {
      id: "9301",
      pet: "Kiet and Sakda",
      species: "Cat",
      visit: "Annual vaccines / mild itching and sneezing",
      firstRecommendationAccepted: true,
      takeaway: "A routine feline vaccine visit with no real affordability tension.",
      notes: "The visit focused on exams, vaccine updates, and a small amount of ear and food discussion. There was no meaningful budget or treatment-choice negotiation.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/9301-transcript.txt"
    },
    {
      id: "26037",
      pet: "Cheeto and Hamilton",
      species: "Cat",
      visit: "Annual cat vaccines / dental and weight guidance",
      firstRecommendationAccepted: true,
      takeaway: "A largely routine visit where options were secondary to preventive care and basic counseling.",
      notes: "The veterinarian recommended a dental cleaning for one cat, reviewed calorie counting, and completed routine vaccine care. Affordability did not drive the interaction.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/26037-transcript.txt"
    },
    {
      id: "27526",
      pet: "Marty",
      species: "Dog",
      visit: "Ear irritation / wellness vaccines / blood panel",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian used a moderate, practical approach, including skipping a dental this year rather than pushing one.",
      notes: "The visit covered mild ear issues, vaccine updates, blood work, and a dental check. The veterinarian explicitly said this was a reasonable year to skip a dental, which reads as minimum-responsible framing more than aggressive upselling.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/27526-transcript.txt"
    },
    {
      id: "32120",
      pet: "Perry",
      species: "Dog",
      visit: "Puppy booster / boarding and potty-training follow-up",
      firstRecommendationAccepted: true,
      takeaway: "A routine vaccine follow-up rather than a meaningful affordability case.",
      notes: "The transcript is noisy and includes clinic chatter, but the owner-facing section is mainly a vaccine update and puppy wellness check. There was no meaningful cost or decline discussion.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/32120-transcript.txt"
    },
    {
      id: "32586",
      pet: "Shadow",
      species: "Cat",
      visit: "Rabies-only visit / grooming mats / litter box issues",
      firstRecommendationAccepted: true,
      takeaway: "This is a strong contextualized-care case: the owner declines broader work due to cost, and the vet shifts to a lower-intensity grooming and litter-box plan.",
      notes: "The handoff explicitly noted that the owner declined everything except rabies because of cost. The veterinarian then built a practical plan around gabapentin before grooming, a second litter box, Feliway, and anesthesia only if needed.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/32586-transcript.txt"
    },
    {
      id: "57177",
      pet: "Bubbles",
      species: "Dog",
      visit: "Puppy first visit / vaccine series / neuter timing",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian gave a nuanced explanation of vaccine staging and neuter timing rather than defaulting to a single generic recommendation.",
      notes: "The visit covered a split vaccine series, small-dog spay and neuter timing, harness use for tracheal health, and breeder-related parasite risk. It is a good explanation-heavy visit without explicit money language.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/57177-transcript.txt"
    },
    {
      id: "75979",
      pet: "Jake",
      species: "Dog",
      visit: "Benign cyst follow-up / kennel cough vaccine",
      firstRecommendationAccepted: true,
      takeaway: "The vet recommended watchful waiting for a benign lesion and deferred removal unless the dog was anesthetized for another reason.",
      notes: "The veterinarian described the cyst as benign, suggested topical care if irritated, and said it could be removed only if the dog were already under for a dental. The conversation was conservative rather than intervention-heavy.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/75979-transcript.txt"
    },
    {
      id: "80607",
      pet: "Toby",
      species: "Dog",
      visit: "Sedated vaccine visit / nail trim attempt",
      firstRecommendationAccepted: true,
      takeaway: "A routine sedation-assisted preventive visit with no real affordability question.",
      notes: "The team managed a sedated but still anxious patient for rabies and distemper vaccination. The visit did not involve a meaningful treatment tradeoff conversation.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/80607-transcript.txt"
    },
    {
      id: "100882",
      pet: "Addison",
      species: "Dog",
      visit: "Adoption meet-and-greet / preventive planning",
      firstRecommendationAccepted: true,
      takeaway: "This was an adoption intake conversation, not a meaningful affordability or decline encounter.",
      notes: "The discussion centered on acclimation, preventives, microchip confirmation, and new-dog naming. There was no substantive cost-of-care negotiation.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/100882-transcript.txt"
    },
    {
      id: "120931",
      pet: "Sweetie",
      species: "Dog",
      visit: "Cardiac recheck / medication refill",
      firstRecommendationAccepted: true,
      takeaway: "A routine cardiology recheck with stable disease and refill planning, not an affordability conversation.",
      notes: "The veterinarian reviewed improved kidney values, stable chest findings, sildenafil use for pulmonary hypertension, and a six-month recheck interval. It was a straightforward chronic-disease follow-up.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/120931-transcript.txt"
    },
    {
      id: "143661",
      pet: "Henry",
      species: "Dog",
      visit: "Dog bite wound follow-up",
      firstRecommendationAccepted: true,
      takeaway: "This was acute wound management, not a lower-cost alternatives conversation.",
      notes: "The veterinarian identified superficial wounds, one small puncture, and a plan for pain control, antibiotics, observation, and possible cone or shirt protection. There was no meaningful budget negotiation.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/143661-transcript.txt"
    },
    {
      id: "194462",
      pet: "Noodle",
      species: "Dog",
      visit: "Hematuria / suspected UTI",
      firstRecommendationAccepted: true,
      takeaway: "A straightforward hematuria workup and treatment discussion without real affordability tradeoffs.",
      notes: "The veterinarian described urine collection, bladder imaging, and likely UTI treatment. The transcript ends with a urinalysis summary and a routine recheck plan.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/194462-transcript.txt"
    },
    {
      id: "198453",
      pet: "Quinn",
      species: "Dog",
      visit: "Chronic GI follow-up / eye allergies / nutrition consult",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian balanced allergy treatment, GI history, and nutrition-referral options without turning the visit into a price discussion.",
      notes: "The visit covered Zyrtec for mild eye allergy, several veterinary nutritionist referral options, and chronic GI management strategy. It is a consult-heavy case with meaningful options but no overt cost framing.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/198453-transcript.txt"
    },
    {
      id: "201511",
      pet: "Eris",
      species: "Cat",
      visit: "Annual cat vaccines / dry skin",
      firstRecommendationAccepted: true,
      takeaway: "A routine wellness visit where the main recommendation was a simple fish-oil supplement.",
      notes: "The veterinarian updated vaccines, reviewed ideal weight, and suggested fish oil for mild dry skin. The visit did not involve meaningful treatment tradeoffs or cost discussion.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/201511-transcript.txt"
    },
    {
      id: "202195",
      pet: "Fox",
      species: "Dog",
      visit: "Morning ultrasound update call",
      firstRecommendationAccepted: true,
      takeaway: "A brief status-update phone call rather than a true care-options conversation.",
      notes: "The veterinarian gave a progress update while waiting on ultrasound interpretation and reassured the owner that the dog was stable on anti-nausea care. There was no real choice architecture in the call.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/202195-transcript.txt"
    },
    {
      id: "216650",
      pet: "Michael",
      species: "Cat",
      visit: "Chronic vomiting / dental and eye concerns",
      firstRecommendationAccepted: true,
      takeaway: "This is a useful mixed case: diagnostics, diet steps, dental counseling, and explicit talk about price matching and online pharmacy options.",
      notes: "The veterinarian framed blood work as a reasonable baseline, moved from sensitive-stomach OTC food to possible hydrolyzed diet, discussed dental cleaning safety, and offered a lower-cost pharmacy path through the clinic website with Chewy price matching. It is one of the clearer logistics-and-cost transcripts in the batch.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: true,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/216650-transcript.txt"
    },
    {
      id: "221526",
      pet: "Baby Stewie",
      species: "Cat",
      visit: "Post-op urinary surgery recheck",
      firstRecommendationAccepted: true,
      takeaway: "A routine post-op recheck focused on healing and finishing medications.",
      notes: "The veterinarian checked incision healing, confirmed the cone could likely come off soon, and advised finishing the antibiotic course. The visit did not center on affordability or alternative plans.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/221526-transcript.txt"
    },
    {
      id: "279093",
      pet: "Clark",
      species: "Dog",
      visit: "Staple removal recheck / possible incision infection",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian pivoted sensibly when the incision still had pus: culture it, leave some staples, and treat instead of forcing premature closure.",
      notes: "The initial expectation was staple removal, but the veterinarian found an open, draining spot and changed course to culture, antibiotics, and delayed removal. It is a good staged reassessment case.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/279093-transcript.txt"
    },
    {
      id: "307684",
      pet: "Nero",
      species: "Dog",
      visit: "Hair loss / endocrine workup",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian used a stepwise workup: rule out endocrine disease first, then try melatonin if the panel is normal.",
      notes: "The plan moved from hormonal screening to melatonin and supportive care for alopecia, rather than jumping straight to empirical treatment. It is a staged but nonfinancial decision tree.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/307684-transcript.txt"
    },
    {
      id: "312320",
      pet: "Peach",
      species: "Dog",
      visit: "Acute vomiting and gas / GI workup",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian read the x-rays carefully, ruled out a clear obstruction, and recommended supportive care with explicit red flags.",
      notes: "The plan separated gassy large-bowel loops from a true small-bowel obstruction, then paired fluids, anti-nausea treatment, bland diet, and red-flag guidance about vomiting through Cerenia. This is a good example of minimum-responsible acute GI care.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/312320-transcript.txt"
    },
    {
      id: "343446",
      pet: "Hero",
      species: "Dog",
      visit: "Breathing episodes / vomiting / GI imaging review",
      firstRecommendationAccepted: true,
      takeaway: "The conversation is more about sorting a confusing, expensive ER workup into a plausible next step than about offering cheap substitutes.",
      notes: "The owners described ER frustration, prior expense, x-rays, and concern about a possible liver or intestinal problem. The veterinarian reframed the likely issues, explained why the x-rays did not look dramatically obstructive, and leaned toward viral enteritis or other GI irritation rather than something obviously surgical.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/343446-transcript.txt"
    },
    {
      id: "372631",
      pet: "Sharpie",
      species: "Cat",
      visit: "UTI culture follow-up call",
      firstRecommendationAccepted: true,
      takeaway: "A clean phone-call example of antibiotic options shaped by owner travel logistics rather than a hidden treatment pool.",
      notes: "The veterinarian explained that the cultured E. coli was susceptible to multiple choices, then contrasted continuing oral Clavamox with a two-week injection. The owner’s travel situation influenced the selection.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/372631-transcript.txt"
    },
    {
      id: "379165",
      pet: "Bailey",
      species: "Dog",
      visit: "Antibiotic-associated diarrhea follow-up",
      firstRecommendationAccepted: true,
      takeaway: "The vet managed a medication side effect with stepped supportive care rather than abandoning the underlying treatment plan.",
      notes: "The veterinarian suggested increasing fiber and adding metronidazole if needed to help the dog finish a twenty-eight-day antibiotic course. It is a practical supportive-care conversation with no overt price component.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/379165-transcript.txt"
    },
    {
      id: "385130",
      pet: "Champ",
      species: "Dog",
      visit: "Senior cough / ear and mobility summary",
      firstRecommendationAccepted: true,
      takeaway: "This transcript is closer to a concise treatment summary than a full shared-decision conversation.",
      notes: "The note-style transcript suggests ear cleaning, long-term Rimadyl, glucosamine and omega fatty acids, and antibiotic support for upper-airway or dental concerns. It did not read like an affordability negotiation.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/385130-transcript.txt"
    },
    {
      id: "389311",
      pet: "Jack",
      species: "Dog",
      visit: "Lip fold dermatitis / dental discussion",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian chose the only realistic treatment route for a hard-to-reach lesion and explained why topicals would fail.",
      notes: "The vet ruled out papillomas, diagnosed irritated lip folds, explained why topical treatment would be impractical, and shifted to oral antibiotics plus warm compresses. Dental prevention and future cleaning were also discussed.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/389311-transcript.txt"
    },
    {
      id: "407989",
      pet: "Buddy",
      species: "Dog",
      visit: "Senior wellness / dry eye / vaccines and ProHeart",
      firstRecommendationAccepted: true,
      takeaway: "A senior preventive visit with some declined work, but not really a transcript about lower-cost options.",
      notes: "The owner declined blood work in the pre-visit note, but the actual visit focused on vaccines, ProHeart, eye cleaning, anal glands, and supplements. It reads more like routine maintenance than a substantive affordability dialogue.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/407989-transcript.txt"
    },
    {
      id: "453574",
      pet: "Penny",
      species: "Dog",
      visit: "Vomiting after swallowed treat",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian used blood work and supportive care to avoid overcalling a treat-related vomiting episode as a surgical problem.",
      notes: "The plan explicitly contrasted blood work, x-rays, anti-nausea treatment, fluids, bland diet, and pain control, with clear guidance about the red flag of vomiting through Cerenia. This is a strong acute-care triage transcript.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/453574-transcript.txt"
    },
    {
      id: "468892",
      pet: "Zeus",
      species: "Dog",
      visit: "Bloodwork follow-up / thyroid discussion",
      firstRecommendationAccepted: true,
      takeaway: "A measured lab-interpretation call that adds one confirmatory test instead of jumping straight to treatment.",
      notes: "The veterinarian walked through CBC, chemistry, cholesterol, and thyroid values, then explained why a TSH confirmatory test made more sense than immediately treating hypothyroidism. It is staged decision making without a financial frame.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/468892-transcript.txt"
    },
    {
      id: "509384",
      pet: "Lucy",
      species: "Dog",
      visit: "Hot spot / allergy management",
      firstRecommendationAccepted: true,
      takeaway: "The vet kept treatment practical: continue targeted topical care unless the problem becomes broad enough to justify whole-body antibiotics.",
      notes: "The veterinarian linked the recurrent lesions to allergy, supported ongoing topical Mometamax when spots were limited, and explained that oral antibiotics would become reasonable only if the lesions multiplied or became too numerous to treat locally.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/509384-transcript.txt"
    },
    {
      id: "529996",
      pet: "Jarvis Ollie",
      species: "Cat",
      visit: "Diabetic cat mouth/GI follow-up",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian kept a diabetic-mouth/GI case on a conservative path because the numbers were stable and the cat was clinically better.",
      notes: "The steroid and Bexacat combination had not worsened the monitored values, so the plan was to continue the current low-dose steroid, add psyllium husk for stool quality, and push the next recheck out to a month. This reads like minimum-responsible chronic-care management.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/529996-transcript.txt"
    },
    {
      id: "533267",
      pet: "Rosie / Olive",
      species: "Dog",
      visit: "Seizure medication follow-up call",
      firstRecommendationAccepted: true,
      takeaway: "This is a good low-cost logistics transcript: immediate-release Keppra, dose adjustment, and GoodRx-driven pharmacy shopping.",
      notes: "The veterinarian discussed immediate-release Keppra dosing, a possible post-seizure loading dose, and practical script routing to whichever pharmacy offered the best GoodRx price. The point was not hidden medicine, but accessible medication logistics.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: true,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/533267-transcript.txt"
    },
    {
      id: "548624",
      pet: "Rosie",
      species: "Cat",
      visit: "Litter box behavior follow-up / antianxiety medication",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian framed the likely problem as behavioral and offered a simple medication-first path with room to titrate.",
      notes: "Normal lab work shifted the interpretation toward behavioral urination outside the litter box. The veterinarian offered a once-daily tablet, mentioned a compounded liquid if needed, and emphasized dose flexibility if the first pass was not enough.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/548624-transcript.txt"
    },
    {
      id: "560599",
      pet: "Vader",
      species: "Dog",
      visit: "Post-spinal-surgery discharge / mast cell concern",
      firstRecommendationAccepted: true,
      takeaway: "The case is full of real-world constraint management: postoperative recovery, a possible new mast cell issue, another aggressive dog at home, and owners already deep into surgical spend.",
      notes: "The veterinarian recommended Benadryl and Pepcid first, preferred to avoid another surgery immediately after spinal surgery, and openly acknowledged the family’s financial and home-management burdens. It is a strong example of sequencing care around what is tolerable now rather than piling on every intervention immediately.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/560599-transcript.txt"
    },
    {
      id: "567506",
      pet: "Tucker",
      species: "Dog",
      visit: "Vomiting blood / splenic enlargement / ultrasound decision",
      firstRecommendationAccepted: true,
      takeaway: "This is a strong staged-care case: repeat anti-nausea treatment, home ulcer meds, and outpatient ultrasound rather than automatic overnight hospitalization.",
      notes: "The veterinarian reviewed inconclusive x-rays, a benign-looking spleen enlargement, concern for pancreatitis or ulcer disease, and the option of staying overnight versus another anti-nausea shot plus outpatient ultrasound. The owners explicitly chose the less intensive path and the veterinarian endorsed it as reasonable.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/567506-transcript.txt"
    },
    {
      id: "569836",
      pet: "Enzo",
      species: "Cat",
      visit: "Hair tie / shower caddy ingestion",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian openly discussed retrieval versus watchful waiting and gave practical home-passing advice once repeated emesis failed.",
      notes: "After x-rays and multiple failed attempts to induce vomiting, the veterinarian explained why the item might still pass, what red flags would mean obstruction, and how white bread plus coconut or fish oil could help move it along. This is a classic non-surgical first path with clear thresholds for escalation.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/569836-transcript.txt"
    },
    {
      id: "620984",
      pet: "Callie",
      species: "Dog",
      visit: "Stone analysis follow-up call",
      firstRecommendationAccepted: true,
      takeaway: "A brief follow-up call centered on diet and periodic culture monitoring, not an affordability negotiation.",
      notes: "The veterinarian explained mixed stone composition, reinforced the current diet, and recommended urine cultures every three months. There was no meaningful tradeoff discussion beyond routine chronic management.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/620984-transcript.txt"
    },
    {
      id: "637192",
      pet: "Xumma",
      species: "Dog",
      visit: "Sudden hind-limb swelling / suspected bone cancer",
      firstRecommendationAccepted: true,
      takeaway: "This is one of the clearest high-stakes contextualized-care transcripts in the batch: CT or radiology overread, fungal testing, pain control, supportive care, and an honest discussion of why amputation may not buy much.",
      notes: "The veterinarian walked through bone cancer versus fungal disease, explained why the x-rays looked suspicious, offered specialist CT versus a $200 radiologist read, discussed amputation and chemo candidly, and adjusted recommendations to the owner’s treatment limits. It is a strong transcript for Andy’s question about explaining why certain paths are or are not worth pursuing.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: false,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/637192-transcript.txt"
    },
    {
      id: "665683",
      pet: "Luci",
      species: "Cat",
      visit: "Cat wellness / chronic ear debris / FELV discussion",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian made a simple indoor-versus-outdoor vaccine decision and did not push FELV once the lifestyle risk was clarified.",
      notes: "The visit centered on chronic ear debris, intermittent sneezing, vaccine updates, and the question of feline leukemia vaccination. The veterinarian explicitly said the FELV vaccine was unnecessary for an indoor cat with only balcony access.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/665683-transcript.txt"
    },
    {
      id: "667613",
      pet: "Emmy Lou",
      species: "Dog",
      visit: "Urine culture resistance follow-up",
      firstRecommendationAccepted: true,
      takeaway: "A short phone-call case where the main point was changing to the antibiotic the culture actually supported.",
      notes: "The veterinarian explained that the recent bacteria were resistant to the last two drugs but susceptible to Clavamox, then prescribed a straightforward seven-day switch. It was a clean culture-driven adjustment without a broader tradeoff discussion.",
      tags: {
        optionsOffered: false,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: false,
        noOptionButAppropriate: true,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/667613-transcript.txt"
    },
    {
      id: "739999",
      pet: "Athena",
      species: "Dog",
      visit: "Raisin ingestion summary note",
      firstRecommendationAccepted: false,
      takeaway: "This summary note is one of the clearest examples of financial constraints reshaping the plan from hospitalization to outpatient monitoring.",
      notes: "The recommendation was hospitalize on IV fluids after suspected raisin ingestion. Because of financial concerns, the owner chose outpatient care with prepaid rechecks and subcutaneous fluids instead.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: true,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: true,
        stagedTradeoff: true,
        pharmacySavings: false,
        riskExplained: true,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: true,
        barrierDetected: true
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/739999-transcript.txt"
    },
    {
      id: "805770",
      pet: "Bea",
      species: "Dog",
      visit: "Annual vaccines / grazing and Lyme discussion",
      firstRecommendationAccepted: true,
      takeaway: "The veterinarian normalized grazing, discouraged unnecessary Lyme vaccination while the dog stayed on Simparica, and kept the plan simple.",
      notes: "The visit addressed grief-related appetite change, body condition, feeding strategy, vaccine updates, and whether Lyme vaccination was needed. The vet explicitly leaned away from the Lyme vaccine because the dog was already on tick prevention and had limited exposure.",
      tags: {
        optionsOffered: true,
        explicitMoneyLanguage: false,
        explicitDeclineInquiry: false,
        alternativeOnDecline: false,
        payRelatedOption: false,
        stagedTradeoff: false,
        pharmacySavings: false,
        riskExplained: false,
        minimumResponsible: true,
        noOptionButAppropriate: false,
        representative: false,
        barrierDetected: false
      },
      transcriptPath: "3-8-jason.szumski copy/Transcripts/805770-transcript.txt"
    }
  ]
};
