window.ANDY_ANALYSIS = {
  "meta": {
    "title": "Andy Transcript Analysis Dashboard",
    "subtitle": "Andy-framed review of 50 random Jason Szumski transcripts",
    "date": "2026-03-18",
    "sampleNote": "50-random-transcript sample from Point 4 evaluation; one-veterinarian sample, not a profession-wide estimate.",
    "sourcePage": "Point4_Transcript_Evaluation.html",
    "memoPath": "Andy_50_Transcript_Analysis.md"
  },
  "thesis": {
    "headline": "This 50-transcript sample supports Andy’s core point more than it undermines it.",
    "body": "The dominant pattern is not hidden cheap medicine. It is staged, medically responsible tradeoffs: narrower workups, cheaper logistics, home management when safe, and clear explanations when the lower-cost path would be weaker or riskier."
  },
  "questions": [
    "How often does money come up at all?",
    "Are vets offering real lower-cost options, or only weak compromises after pushback?",
    "Do vets ask about goals, decline reasons, or constraints before recommending?",
    "Do vets explain when the cheaper path is a bad idea?",
    "Is the plan usually already close to the minimum responsible plan?",
    "Are practical access tools more common than formal financing?"
  ],
  "metrics": {
    "total": 50,
    "optionsOffered": 45,
    "moneyLanguage": 16,
    "explicitDeclineInquiry": 4,
    "payRelatedOption": 10,
    "firstRecommendationAccepted": 49,
    "noOptionButAppropriate": 5,
    "stagedTradeoff": 23,
    "riskExplained": 5,
    "minimumResponsible": 4,
    "pharmacySavings": 4
  },
  "patterns": [
    {
      "key": "optionsOffered",
      "label": "Options Offered",
      "value": 45,
      "total": 50,
      "color": "#1f8f5f"
    },
    {
      "key": "moneyLanguage",
      "label": "Explicit Money Language",
      "value": 16,
      "total": 50,
      "color": "#2269b5"
    },
    {
      "key": "stagedTradeoff",
      "label": "Staged Tradeoffs",
      "value": 23,
      "total": 50,
      "color": "#cc7a00"
    },
    {
      "key": "explicitDeclineInquiry",
      "label": "Asked Why Before Pivoting",
      "value": 4,
      "total": 50,
      "color": "#9b59b6"
    },
    {
      "key": "payRelatedOption",
      "label": "Pay / Lower-Cost Logistics",
      "value": 10,
      "total": 50,
      "color": "#d9485f"
    },
    {
      "key": "riskExplained",
      "label": "Risk of Cheaper Path Explained",
      "value": 5,
      "total": 50,
      "color": "#8e3b46"
    },
    {
      "key": "minimumResponsible",
      "label": "Minimum Responsible Framing",
      "value": 4,
      "total": 50,
      "color": "#2d7a9a"
    },
    {
      "key": "pharmacySavings",
      "label": "Pharmacy Savings",
      "value": 4,
      "total": 50,
      "color": "#57606f"
    },
    {
      "key": "noOptionButAppropriate",
      "label": "No Option Needed",
      "value": 5,
      "total": 50,
      "color": "#6b7280"
    }
  ],
  "transcriptBuckets": {
    "representativeIds": [
      "145721",
      "312322",
      "197895",
      "518435",
      "47619",
      "131852",
      "223582",
      "1316",
      "702488",
      "278772"
    ],
    "noOptionButAppropriateIds": [
      "187364",
      "23921",
      "7972",
      "305642",
      "501501"
    ]
  },
  "transcripts": [
    {
      "id": "108559",
      "pet": "Sweetie",
      "species": "Dog",
      "visit": "Emergency — Syncopal events / heart failure",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "X-ray then hospitalization",
      "notes": "Exemplary communication. Vet explained syncopal vs seizure in lay terms, presented Option 1 (diagnostics + hospitalization) and Option 2 (euthanasia) with compassion, discussed prognosis realistically, reviewed x-rays together with owner, explained kidney monitoring. Cost estimate promised. No barriers detected. Payment plan not explicitly offered but estimate was provided.",
      "badges": [
        "Cost Language",
        "Staged Tradeoff"
      ],
      "takeaway": "The vet offers a staged, financially aware path rather than all-or-nothing medicine.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/108559-transcript.txt"
    },
    {
      "id": "120525",
      "pet": "Bambi",
      "species": "Dog",
      "visit": "Rabies vaccine + neuter consult + aggression/anxiety",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Neuter + training + trazodone",
      "notes": "Vet provided multi-faceted plan: neutering to reduce hormonal aggression, training recommendations (daycare, Barrington Square, Dogtopia), behavioral handout, trazodone for interim relief, and discussed Prozac as future option. Offered spectrum of care from behavioral to pharmaceutical. Clear, conversational communication. No payment plan discussed.",
      "badges": [
        "Cost Language"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/120525-transcript.txt"
    },
    {
      "id": "12169",
      "pet": "Wyla",
      "species": "Cat",
      "visit": "Annual exam / vomiting follow-up",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Continue Fortiflora + steroid + monitor",
      "notes": "Good rapport and warm communication. Vet discussed pigmentation concern clearly, explained normal aging changes, addressed herpes flare-up possibility related to stress, discussed antibiotics from prior call that were never picked up. Assessed that body likely cleared the UTI naturally. No cost discussion needed — routine visit.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/12169-transcript.txt"
    },
    {
      "id": "1316",
      "pet": "Mickey",
      "species": "Dog",
      "visit": "Vaccine consult / arthritis / boarding discussion",
      "firstRecommendationAccepted": false,
      "firstRecommendation": "Full vaccination panel for boarding",
      "notes": "Outstanding spectrum of care. Owner asked whether a 14-year-old dog needed full vaccines. Vet acknowledged age concern, didn't push, explained which vaccines were truly needed vs optional. Owner chose only Bordetella + rabies — vet supported this. For arthritis, vet offered gabapentin at two dose levels (pain vs anxiety), mentioned Rimadyl and Librela as additional options. Transparent about cost tiers at different boarding facilities. Gabapentin for separation anxiety also discussed as anti-anxiety trial. No payment plans explicitly offered.",
      "badges": [
        "Representative",
        "Cost Language",
        "Asked Why",
        "Staged Tradeoff",
        "Minimum Responsible Care"
      ],
      "takeaway": "The vet explicitly explores the client’s hesitation and then pivots to an alternative plan.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": true,
        "alternativeOnDecline": true,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": true,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/1316-transcript.txt"
    },
    {
      "id": "13434",
      "pet": "Cooper",
      "species": "Dog",
      "visit": "New patient — puppy wellness / ears / food / training",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Bordetella + ear cleaner + fecal + food guidance",
      "notes": "Very thorough new-patient visit. Vet addressed diet (Pro Plan chicken & rice, calculated calories at 850/day), training options (in-person preferred over drop-off, specific local recommendations), ear care protocol, neuter site check, allergy monitoring plan (environmental vs food), and fecal testing rationale. Tech provided good handoff. Positive reinforcement training advocated. Long, unhurried visit.",
      "badges": [
        "Cost Language",
        "Staged Tradeoff"
      ],
      "takeaway": "The vet offers a staged, financially aware path rather than all-or-nothing medicine.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/13434-transcript.txt"
    },
    {
      "id": "145721",
      "pet": "Abe",
      "species": "Dog",
      "visit": "Sick visit — not eating 3 days, abdominal pain",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "X-ray (stepwise approach offered)",
      "notes": "Vet offered stepwise diagnostics: Option A was blood work + x-rays together; Option B was start with x-ray of belly only, and if answer found, skip blood work. This is excellent spectrum of care — allowing owner to manage cost while still getting diagnostics. Explained findings on physical exam clearly (enlarged testicle, perianal hyperplasia, prostate exam). No jargon without explanation.",
      "badges": [
        "Representative",
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/145721-transcript.txt"
    },
    {
      "id": "165858",
      "pet": "Jellybean",
      "species": "Cat",
      "visit": "Sick visit — gagging/constipation on atopica",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Cerenia injection + sub-Q fluids",
      "notes": "Vet offered clear plan: anti-nausea injection (Cerenia), sub-Q fluids with Gatorade analogy for electrolytes, and optional x-ray (but was transparent that exam findings were benign). Deferred to regular vet on atopica dosing change — appropriate. Discussed hydrolyzed diet already in place. Waiting on blood work from regular vet before making further decisions. Owner was a vet tech — staff-to-staff communication was efficient and respectful.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/165858-transcript.txt"
    },
    {
      "id": "187364",
      "pet": "Willow & Vinny",
      "species": "Dog",
      "visit": "Routine vaccines — two puppies",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Annual vaccines (3 each)",
      "notes": "Straightforward dual-puppy wellness visit. Vaccines administered with clear explanation of injection sites and potential sensitivity. Noted Vinny was on doxycycline for tick — acknowledged GI side effects as expected. Both dogs examined, temp checked, Cook County rabies tags provided. Short, efficient, warm. No options to offer since this was strictly a vaccine visit.",
      "badges": [
        "No Option Needed"
      ],
      "takeaway": "No meaningful alternative path was needed; this was a protocol-driven or non-evaluable case.",
      "tags": {
        "optionsOffered": false,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": true,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/187364-transcript.txt"
    },
    {
      "id": "20571",
      "pet": "Olly",
      "species": "Cat",
      "visit": "Recheck — blood in urine / bladder stone",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Ultrasound + urine sample, then diet trial",
      "notes": "Vet explained diagnostic plan clearly: ultrasound to check for bladder stone, urine sample via cystocentesis, possible x-ray if ultrasound inconclusive. When stone was confirmed, offered both dietary dissolution trial (urinary SO diet for 4-8 weeks with recheck at 4 weeks) and mentioned surgical options. Good spectrum of care — conservative approach first. Transcript is truncated but approach is sound.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/20571-transcript.txt"
    },
    {
      "id": "223582",
      "pet": "Nelly",
      "species": "Dog",
      "visit": "Routine vaccines + allergy Rx refill",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "3-year rabies (cost-compared with 1-year)",
      "notes": "Vet proactively offered choice between 1-year ($54) and 3-year ($99) rabies — transparent cost comparison. Owner chose 3-year. Apoquel prescription renewed for Costco pickup — acknowledging owner's pharmacy preference for cost savings. Allergy management discussed: use Apoquel as needed when itching returns during pollen season. Miralax dosing relayed for another pet. Good exam, no concerns.",
      "badges": [
        "Representative",
        "Cost Language",
        "Pharmacy Savings"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": true,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/223582-transcript.txt"
    },
    {
      "id": "23921",
      "pet": "Javi",
      "species": "Dog",
      "visit": "Emergency — grape ingestion / toxicity",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Emesis + monitoring",
      "notes": "Emergency visit — grape ingestion in 18.5 lb dog. Vet called poison control, induced vomiting, recovered most grapes. Explained two trains of thought on grape toxicity (dose-dependent vs pesticide-related). Clear discharge instructions: monitor for vomiting, excess drinking/urination, possible loose stool. Poison control report printed for owner. Praised owner for acting quickly. No cost discussion needed — emergency with clear protocol.",
      "badges": [
        "Cost Language",
        "Staged Tradeoff",
        "No Option Needed"
      ],
      "takeaway": "No meaningful alternative path was needed; this was a protocol-driven or non-evaluable case.",
      "tags": {
        "optionsOffered": false,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": true,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/23921-transcript.txt"
    },
    {
      "id": "27483",
      "pet": "Enzo",
      "species": "Dog",
      "visit": "Post-boarding — bloody nose + diarrhea",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Probiotic paste + capsules",
      "notes": "Vet examined nose, explained reverse sneezing can rupture vessels, reassured about allergens at kennel. For diarrhea, prescribed probiotic paste (3 days) + capsules (7 days) — described paste as 'pumpkin on steroids' (good lay analogy). Validated owner's use of pumpkin. Warm, reassuring tone with first-time dog owners who compared themselves to new parents. Efficient visit.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/27483-transcript.txt"
    },
    {
      "id": "278166",
      "pet": "Anna",
      "species": "Dog",
      "visit": "End-of-life — kidney failure / euthanasia discussion",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Sub-Q fluids + schedule euthanasia",
      "notes": "Deeply compassionate end-of-life conversation. Vet presented creatinine (4.2→12.9) and BUN (63→120) clearly with context. Explained 75% kidney threshold concept without jargon. Offered multiple euthanasia options: today, later tonight, tomorrow morning, at home via house call service. Gave sub-Q fluids for comfort. Discussed timeline, scheduling, what to expect (30 seconds, hour total visit). Validated owner's grieving process. Addressed acute vs chronic kidney disease question. No financial barriers imposed.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/278166-transcript.txt"
    },
    {
      "id": "312322",
      "pet": "Nacho",
      "species": "Dog",
      "visit": "Recheck — IVDD (intervertebral disc disease) pain management",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Day hospitalization for pain med management",
      "notes": "Excellent cost transparency. Vet offered: Option 1 — keep here for ~12 hrs ($100 medical boarding); Option 2 — give meds now, go home. Also explained 24-hr hospitalization with IV ($750-1000) if needed longer. Owner asked about costs directly and vet answered transparently with hourly hospitalization rates. Explained gabapentin every 8 hrs (not 12) for better pain control, Rimadyl injection option for food-refusing dog. Emphasized 6-8 week strict rest. Owner involved in decision. Full financial discussion.",
      "badges": [
        "Representative",
        "Cost Language",
        "Asked Why",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff"
      ],
      "takeaway": "The vet explicitly explores the client’s hesitation and then pivots to an alternative plan.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": true,
        "alternativeOnDecline": true,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/312322-transcript.txt"
    },
    {
      "id": "3180",
      "pet": "Maple",
      "species": "Dog",
      "visit": "Tooth loss / dental disease assessment",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Schedule dental cleaning + extraction",
      "notes": "Vet explained dental disease clearly — bacteria caking on teeth, gingival inflammation, calculus hiding underlying issues. Offered two paths: pull loose incisor under sedation now, or do full dental cleaning (preferred). Discussed post-dental care realistically: 'I've realized daily brushing isn't realistic' — moved to Greenies recommendation. Addressed anesthesia fears from prior bad experience at another clinic. Explained modern reversible anesthesia. Drop-off protocol explained (7-7:30AM, call when awake, pickup early-mid afternoon). Toenail trim added while under.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/3180-transcript.txt"
    },
    {
      "id": "383662",
      "pet": "Cooper/Bentley/Kaden",
      "species": "Dog",
      "visit": "Phone call — hookworm results + deworming plan",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Drontal dewormer + consistent Simparica Trio",
      "notes": "Phone call delivering fecal results. Vet explained hookworm transmission between dogs clearly, noted Bentley cleared but Cooper and Kaden now positive. Discussed that Simparica Trio also kills hookworms if given consistently — offered long-term prevention strategy alongside acute treatment. Planned recheck fecal in 2 weeks. Efficient, clear phone communication.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/383662-transcript.txt"
    },
    {
      "id": "420398",
      "pet": "Vivian",
      "species": "Dog",
      "visit": "Recheck — worsening infection, possible fungal (blastomycosis)",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Hospitalization + fungal panel + chest x-rays",
      "notes": "Complex case with rapidly deteriorating values over 5 days. Vet walked through CBC, chem panel side-by-side with prior results — explained each marker in lay terms (WBC 8.4→26K, bands indicating true infection, platelets low = bruising risk, kidney and liver values climbing). Transparent about prognosis: 'I wanna be honest with you... this is progressing quickly which scares me.' Explained blastomycosis etiology (sniffing soil), lepto vaccination relevance. Offered visitation policy during hospitalization. Itemized estimate promised.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/420398-transcript.txt"
    },
    {
      "id": "533936",
      "pet": "Ghost",
      "species": "Dog",
      "visit": "Recheck — immune-mediated disease, skin infections",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Taper prednisone 10/5→5/5, continue antibiotics",
      "notes": "Minor jargon: 'first generation cephalosporin' used briefly but then simplified. Owner asked about antibiotic resistance — vet explained clearly. Good discussion of immunosuppressive medication taper plan, skin infection management during taper, warm compress for scabs, fish oil for skin barrier. Transparent about Simparica Trio pricing ($37.78 single, $206.68 six-pack with rebate). Weight-based dosing explained. Monthly recheck schedule maintained. Overall strong communication with one minor jargon moment.",
      "badges": [
        "Cost Language",
        "Asked Why",
        "Barrier Detected"
      ],
      "takeaway": "The vet explicitly explores the client’s hesitation and then pivots to an alternative plan.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": true,
        "alternativeOnDecline": true,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": true
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/533936-transcript.txt"
    },
    {
      "id": "560621",
      "pet": "Tank",
      "species": "Dog",
      "visit": "Emergency — pharyngeal mass / airway obstruction",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Intubation + overnight oxygen + specialist referral",
      "notes": "High-acuity emergency. Vet walked owner through x-ray findings in real-time, explained the gray circular area, hyoid anatomy. When mass was discovered (not a foreign body), discussed: debulking in-house vs specialist surgery (recommended). Arranged transfer to specialist at 4:30AM for morning surgery slot. Explained worst case (airway obstruction) and best case (debulk and remove). Owner wanted to stay overnight — vet accommodated. Steroid injection to reduce swelling. Guarded prognosis discussed with cancer likelihood. Owner stated 'we don't care what it costs' — no financial barrier.",
      "badges": [
        "Staged Tradeoff",
        "Risk of Cheaper Path Explained"
      ],
      "takeaway": "The vet discusses a cheaper or less invasive path, but explains clearly why it may be inadequate or risky.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": true,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/560621-transcript.txt"
    },
    {
      "id": "667596",
      "pet": "Sammy",
      "species": "Dog",
      "visit": "Phone call — GI panel results / diet recommendation",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Hypoallergenic diet + fiber for 4-5 months",
      "notes": "Phone call explaining GI panel. Minor jargon: 'trypsin-like immunoreactivity' used but then explained ('tests for pancreatic enzymes'). Discussed pancreatitis (negative), TLI (normal), B12 dysbiosis. Practical advice: pick up small bag first to test palatability, two approved diets to choose from, script at clinic. Emphasized puppy-specific nutritional needs (minerals for bone development). Recheck in 4 months. Clear, educational phone communication.",
      "badges": [
        "Barrier Detected"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": true
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/667596-transcript.txt"
    },
    {
      "id": "701996",
      "pet": "Lily",
      "species": "Cat",
      "visit": "Vaccines + eye discharge management",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Distemper vaccine + new eye ointment",
      "notes": "Vet addressed eye discharge history, explained distemper vaccine helps protect against upper respiratory causes of discharge. When current ointment wasn't resolving in 24 hours, switched to different antibiotic ointment (resistant infection hypothesis). Set clear timeline: if still discharging in 1 month, reevaluate. Exam thorough — lymph nodes, heart. Also discussed Addison's disease case management with staff (educational moment).",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/701996-transcript.txt"
    },
    {
      "id": "702488",
      "pet": "Bella",
      "species": "Dog",
      "visit": "Hospitalized — vestibular disease (vertigo)",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Continue hospitalization + meclizine + Cerenia",
      "notes": "Vet explained vestibular disease clearly using 'old dog idiopathic vestibular disease' then simplified. Described nystagmus ('eyes bouncing back and forth'). Discussed medications: meclizine for dizziness, Cerenia for nausea/motion sickness. Offered medical boarding at $80/day as step-down from ICU. Owner expressed financial concern ('I didn't think I could afford your next price') — vet offered lower-cost medical boarding option and sling/mask to facilitate home care. Payment discussion was responsive to owner's stated concern.",
      "badges": [
        "Representative",
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff"
      ],
      "takeaway": "The vet offers a staged, financially aware path rather than all-or-nothing medicine.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/702488-transcript.txt"
    },
    {
      "id": "702614",
      "pet": "Xoco",
      "species": "Cat",
      "visit": "Phone update — post foreign body surgery",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Appetite stimulant + owner visit at 2PM with food",
      "notes": "Brief phone update on post-surgical cat. Vet explained 24-hour post-surgery eating expectation, plan to start appetite stimulant at lunchtime, invited owner to bring home food at 2PM. Goal: if eating, discharge same day. Clear, concise, warm phone communication.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/702614-transcript.txt"
    },
    {
      "id": "7972",
      "pet": "Murphy",
      "species": "Dog",
      "visit": "Emergency — allergic reaction / facial swelling",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Antihistamine injections + Benadryl at home",
      "notes": "Classic allergic reaction emergency. Vet explained differential causes (bug bite, food, vaccine reaction — ruled out last). Treatment plan clear: in-hospital injections for swelling, Benadryl at home (half of 25mg tablet every 8 hours for 13.5 lb dog). Explained monitoring: breathing difficulty = come back, possible flare-up, possible diarrhea. Practical 15-minute observation period before discharge. Efficient emergency visit.",
      "badges": [
        "Staged Tradeoff",
        "No Option Needed"
      ],
      "takeaway": "No meaningful alternative path was needed; this was a protocol-driven or non-evaluable case.",
      "tags": {
        "optionsOffered": false,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": true,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/7972-transcript.txt"
    },
    {
      "id": "815388",
      "pet": "Major",
      "species": "Dog",
      "visit": "Recheck — glaucoma / intraocular pressure management",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Add latanoprost drops + continue CoSopt",
      "notes": "Vet explained left eye responding well (normal pressure), right eye pressure climbing. Added third medication (latanoprost) with different mechanism of action. Scheduled Sunday recheck with another doctor who was briefed. Discussed surgical option (enucleation) when owner asked: would remove right eye only, leave comfortable left eye. Offered to consult ophthalmologist for additional ideas. Transparent that 'I've never had to go past these three without taking out the eye.' Honest, collaborative approach.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/815388-transcript.txt"
    },
    {
      "id": "131852",
      "pet": "Butterscotch",
      "species": "Cat",
      "visit": "Sick — not eating 2 days, drinking excessively",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "In-house blood work (vs send-out option)",
      "notes": "Excellent spectrum of care with explicit cost options. Vet explained two differential diagnoses (CKD vs hyperthyroidism) in lay terms with analogies (dialysis comparison). Offered Option 1: in-house blood work (results in 25-30 min, more expensive) vs Option 2: send-out (results next day, cheaper). Recommended in-house given severity. Heart murmur noted and connected to hyperthyroid possibility. Feliway towel for stress reduction. Owner's cat ornery — vet accommodating. Also discussed dental findings after blood draw. No jargon without explanation.",
      "badges": [
        "Representative",
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Risk of Cheaper Path Explained"
      ],
      "takeaway": "The vet discusses a cheaper or less invasive path, but explains clearly why it may be inadequate or risky.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": true,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/131852-transcript.txt"
    },
    {
      "id": "192750",
      "pet": "Billion",
      "species": "Dog",
      "visit": "Second opinion — lip hair loss / irritation",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Apoquel + coconut oil + fish oil supplement",
      "notes": "Clear stepwise approach: coconut oil topical (safe if licked), Apoquel to break itch-lick cycle (explained mechanism: 'tells brain you're not itchy'), fish oil for hair regrowth. Examined teeth to rule out dental cause. Explained histamine mechanism without jargon. Tapering course explained (twice daily for 1 week, then once daily for 1 week). Offered OTC supplement recommendation. Checked Simparica Trio status for Demodex rule-out. Weight checked on baby scale for accuracy. Warm, thorough.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/192750-transcript.txt"
    },
    {
      "id": "197895",
      "pet": "Lottie",
      "species": "Dog",
      "visit": "Annual — mobility issues / arthritis in 14-year-old",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "NSAID (pending renal panel) + vaccines",
      "notes": "Excellent access-to-care. Owner declined heartworm test — vet didn't push but pivoted to recommend renal panel instead (needed before starting NSAID). Explained kidney concern from prior blood work (creatinine/BUN elevated in 2023). Offered in-house (faster, more expensive) vs send-out (cheaper, results next day) — owner chose send-out. Used own 13.5-year-old lab as relatable example. Described lowest effective dose strategy. Demonstrated hip range of motion. UTI history addressed. Personal, unhurried despite being a 14-year-old dog.",
      "badges": [
        "Representative",
        "Asked Why",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Minimum Responsible Care"
      ],
      "takeaway": "The vet explicitly explores the client’s hesitation and then pivots to an alternative plan.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": true,
        "alternativeOnDecline": true,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": true,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/197895-transcript.txt"
    },
    {
      "id": "216866",
      "pet": "Bella Boo",
      "species": "Dog",
      "visit": "Brown vaginal discharge / possible diabetes discovery",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Antibiotics + wipes + blood panel for diabetes",
      "notes": "Diagnostic workup pivoted mid-visit when urinalysis revealed sugar — vet explained diabetes connection clearly and pivoted plan. Discussed hooded vulva causing recurrent UTI, offered two long-term solutions (weight loss vs vulvoplasty surgery). Differentiated ovarian remnant from infection. Sent out blood panel with promise to call with results and walk through insulin training if needed. Practical discharge: wipes for skin folds, antibiotics. Stepwise approach from conservative to surgical.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/216866-transcript.txt"
    },
    {
      "id": "278772",
      "pet": "Mudslide",
      "species": "Dog",
      "visit": "Wellness — cyst, dental, weight, training consult",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Blood work + vaccines + weight management plan",
      "notes": "Tech reduced cost by ~$200 before vet entered room — excellent spectrum of care at front desk. 'Some blood work is better than no blood work' philosophy. Vet addressed: cyst (drain vs monitor), dental tartar (treats vs ultrasonic cleaning with honest 'lasts about a year' caveat), tip fracture (explained no pulp exposure), weight (73→60-65 lb target, 800-1000 cal/day calculated, calorie sheet provided), incontinence in daughter's dog (urine sample recommended). Also addressed Barkley's seizure question via phone. Thorough, multi-pet consultation.",
      "badges": [
        "Representative",
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Minimum Responsible Care"
      ],
      "takeaway": "The vet offers a staged, financially aware path rather than all-or-nothing medicine.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": true,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/278772-transcript.txt"
    },
    {
      "id": "291602",
      "pet": "Puck",
      "species": "Dog",
      "visit": "New patient — leg mass / ursodiol refill",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Topical steroid/antibiotic cream (vs surgical excision)",
      "notes": "Vet performed FNA in-house, reported results immediately (no mast cells — benign). Discussed surgical excision challenge (poor skin closure at that location) and offered conservative topical therapy first. Transparent about expectations ('probably not to nothing, but a decent amount of shrinkage'). Ursodiol refill handled via online pharmacy with price-matching (Chewy/Amazon). Twice daily application with practical advice: apply before dinner to distract from licking. Written instructions provided.",
      "badges": [
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Risk of Cheaper Path Explained",
        "Pharmacy Savings"
      ],
      "takeaway": "The vet discusses a cheaper or less invasive path, but explains clearly why it may be inadequate or risky.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": true,
        "riskExplained": true,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/291602-transcript.txt"
    },
    {
      "id": "305642",
      "pet": "She",
      "species": "Dog",
      "visit": "Surgical dictation — foreign body enterotomy",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "N/A — surgical procedure note",
      "notes": "This is a surgical dictation recording, not a client-facing conversation. Heavy medical terminology throughout (dorsal recumbency, ciliotomy, enterotomy, PDS suture, mesentery, peristalsis). Appropriate for medical record but not evaluable for client communication barriers or approach to care. Included for completeness.",
      "badges": [
        "No Option Needed",
        "Barrier Detected"
      ],
      "takeaway": "No meaningful alternative path was needed; this was a protocol-driven or non-evaluable case.",
      "tags": {
        "optionsOffered": false,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": true,
        "representative": false,
        "barrierDetected": true
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/305642-transcript.txt"
    },
    {
      "id": "3701",
      "pet": "Toffee",
      "species": "Dog",
      "visit": "Recheck — steroid taper for mass / wellness vaccines",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Taper prednisone to quarter tab BID + blood work",
      "notes": "Complex steroid management case. Vet engaged deeply with owner's detailed medication history, validated owner's observations about evening episodes. Explained dose-response relationship at different ranges. Acknowledged muscle wasting from steroids. Offered to increase food to compensate for weight loss. Blood work sent out with next-day callback plan. Addressed eye discharge (seasonal allergies, Benadryl helping). Bordetella oral vaccine given with kennel cough explanation. Cook County rabies tag provided. Long, patient conversation.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/3701-transcript.txt"
    },
    {
      "id": "47619",
      "pet": "Gracie",
      "species": "Cat",
      "visit": "Sick — URI / herpes virus / sneezing",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Antibiotic injection + lysine supplement",
      "notes": "Vet explained herpes virus lifecycle clearly: latent infection, stress triggers, 7-day self-clearing, when antibiotics are/aren't needed. Decision to treat with antibiotic injection based on fever finding. Lysine supplement recommended with Amazon option noted as cheaper than in-clinic. Discussed need for FVRCP booster (got one as kitten, needs second). Connected brother's visit yesterday for context. Transparent about when antibiotics help vs don't ('if not yellow discharge, antibiotics are questionable').",
      "badges": [
        "Representative",
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Risk of Cheaper Path Explained",
        "Minimum Responsible Care",
        "Pharmacy Savings"
      ],
      "takeaway": "The vet discusses a cheaper or less invasive path, but explains clearly why it may be inadequate or risky.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": false,
        "pharmacySavings": true,
        "riskExplained": true,
        "minimumResponsible": true,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/47619-transcript.txt"
    },
    {
      "id": "483190",
      "pet": "Sosa",
      "species": "Dog",
      "visit": "Recheck — chronic pain / spinal / adding amantadine",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Add amantadine for chronic wind-up pain",
      "notes": "Minor jargon: 'mechanistically similar to ketamine' briefly used but then clarified ('they don't become zombies'). Excellent pain management approach — introduced amantadine for chronic wind-up pain, explained 2-week onset, discussed potential to eventually reduce gabapentin and Rimadyl. Compared Rimadyl (liver monitoring needed) vs gabapentin (very safe long-term). Owner involved in titration plan: if going well, slowly back off other meds. Lumps examined — no intramuscular masses palpated. Spinal pain etiology explained with sciatica analogy.",
      "badges": [
        "Staged Tradeoff",
        "Barrier Detected"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": true
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/483190-transcript.txt"
    },
    {
      "id": "491107",
      "pet": "Linus",
      "species": "Dog",
      "visit": "Senior annual — sebaceous adenoma / heart murmur",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Rabies vaccine + heartworm test + nail trim",
      "notes": "Warm rapport with anxious owner. Sebaceous adenoma identified and explained ('old dog wart') — could remove during future anesthesia. Discussed continuity of care concern openly (owner had seen 5 different vets) — vet encouraged picking a favorite for consistency, acknowledged yearly stuff is fine with anyone. Online pharmacy with price matching offered for Heartgard. Muzzle used respectfully. Owner mentioned back history — vet connected prior Metacam success. Nail trim accommodated. Results promised by email within 1-2 days.",
      "badges": [
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Pharmacy Savings"
      ],
      "takeaway": "The vet offers a staged, financially aware path rather than all-or-nothing medicine.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": true,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/491107-transcript.txt"
    },
    {
      "id": "501501",
      "pet": "Taki/Bella",
      "species": "Dog",
      "visit": "Phone call — blood work results / dental scheduling",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Schedule dental cleaning",
      "notes": "Brief voicemail delivering blood work results. Minor jargon: 'inflammatory leukogram' used but then explained ('probably related to Bella's teeth with all the inflammation going on in the gums'). Results unremarkable — cleared for dental. Direct, efficient phone communication.",
      "badges": [
        "No Option Needed",
        "Barrier Detected"
      ],
      "takeaway": "No meaningful alternative path was needed; this was a protocol-driven or non-evaluable case.",
      "tags": {
        "optionsOffered": false,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": true,
        "representative": false,
        "barrierDetected": true
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/501501-transcript.txt"
    },
    {
      "id": "507958",
      "pet": "Pearl",
      "species": "Cat",
      "visit": "Sick — 21-year-old cat / weight loss / kidney disease",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Kidney diet + appetite stimulant + B12 + antibiotic injection",
      "notes": "Outstanding end-of-life care conversation. Vet was upfront: 'if kidney values were 13-14, I'd say it's not fair' but at current levels, comfortable trying therapy. Addressed quality of life question directly when owners asked 'are we being selfish?' — 'I'm pretty upfront about that. If I felt like it, I would let you know.' Broad approach: antibiotic injection (2 weeks), B12 injection, kidney diet (3 Hill's options to try), appetite stimulant (ear ointment — explained absorption, warned to wear gloves). Arthritis deferred to after kidney stabilization. Monthly recheck with same vet requested. Compared diabetes management (which owners had done) to kidney disease ('much easier'). Compassionate, honest, thorough.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/507958-transcript.txt"
    },
    {
      "id": "518435",
      "pet": "Stella",
      "species": "Cat",
      "visit": "Hospitalized — foreign body / scope vs surgery decision",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Scope first, flip to surgery if unsuccessful",
      "notes": "Exceptional shared decision-making. Vet presented scope vs surgery with full transparency on pros/cons/costs. Scope: less invasive, cheaper, faster recovery, but might miss secondary object. Surgery: definitive but more invasive. Offered hybrid approach: try scope 10 min, flip to surgery if needed ('I normally wash the cost and just charge for surgery'). Explained pylorus obstruction with anatomical detail. Discussed intestinal plication risk. Acknowledged cat's surgical history may complicate. Multiple calls with family members (son and parent) — repeated information patiently. Praised owner's care: 'you've played this exactly how I would have with my cat regardless of money.' Financial discussion transparent ($100 difference for anesthesia time).",
      "badges": [
        "Representative",
        "Cost Language",
        "Pay / Lower-Cost Logistics",
        "Staged Tradeoff",
        "Risk of Cheaper Path Explained"
      ],
      "takeaway": "The vet discusses a cheaper or less invasive path, but explains clearly why it may be inadequate or risky.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": true,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": true,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/518435-transcript.txt"
    },
    {
      "id": "542106",
      "pet": "Donnie",
      "species": "Dog",
      "visit": "Annual — vaccines / weight management / reactive dog",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "3-year rabies + ProHeart + Provecta + weight plan",
      "notes": "Reactive Rottweiler managed collaboratively between vet and tech. Tech developed treat-based system, positive reinforcement approach noted from prior visit. Vet addressed weight gain (120→132 lb) with calorie calculator (1,200 cal/day target). Connected reduced walks (twins born) to weight gain empathetically. 3-year rabies chosen to minimize future visits. ProHeart injection for heartworm (less pokes = better for reactive dog). Blood work deferred to next year based on age. Practical, supportive visit.",
      "badges": [
        "Cost Language"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": true,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/542106-transcript.txt"
    },
    {
      "id": "56770",
      "pet": "Binky",
      "species": "Cat",
      "visit": "Skin rash / bacterial infection + rabies vaccine",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Topical cream + area shave + rabies vaccine",
      "notes": "Vet performed skin scrape and microscopy in-house, reported results within 5 minutes (bacterial infection). Explained shaving area for better cream absorption — reassured hair regrowth in ~1 month. Simple treatment: topical cream once daily for 7 days with follow-up if not resolved. Rabies vaccine administered (Cook County requirement noted). Rescue cat with anxiety — vet handled gently. Tech handoff was clean with good history.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/56770-transcript.txt"
    },
    {
      "id": "603257",
      "pet": "Fiona",
      "species": "Dog",
      "visit": "Routine wellness — 3-year rabies + tooth monitoring",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "3-year rabies + monitor chipped tooth",
      "notes": "Brief, efficient wellness visit. Vet identified chip fracture on molar — explained no pulp exposure (not painful since eating normally). Offered monitoring vs X-ray under anesthesia if signs develop. 40x blood panel and lepto vaccine scheduled. Bordetella and flu due in 2 weeks. Warm, quick visit with no concerns.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/603257-transcript.txt"
    },
    {
      "id": "6685",
      "pet": "Blitzen",
      "species": "Cat",
      "visit": "Sick — decreased urination / weight loss workup",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "In-house CBC/chem + urinalysis",
      "notes": "Owner is a nurse — vet adapted communication accordingly ('we can use medical jargon'). Acknowledged sister cat's colon cancer history empathetically. Explained 10% body weight loss significance with lay comparison ('like me losing 20 lbs'). Systematically ruled out kidney disease (not drinking excessively), IBD (not vomiting frequently), and obstruction (bladder small on palpation). Compared current labs to 2-year-old baseline. Discussed MiraLAX management, Greenies limits (2/day for dental health with calorie awareness). Owner had Tuesday appointment with Dr. Hazy — vet coordinated care. Thorough, methodical workup.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/6685-transcript.txt"
    },
    {
      "id": "686999",
      "pet": "Samson",
      "species": "Cat",
      "visit": "Hospitalization — kidney disease / UTI / declining",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "IV hospitalization + IV antibiotics + fluids",
      "notes": "Complex case — 4th hospitalization since summer. Vet walked through CBC changes side by side (WBC doubled from 18K to 37K, neutrophils indicating infection). UTI identified as likely cause of rapid decline. Explained pyelonephritis mechanism. Realistic about prognosis: 'I can clear the infection, but then the question becomes where are our kidneys at.' Owner emotional but vet validated: 'you're taking excellent care of him, more than most people would.' Addressed owner's guilt about not catching sooner. Practical hospitalization: ICU placement for close monitoring, IV antibiotics for faster kidney delivery, fluid management adjusted for prior sub-Q at home. Owner's medications brought from home. Coordinated with prior treating vet.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/686999-transcript.txt"
    },
    {
      "id": "717511",
      "pet": "Lucy/Patty",
      "species": "Dog",
      "visit": "Recheck — giardia / bloody diarrhea",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Liquid metronidazole + fiber powder + stew diet + fluids",
      "notes": "Vet switched from pills (owner struggling) to liquid formulation — practical spectrum of care. Saved owner money by deferring X-ray: 'my gut is telling me let's not waste your money on that right now.' Addressed zoonotic risk (giardia contagious to humans — bleach surfaces). Switched from paste to fiber powder (owner reported dog hating paste). Changed prescription diet from pate to stew (owner noted dog liked Campbell's soup). Timeline set: 3 days for improvement, finish meds by Christmas Eve. Addressed upcoming puppy-sitting concern directly. Validated scared owner whose previous dog died similarly. Open 24/7 reminder given.",
      "badges": [
        "Pay / Lower-Cost Logistics"
      ],
      "takeaway": "The access move here is logistical: cheaper setting, send-out testing, or lower-cost follow-up.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": true,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/717511-transcript.txt"
    },
    {
      "id": "737",
      "pet": "Merlin",
      "species": "Cat",
      "visit": "Annual — licking rear / anal gland check",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Neosporin/Animax on scab area + vaccines",
      "notes": "Thorough exam: teeth (mild calculus, no gingivitis), ears, eyes, lymph nodes, abdomen, kidneys. Rectal exam performed to check anal glands (normal). Identified one mildly enlarged gland — expressed it. Recommended Animax over Neosporin for secondary infection prevention. Blood work from June still current. Prescription food refill (Blue Buffalo HF for allergies) handled. Owner mentioned cat allergic to treats — vet immediately noted treats shouldn't have been offered. Efficient, warm visit.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/737-transcript.txt"
    },
    {
      "id": "80608",
      "pet": "Toby",
      "species": "Dog",
      "visit": "Annual vaccines — fearful/reactive dog management",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "3-year rabies + distemper + Simparica Trio",
      "notes": "Fear-free visit management. Pre-visit trazodone + gabapentin at home. Vet offered two vaccine delivery options: owner holds head in room vs treatment area. Tried room first — succeeded with heavy treat distraction. 3-year rabies chosen to minimize future visits. Fecal sent out. Positive reinforcement throughout. Nail trim attempted after vaccines. Collaborative tech-vet approach with reactive dog. Brief but effective.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/80608-transcript.txt"
    },
    {
      "id": "814214",
      "pet": "Zelda",
      "species": "Dog",
      "visit": "Phone call — mast cell tumor pathology results",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Biannual rechecks + monitoring",
      "notes": "Delivered mast cell tumor diagnosis with appropriate context: 90% controlled by surgical excision (already done), 10% metastasize. Subcutaneous type explained. Recommended biannual exams (every 6 months). Additional testing pending (1-6 days). Reassuring but realistic: 'I feel pretty confident we won't have to worry again, but these things can do as they please.' Stitches removal scheduled. Clear, concise phone delivery.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/814214-transcript.txt"
    },
    {
      "id": "9109",
      "pet": "Grimm",
      "species": "Dog",
      "visit": "Ear infection + paw licking / allergies",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "Claro ear medication + paw wipes",
      "notes": "Stepwise allergy management. Ear: Claro (lasts 2 weeks, no home treatment needed — '9 out of 10 times it works'). Paws: baby wipes or medicated wipes after outdoor time (least invasive first), then Cytopoint injection or Apoquel if needed. Explained itch-lick-bacteria cycle clearly. Owner mentioned other dog with same symptoms — vet connected to seasonal allergies and offered same approach. Ear swab performed in-room. Large dog (Great Dane) managed with treat distraction. Warm, practical.",
      "badges": [
        "Staged Tradeoff"
      ],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": true,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/9109-transcript.txt"
    },
    {
      "id": "9639",
      "pet": "Minnie",
      "species": "Dog",
      "visit": "Recheck — vaccine site reaction / pain management",
      "firstRecommendationAccepted": true,
      "firstRecommendation": "NSAID (Rimadyl) + continue gabapentin + Benadryl + sucralfate",
      "notes": "Thorough pain workup for vaccine reaction. Vet explained steroid masking effect (reaction appeared after steroid wore off at 72 hours). Offered multimodal pain plan: NSAID for inflammation, gabapentin for nerve pain, Benadryl for histamine at injection site, sucralfate to protect stomach during NSAID/steroid transition. Range of motion tested — good but tense. Connected prior neck bite scar to current nerve sensitivity. Massage encouraged. Ice recommended, heat discouraged during active inflammation. Owner knowledgeable (asked about massage, ice/heat, Zyrtec switching). Recheck in 5 days if not improving, 2 weeks if improving. Detailed, patient communication.",
      "badges": [],
      "takeaway": "Options were offered, but the visit does not strongly center on cost or decline management.",
      "tags": {
        "optionsOffered": true,
        "explicitMoneyLanguage": false,
        "explicitDeclineInquiry": false,
        "alternativeOnDecline": false,
        "payRelatedOption": false,
        "stagedTradeoff": false,
        "pharmacySavings": false,
        "riskExplained": false,
        "minimumResponsible": false,
        "noOptionButAppropriate": false,
        "representative": false,
        "barrierDetected": false
      },
      "transcriptPath": "3-8-jason.szumski copy/Transcripts/9639-transcript.txt"
    }
  ]
};
