window.ANDY_ANALYSIS_BATCH17 = (() => {
  const rows = `
218054|Blue|Dog|Pancreatitis flare kept on a supportive outpatient path|1|The veterinarian kept a recurrent pancreatitis dog on a supportive outpatient path instead of reopening a large expensive workup.|The discussion centered on anti-nausea medication, fluids, probiotics, low-fat diet, stomach-safe pain control, and stopping the likely trigger antibiotic.|staged,risk,nooption
218345|Isabella|Dog|Wellness and vaccine visit with vaccine-reaction planning but no live fork|1|This was mainly preventive care with a small medication-prevention aside rather than a live options case.|The conversation stayed on vaccines, prior reactions, grain-free counseling, and general wellness without a meaningful affordability or care-spectrum decision.|nooption
220681|Braxton|Dog|Addisonian recheck using dose timing refinement and one more checkpoint|1|The veterinarian treated this as a known endocrine management case with a small scheduling refinement rather than a broader choice set.|The discussion stayed on splitting the daily dose, rechecking electrolytes once more, and then transitioning to routine monthly maintenance.|staged,nooption
220745|Roxy and Calvin|Dog|Chronic myositis management and vaccine restraint in a two-dog visit|1|The veterinarian built a pragmatic chronic-management plan and avoided over-stimulating an immune-mediated dog.|The discussion covered rabies-only vaccination, prednisone continuation, bloodwork, and the option of getting the medication through a human pharmacy.|options,pay,pharmacy,staged,risk,rep
220816|Bella boo|Dog|Glucosuria workup kept stepwise with Fanconi testing first|1|The veterinarian kept the unusual urine finding on a stepwise diagnostic track instead of jumping straight to treatment.|The discussion compared rare Fanconi testing against later diet or supplement acidification and included sending an estimate before running the specialized test.|options,money,staged,risk,rep
220879|Bruno|Dog|Kennel-cough visit managed conservatively with thresholds for doing more|1|The veterinarian used a conservative viral-kennel-cough plan while naming the thresholds that would justify doing more.|The discussion included cough tablets, cerenia, bland diet or bland dog food, harness use, and optional calming medication if the dog could not rest.|options,staged,risk,min
220904|Bruno|Unknown|Fragmentary aggression intake without a usable treatment sequence|1|This file does not preserve enough of a coherent visit to code a meaningful spectrum-of-care conversation.|The capture is mostly fragmentary intake around aggression and possible neutering or bloodwork without a full recommendation sequence.|nooption
221058|Huckelberry|Cat|Outdoor-cat wellness visit with vaccines and parasite prevention|1|This remained a preventive visit with only light parasite-prevention counseling rather than a real options case.|The conversation stayed on vaccines, calorie guidance, and Bravecto logistics for an outdoor cat.|nooption
221075|Annie|Cat|Hindlimb-pain visit using x-rays first with explicit pricing|1|The veterinarian kept the plan stepwise and priced the first move clearly instead of widening the workup immediately.|The discussion focused on x-rays, pain medication, and the possibility of a clot or orthopedic issue, with explicit exam, x-ray, and medication pricing.|money,staged,risk,nooption
221259|Frankie|Dog|GI upset after possible foreign material managed with optional imaging|1|The veterinarian weighed imaging against conservative GI care and stayed outpatient because the history still fit stomach upset more than obstruction.|The discussion compared x-rays now versus metronidazole, probiotic support, bland diet, and GI Biome later if the diarrhea did not turn around.|options,staged,risk,rep
221338|Hinger|Dog|Endocrine callback about regulation and dose adjustment|1|This was a straightforward chronic-disease check-in rather than a live treatment-branch conversation.|The discussion stayed on regulation, timing, appetite, and the possibility of increasing the dose after the next recheck.|staged,nooption
221466|Riko|Dog|Torn dewclaw managed conservatively instead of immediate removal|1|The veterinarian chose the least invasive workable path once the dewclaw looked closed enough to heal on its own.|The discussion contrasted removing the torn nail versus leaving it, then used cleaning, antibiotics, cone use, and simple follow-up.|options,staged,risk,min
221626|Jax|Dog|Red-eye visit sorted with stain-first logic and medication choice|1|The veterinarian sorted ulcer risk first and then steered the owner to the easier medication route even though it cost more.|The discussion covered bacterial versus allergic conjunctivitis, ruling out a corneal cut, choosing drops over ointment for ease, and noting the drops were more expensive.|options,money,staged,risk,rep
221754|Zoey and Barney|Dog|Dry-eye, cherry-eye, and dental-support choices in a two-dog visit|1|The veterinarian offered practical management options while being honest that surgery and ongoing eye care may still be needed.|The discussion covered dental chews versus water additives, alternate eye medications, ear cleaning, and a cherry-eye surgery consult with cost skepticism named directly.|options,money,staged,risk
222035|Lily|Dog|Abdominal-mass discovery handled with stepwise and affordability-aware triage|1|The veterinarian respected the owner's financial ceiling and started with the most informative first test before landing on palliative management.|The discussion contrasted supportive care versus x-rays, surfaced the owner's CareCredit limits, and then moved to outpatient anti-nausea, pain, and hemostatic support after the cavitated abdominal mass was found.|options,money,staged,risk,rep
222136|Shiloh|Cat|Post-catheter urinary irritation managed conservatively with future surgery named|1|The veterinarian treated the current episode conservatively while planting the longer-term surgical option if the pattern recurs.|The discussion covered switching pain support to gabapentin, adding a bladder-wall supplement, and explaining a PU surgery for recurrent obstruction risk.|options,staged,risk
222175|Delta dawn|Dog|Itchy skin and ears treated around a handling barrier|1|The veterinarian adapted the itch plan to what the dog and owners could actually administer rather than insisting on pills or drops that would fail.|The discussion contrasted pills with an itch-control injection, topical ear medication, warm compresses for the eyes, and the practical limits of treating a very handling-averse dog.|options,staged,barrier
222185|Bailey|Dog|Clear allergic reaction treated on a direct emergency track|1|The veterinarian did not broaden the case because the treatment path was already clear.|The discussion focused on epinephrine, Benadryl, steroid support, and monitoring for worsening swelling or breathing changes.|staged,risk,nooption
222231|Bear|Dog|Routine puppy vaccine visit without a meaningful options branch|1|This was preventive care rather than an affordability or alternatives conversation.|The discussion stayed on vaccines, heartworm testing, and ordinary puppy wellness.|nooption
222255|Mia|Dog|Corneal ulcer visit narrowed to repair-focused eye treatment|1|The veterinarian used the stain result to narrow the eye plan and protect healing.|The discussion identified a sizable corneal ulcer, then used pain medication, ocular gel, antibiotic ointment, cone use, and recheck timing instead of the more aggressive drops reserved for non-ulcer cases.|options,staged,risk,rep
222434|Gracie|Dog|Post-diarrhea recovery managed with probiotic reset first|1|The veterinarian kept the case low intensity and used a microbiome reset before moving to anything more aggressive.|The discussion centered on a probiotic-plus-fiber kit, watchful follow-up, and GI Biome later if the stool failed to normalize.|options,staged,min
222553|Akira|Cat|UTI treatment using first-line antibiotics with culture reserved next|1|The veterinarian used standard first-line treatment and made the culture decision explicit rather than hiding it.|The discussion compared starting amoxicillin now versus sending a culture, added cranberry support, and explicitly priced the antibiotic.|options,money,staged
222693|Skipper|Dog|Kennel-cough versus foreign-body concern sorted with imaging|1|The veterinarian used imaging to rule out the scary story, then kept the treatment on a typical kennel-cough track.|The discussion compared wrapper ingestion concern against kennel cough, used chest and abdominal x-rays to rule out foreign material and pneumonia, and sent home cough tabs plus cerenia.|options,staged,risk,rep
222739|Reni|Dog|Wellness and dental-planning visit with urinary-diet maintenance|1|This was mostly maintenance care with a small planning branch for dental timing and urine-safe diet continuation.|The discussion stayed on continuing the urinary diet, pre-op bloodwork for a future dental, and a new prescription for the canned food.|staged,nooption
223020|Fiona|Dog|Ascites workup moved from x-rays to tap and specialist ultrasound|1|The veterinarian was transparent about uncertainty and advanced the case one informative step at a time.|The discussion covered abdominal fluid, inflammatory-cell analysis, ruling out obvious organ causes, draining the fluid, and referral for a specialist ultrasound.|options,staged,risk,rep
223124|Lola|Dog|Senior decline and incontinence workup with practical first steps|1|The veterinarian framed the likely incontinence cause clearly while still building in metabolic screening for the dog's broader decline.|The discussion compared UTI versus sphincter incontinence, explained the medication trial logic, and contrasted in-house bloodwork against waiting for outside results.|options,money,pay,staged,risk,rep
223155|Fabio|Dog|Male-dog UTI treated with first-line antibiotics and environmental adjustments|1|The veterinarian kept the case practical and tied the management plan to likely bladder irritation rather than overcomplicating it.|The discussion covered antibiotics, cranberry support, and switching from paper litter to pee pads because the current setup may be contributing to irritation.|options,staged
223664|A|Dog|Two-dog wellness visit with a small cost aside around rabies duration|1|This was mostly preventive care, with only a brief low-stakes branch around wound aftercare and the one-year versus three-year rabies choice.|The discussion stayed on routine vaccines, minor facial scuffle wounds treated with Neosporin, and a lower-cost one-year rabies option that the owners declined.|money,nooption
223665|Boo|Dog|End-of-life crisis visit where euthanasia displaced futile escalation|0|The veterinarian was direct that further workup would not realistically change the outcome and pushed humane euthanasia over futile escalation.|The discussion contrasted expensive workup for peace of mind against immediate euthanasia in a profoundly unstable geriatric dog whose body appeared to be shutting down.|options,money,staged,risk,rep
223895|Lily|Cat|CKD nutrition consult prioritized calories over diet purity|1|The veterinarian prioritized actual eating over diet purity and offered several kidney-tolerable food options.|The discussion weighed Tiki Cat, Friskies, and OncCare against more traditional kidney diets while explaining phosphorus and protein tradeoffs in chronic kidney disease.|options,staged,risk
223985|Ellie|Dog|Routine wellness visit with only minor chronic-eye guidance|1|This was a routine preventive visit with only minor maintenance guidance around chronic eye flare-ups.|The discussion stayed on vaccines, nail-trim guidance, and using the existing eye medication as needed for redness or discharge.|nooption
224124|Max|Cat|Senior-cat wellness visit with maintenance bloodwork and dental planning|1|The veterinarian stayed in maintenance mode while using the visit to tighten long-term monitoring and low-intensity dental support.|The discussion covered air-purifier benefit, choosing a one-year rabies shot, dental treats versus later cleaning, and updated bloodwork because the cat had lost weight.|staged,nooption
224148|Katie|Dog|Routine vaccine and prevention visit without a real treatment fork|1|This was a straightforward wellness encounter.|The discussion stayed on vaccines, heartworm screening, and ordinary preventive care.|nooption
224180|Jax|Dog|Recurrent tooth-root abscess bridged medically while extraction was weighed|1|The veterinarian was honest that the only definitive fix was extraction, but still built a temporary bridge with antibiotics and pain control.|The discussion covered abscessed tooth removal, fear of anesthesia, starting carprofen, and giving a dental estimate with low and high ends.|options,money,staged,risk,rep
224206|Ghost|Dog|IMHA-type recheck with slow taper and boarding logistics|1|The veterinarian kept the plan deliberately slow and used the recheck to set up practical medication and boarding logistics.|The discussion centered on gradually tapering prednisone, refilling a drug via outside pharmacy if needed, and arranging medical boarding with quoted rates while the owner traveled.|options,pay,staged,risk,rep
225492|Luna|Dog|Staple-removal recheck after surgery without new branching|1|This was a clean postoperative recheck rather than a new options discussion.|The conversation stayed on healed scabs, Lyme vaccine update, and ordinary heartworm follow-up.|nooption
225581|Luna|Cat|End-of-life consult narrowed to comfort care versus euthanasia|0|The veterinarian narrowed the realistic choices to comfort medications for a little more time versus euthanasia.|The discussion contrasted appetite stimulant and anti-nausea support against letting a declining cat go rather than waiting for starvation or doing major intervention.|options,staged,risk,rep
225721|Samantha|Cat|Two-cat ear and asthma follow-up tailored to administration realities|1|The veterinarian tailored the plan to the owner's administration preferences and tried to avoid unnecessary extra handling visits.|The discussion covered refrigerated ear drops, whether to stay on oral pred versus transition to inhaled fluticasone later, and giving the pending vaccine today to avoid another stressful visit.|options,staged,risk
225832|Zoey|Dog|Constipation-like GI discomfort kept on a low-intensity outpatient path|1|The veterinarian used imaging to keep the case on a low-intensity outpatient path.|The discussion linked the signs to mild constipation or gut discomfort, then used fluids, anti-nausea treatment, and bland feeding without opening a larger workup.|staged,risk,min,nooption
225912|Stella|Dog|Puppy wellness visit with routine vaccine and spay timing guidance|1|This was preventive care rather than an options-heavy case.|The discussion stayed on remaining puppy vaccines, age-appropriate spay timing, and ordinary feeding guidance.|nooption
226201|Oreo|Cat|Post-fluoxetine urinary concern kept on conservative home monitoring|1|The veterinarian avoided unnecessary catheterization because the cat was not blocked and still fit close outpatient observation.|The discussion compared hospitalization and catheter-level intervention against going home with bladder-support supplements and strict observation while the medication effect wore off.|options,staged,risk,rep
226554|Chiffon|Dog|Patchy flank alopecia worked up with thyroid testing before melatonin|1|The veterinarian kept the alopecia workup ordered and low intensity before calling it a purely cosmetic syndrome.|The discussion covered bilateral flank alopecia, hypothyroidism screening, and a six-week melatonin trial if the thyroid workup stayed normal.|options,staged
226636|Roxy and Calvin|Dog|Heartworm-treatment planning built around medication-access logistics|1|The veterinarian translated heartworm treatment into a manageable ninety-day sequence and offered multiple ways to access the medication.|The discussion walked through doxycycline plus prevention, then laid out online shipment versus filling locally before the staged adulticide injections.|options,pay,staged,risk,rep
226740|Louis|Dog|Routine preventive visit with no real care-spectrum branch|1|This remained a maintenance encounter.|The discussion stayed on vaccines, prevention, and ordinary low-risk wellness decisions.|nooption
226830|Wick|Dog|Chronic itchy-ear flare managed by treating the bigger allergy pattern|1|The veterinarian treated the bigger problem as overall itchiness and chose the safer long-term injection over heavier systemic suppression.|The discussion covered Cytopoint versus Apoquel, coconut oil for dry pinnae, and practical ways to hide monthly preventives in food.|options,staged,risk
226895|Daisy|Dog|Weight-loss and lump concern resolved into benign reassurance|1|The veterinarian used charted weight and aspirate logic to show that the feared decline was more body-composition change than real weight loss.|The discussion focused on stable weight, aspirating the lump to confirm a lipoma, and reviewing prior bloodwork rather than opening a broader diagnostic tree.|nooption
227100|Greta|Dog|Dog-bite abdominal wound discussed with low-versus-high estimate framing|1|The veterinarian clearly framed the difference between a straightforward wound repair and a much bigger abdominal contamination problem.|The discussion covered sedation, possible abdominal-wall entry, lavage, drain placement, pain meds, antibiotics, and a low-to-high estimate depending on what surgery found.|options,money,staged,risk,rep
227348|Coco|Dog|Mild low-energy wellness visit kept proportional with bloodwork first|1|The veterinarian kept the concern proportional while still checking thyroid and organ function before calling it simple weight gain.|The discussion paired wellness vaccines with a send-out panel and conservative dental-brushing advice instead of jumping straight to another cleaning.|options,staged
227577|Toby|Dog|Vestibular and dry-eye discussion tied to inner-ear disease|1|The veterinarian tied the eye and balance signs together and built a practical treatment path without pretending the diagnosis was simple.|The discussion linked the facial and vestibular signs to possible inner-ear disease, added tear-stimulating drops plus lubricant, and revisited the value of antibiotics and next-step imaging.|options,staged,risk,rep
227709|Lilly|Dog|Forelimb limp managed by comparing NSAID strategies after x-rays|1|The veterinarian kept the case non-catastrophic after x-rays and used bloodwork to decide whether a stronger cheaper NSAID could replace Galliprant.|The discussion ruled out bone lysis, discussed increasing Galliprant versus washing out and switching to Rimadyl, and explicitly noted the cheaper medication path.|options,money,staged,risk,rep
227804|Mordecai|Dog|Odd thigh mass concern treated as asymmetry first, MRI later only if needed|1|The veterinarian resisted calling asymmetry a tumor before the sample actually supported it.|The discussion covered aspirating the area, measuring both thighs, and using anti-inflammatory support and monitoring before any advanced imaging.|options,staged
227912|Periwinkle|Cat|Chronic coughing finally moved to inhaled-asthma management|1|The veterinarian used x-rays to confirm asthma and shifted the long-term plan toward the safer inhaled route.|The discussion contrasted oral steroids against an AeroKat plus fluticasone inhaler, with optional room air purification as an environmental assist.|options,staged,risk,rep
227971|Lily|Dog|Routine vaccine and screening visit without a substantive branch|1|This was a straightforward preventive visit.|The discussion stayed on vaccines, heartworm testing, fecal screening, and normal exam findings.|nooption
228447|Mia|Dog|Corneal-ulcer recheck showing healing and short extension of ointment|1|This was a clean healing recheck rather than a new care-spectrum discussion.|The discussion stayed on finishing a few more days of ointment and confirming the eye had healed without scarring.|nooption
229082|Riley and Brody|Dog|Two-dog wellness visit where the meaningful issue was dental worthwhileness|1|The veterinarian identified the likely reason the older dog was skipping meals and framed the dental estimate transparently.|The discussion found two dead lower canines, explained anesthesia timing and estimate ranges, and otherwise kept the visit in routine-wellness territory.|options,staged,risk
229160|Hayley|Dog|Routine vaccine and screening visit with no treatment alternatives branch|1|This was preventive maintenance only.|The discussion stayed on vaccines, weight counseling, and normal annual care.|nooption
229204|Bo|Dog|Spinal-recovery follow-up using medication wean instead of MRI reflex|1|The veterinarian kept the recovery plan pragmatic and adjusted meds based on function instead of reflexively escalating diagnostics.|The discussion centered on stopping methocarbamol, tapering Rimadyl, continuing gabapentin, and sending a more complete thyroid panel to distinguish true disease from euthyroid sick.|options,staged,risk,rep
229273|Simon|Cat|Geriatric weakness visit turned into a clear kidney-crisis plan|1|The veterinarian used in-house labs to turn a vague weakness story into a clear kidney-crisis plan with realistic chronic management afterward.|The discussion covered kidney failure, anemia, blood-pressure elevation, hospitalization with fluids and monitoring, then long-term phosphate binders, subcutaneous fluids, and kidney diet if the cat stabilized.|options,staged,risk,rep
236082|Mandy|Dog|Likely kennel cough discussion where observation stayed primary|1|The veterinarian treated the case like classic mild infectious tracheitis and resisted antibiotics.|The discussion focused on watching for yellow-green discharge or lethargy, optional nighttime cough tablets, and letting daytime coughing clear the throat naturally.|options,staged,min
236187|Greta|Dog|Postoperative drain-removal recheck without a new branch|1|This was a clean healing check rather than an options case.|The discussion stayed on drain removal, cone continuation, and scheduling stitch removal.|nooption
236396|Cooper|Dog|IVDD medical-boarding intake without a new recommendation fork|1|This file is mainly logistics around known spinal disease and boarding, not a fresh care-spectrum discussion.|The conversation centered on current meds, residual deficits, and ensuring the dog was safe for medical boarding.|nooption
236505|Thor|Cat|Biannual exam with routine bloodwork and mild ear debris|1|This was a maintenance visit.|The note is essentially a short summary of routine bloodwork and minor ear debris in an otherwise stable cat.|nooption
236663|Charlie|Dog|Puppy wellness visit with potty-training coaching|1|This was a preventive puppy visit with behavior guidance.|The discussion stayed on vaccines, potty-training timing and rewards, and routine puppy care.|nooption
236822|Eiger|Dog|Anxious itchy-dog wellness visit built around practical handling limits|1|The veterinarian kept the visit practical and chose an itch-control plan that fit the dog's handling limits.|The discussion covered food trials, Cytopoint, keeping the current previsit-med protocol because it worked, and giving the needed vaccines in a modified exam.|options,staged,barrier
236842|Loki|Cat|Normal recheck call on screening bloodwork|1|This was a reassuring lab-results call.|The discussion stayed on normal bloodwork, normal thyroid, and low concern for zoonotic spread.|nooption
237566|Murphy|Dog|Chronic hacking cough handled as tracheitis first with fallback theories|1|The veterinarian treated the cough like chronic tracheitis or collapse first but still widened the workup because the muscle wasting did not fit cleanly.|The discussion covered chronic tracheitis versus collapse, bloodwork with thyroid testing, Temaril-P tapering, and possible omeprazole later if reflux still looked likely.|options,staged,risk,rep
237959|Mia|Dog|Vomiting-and-pain visit where x-rays beat pure supportive care|1|The veterinarian used the pain on palpation to justify imaging before settling on supportive care.|The discussion contrasted stomach-upset supportive care against x-rays to rule out something more serious while keeping pancreatitis high on the list.|options,staged,risk,rep
238003|Zoe|Dog|Conjunctivitis visit where a hair in the eye dictated gentler care|1|The veterinarian used stain-and-flush logic to avoid overtreating a straightforward irritated eye.|The discussion covered checking for an ulcer, flushing out a hair, and using a short course of drops because the problem was irritation rather than a deeper injury.|staged,min,nooption
238042|Loki|Cat|Normal bloodwork callback without a treatment branch|1|This was a straightforward results call.|The discussion stayed on normal CBC, chemistry, thyroid, and reassurance.|nooption
242481|Juice|Unknown|Internal postoperative discussion rather than an owner-facing visit|1|This is not a usable exam-room owner conversation for nuanced care-spectrum coding.|The file reads like internal clinician discussion around a postoperative scrotal complication rather than a standard owner-facing visit.|nooption
242507|Iggy Mae|Dog|Pathology-results call after removal of low-grade soft tissue sarcomas|1|The veterinarian used the results call to reassure the owner while still naming the small residual-monitoring issue honestly.|The discussion covered grade-one sarcomas, clean margins, and simply watching the area over time rather than doing anything more aggressive now.|nooption
242559|Cash|Dog|Interdigital skin lesions managed as allergy-driven disease first|1|The veterinarian treated the feet like allergy-driven skin disease with secondary infection instead of overcomplicating it.|The discussion covered whether topical therapy might beat oral antibiotics, restarting Apoquel, and considering Cytopoint only if the current plan kept failing.|options,staged,risk
242642|Quinn|Dog|CKD-gastroparesis flare kept on a familiar conservative regimen|1|The veterinarian kept the stomach-upset flare on a familiar conservative regimen rather than widening the workup immediately.|The discussion centered on restarting metoclopramide and adding omeprazole for acid and motility support.|staged,nooption
242667|Pixie|Cat|Spay-suture recheck and marking behavior kept on home management|1|The veterinarian kept both issues on a low-intensity home-management track.|The discussion covered removing the external stitches, warm compresses over a likely inflammatory thickening, Feliway on the marked spots, and pushing the booster to a proper tech-visit window.|staged,min,nooption
242731|Clark|Dog|Anal-area licking visit paired with staged dental-planning costs|1|The veterinarian treated the perianal irritation directly while also framing a likely slab-fracture dental as a future staged procedure.|The discussion covered Apoquel, fish oil, topical anti-itch cream, possible anal-gland contribution, and an estimated dental cost with likely extraction.|options,money,staged
243045|Maggie|Dog|Diabetic follow-up kept data-first before changing insulin|1|The veterinarian kept the poorly regulated diabetic on a data-first path instead of adjusting insulin blindly.|The discussion centered on persistent PUPD and poor appetite, sending fructosamine and screening tests, and planning to use a Freestyle Libre plus larger syringes for likely dose adjustment.|options,staged,risk
243574|Tonya|Dog|Mild spring itchiness matched with low-intensity first steps|1|The veterinarian matched the treatment intensity to how mild the allergy signs still looked.|The discussion contrasted Cytopoint and Apoquel, explained why antihistamines were unlikely to help much, and suggested wiping pollen off the paws before escalating.|options,staged,min
243669|Javier|Dog|Pancreatitis concern handled by pricing the one test that would change care|1|The veterinarian balanced cost and severity by picking the one targeted test that would actually change whether home care was still safe.|The discussion contrasted another round of supportive care against a quantitative pancreatic lipase test, explicitly priced the test, and explained how a very high result would justify hospitalization.|options,money,staged,risk,rep
243797|Giitu|Dog|Routine rabies-only visit without a meaningful treatment branch|1|This was a simple maintenance encounter.|The discussion stayed on the rabies vaccine and future tech-appointment timing.|nooption
243859|Oreo|Dog|Chronic ear disease and evening anxiety treated as linked management issues|1|The veterinarian treated the ear and behavioral problems as overlapping chronic-management issues rather than one-off complaints.|The discussion covered fish-oil support, switching to a novel-protein wet diet before prescription hydrolyzed food, keeping the cleaner schedule, and using trazodone or even CBD if the evening panic episodes worsened.|options,staged,risk,rep
244199|Jimbo and Bentley|Dog|Routine French-bulldog puppy visit with training advice|1|This was mostly preventive puppy care.|The discussion stayed on vaccines, deworming and fecal follow-up, socialization, leash training, and ordinary Frenchie puppy guidance.|nooption
244500|Ellie|Dog|Skin-issue visit treated as chronic allergy with secondary infection|1|The veterinarian treated the problem as chronic allergy skin disease with secondary infection, not a mystery lesion.|The discussion covered peri-lip-fold irritation needing oral antibiotics, Cytopoint restart, ear-cleaner support, and topical Neosporin for the tip of the ear.|options,staged
244580|Ellee|Dog|Two-dog visit where the diarrhea case stayed on simple outpatient support|1|The veterinarian treated the GI upset as self-limiting and did not widen the case because the dog still looked well.|The discussion stayed on a diarrhea kit with probiotic and fiber for Minnie, while the weight-loss success in Ellie remained a positive wellness point.|staged,min,nooption
244858|Fabio|Dog|Post-UTI follow-up shifted into prevention and refill logistics|1|The veterinarian used the clean urine recheck to shift the conversation from treatment to practical prevention.|The discussion covered cranberry supplements, dental products, and specific six-pack pricing and online-pharmacy logistics for ongoing Revolution refills.|options,money,pay
245015|Dewey|Dog|Anal-gland concern reframed with diet and surgery as last resort|1|The veterinarian reframed the owner's main fear by explaining that the frequent expression was abnormal but probably not painful, then laid out the realistic options.|The discussion covered why anal glands are not functionally important, a possible gland-removal surgery, and trying an expensive ZD plus ActiveBiome diet before making that jump.|options,money,staged
245059|Sosa|Dog|Spinal-pain flare handled with the safest high-yield home medications|1|The veterinarian kept the flare management focused on the safest, highest-yield medications rather than reflexively stacking sedating agents.|The discussion covered continuing gabapentin, using Rimadyl during flare-ups, and saving methocarbamol for more selective use because it clouds the clinical picture.|options,staged,risk
245679|Lola|Dog|Fragmentary internal ear and diarrhea capture without a full plan|1|The file is too fragmented to support a reliable full care-spectrum code beyond noting a relatively minor outpatient issue set.|The visible content suggests mild yeast-ear management and transient diarrhea, but the actual recommendation sequence is incomplete.|nooption
245760|Jeanne|Cat|Two-cat wellness visit with only mild dental and vaccine timing choices|1|This stayed in preventive maintenance territory.|The discussion focused on bloodwork, one cat's likely future dental, and whether to do a vaccine now or at the next visit to minimize repeat handling.|nooption
246003|Oreo|Dog|Normal-results callback after airway concern without a new plan fork|1|This was a reassuring follow-up call.|The discussion stayed on normal bloodwork, negative heartworm, a pending fecal, and simple home steam and supportive monitoring.|nooption
246178|Lloyd|Cat|Chronic out-of-box urination moved toward maintenance anti-anxiety care|1|The veterinarian moved from symptomatic calm-down medication to a real anti-anxiety maintenance plan aimed at keeping the cat in the home.|The discussion covered restarting treatment with fluoxetine instead of gabapentin, choosing fish flavor, increasing the dose if needed, and using the cheaper shipped option for the medication.|options,money,pay,staged,rep
246250|White paws|Cat|Diabetic cat with gait issue managed as pain or neuropathy first|1|The veterinarian ruled out the immediate diabetic emergencies and then treated the remaining problem like neuropathy or soft-tissue pain.|The discussion covered normal blood sugar and ketones, explained why diabetic ketoacidosis was not happening, and used gabapentin in a way that would not interfere with the next day's follow-up exam.|options,staged,risk,rep
246261|Ghost|Dog|IMHA-type recheck with careful taper and new pain-control discussion|1|The veterinarian kept the immune-disease plan moving down slowly while separately considering pain control for a new gait issue.|The discussion covered reducing prednisone in a cost-effective way, watching soft stool, and separately debating gabapentin versus other pain control for a possible strain or neuropathy-like gait problem.|options,staged,risk
248753|Fonzie|Unknown|Internal surgical dictation rather than an owner-facing conversation|1|This is an operative note, not a usable owner-facing exam-room transcript for the Andy coding questions.|The file is a pure surgery narrative describing exploratory work and foreign-body removal.|nooption
255727|Rednesss|Dog|Two-dog vaccine and eye-recheck visit with a longer drop course|1|The veterinarian treated the persistent post-boarding conjunctivitis as an incompletely cleared routine infection rather than a bigger diagnostic mystery.|The discussion covered switching to a different eye drop for a full week, considering Zyrtec if the eyes keep flaring, and otherwise staying in routine wellness territory.|options,staged
255848|Murphy|Dog|Chronic cough escalated to pneumonia with explicit hospitalization pricing|1|The veterinarian moved decisively once the repeat x-rays and fever showed the case had crossed from chronic nuisance cough into real pulmonary disease.|The discussion compared aspiration, bacterial, parasitic, and fungal pneumonia, recommended hospitalization with IV antibiotics and fungal testing, stopped Temaril-P, and explicitly priced the first 24 hours of care.|options,money,staged,risk,rep
255986|Ayu|Cat|Ear-recheck plan widened toward food change and home cleaning|1|The veterinarian treated the partial response as progress and widened the long-term plan toward food rather than reflexively changing medications immediately.|The discussion covered giving Claro another week, then weekly ear cleaning with gabapentin support, and switching to a fish-based sensitive skin and stomach diet.|options,staged,risk
256050|Leo|Dog|Hacking tracheal-cough visit managed medically before imaging|1|The veterinarian treated the problem like classic tracheal irritation or collapse and resisted imaging unless the cough persisted through medication.|The discussion covered hydrocodone syrup, harness adjustment, when x-rays might still be worth it, and how dental disease and anesthesia planning fit later rather than today.|options,staged,risk,rep
256235|Oliver|Cat|Chronic URI cat kept on the familiar injection-and-support path|1|The veterinarian kept the chronic URI cat on the familiar injection-and-support path while also addressing pain as a contributor to new behavior changes.|The discussion covered repeating the long-acting antibiotic, continuing lysine and MiraLAX, adding gabapentin for likely pain, and draining a benign tail cyst.|options,staged,risk,rep
256396|Harvey|Dog|Acute limb and back pain sorted with x-rays before rest and analgesia|1|The veterinarian used radiographs to make sure the painful presentation was not a fracture, then treated the problem like a musculoskeletal flare.|The discussion covered possible back pain versus wrist injury, x-rays of both forelimbs, identifying arthritis rather than a break, and starting Rimadyl plus gabapentin with rest.|options,staged,risk,rep
256508|Riley|Cat|Post-obstruction recheck with medication wean and surgery fundraising talk|1|The veterinarian used the good recheck to start peeling away temporary meds while explaining why a PU surgery would still change the cat's long-term future.|The discussion covered stopping bethanechol first, finishing antibiotics, staying on the SO diet, and realistically talking through a GoFundMe for the corrective surgery.|options,staged,risk,rep
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected',
    alternativeOnDecline: 'alternativeOnDecline'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 17',
      date: '2026-03-19',
      selectionSeed: '20260319-wave17',
      selectionMethod: 'Seventeenth non-overlapping 100-transcript backlog batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1600_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
