window.ANDY_ANALYSIS_BATCH11 = (() => {
  const rows = `
43544|Murphy|Dog|New-dog establishment visit with vaccine update and neuter estimate|1|This was mostly a routine establishment visit with practical planning rather than a real care-options conversation.|The discussion centered on overdue vaccines, microchip transfer, luxating-patella education, and a neuter estimate for later scheduling.|money,nooption
43655|Vivi and Willow|Cat|Routine dual-cat vaccine visit with lip-lesion reassurance on a third cat|1|This was a preventive visit where alternatives were not really the issue.|The encounter focused on normal exams, rabies and FVRCP vaccines, and reassurance that another cat's lip lesion likely self-resolved.|nooption
43723|Yoda|Dog|Ear-infection visit with direct treatment and blood-blister monitoring|1|The veterinarian used straightforward treatment without needing to build a larger option set.|The plan was deep ear cleaning, five days of ear medication, and watchful monitoring of a small blood blister that was left alone unless it enlarged.|min,nooption
43792|Jack|Dog|Annual exam with feeding questions and routine prevention refills|1|This was a wellness visit with feeding guidance and prevention refills, not a true options discussion.|The encounter focused on annual care, diet questions, and prevention refills rather than on staged treatment choices.|nooption
44339|Kat|Cat|Post-URI vaccine follow-up with spay-planning sheet|1|This was a recovering URI follow-up and vaccine visit where alternatives were not really the issue.|The veterinarian updated core vaccines, gave a spay-pricing sheet, and noted only mild residual sneeze with otherwise normal recovery.|nooption
44418|Cash|Dog|Vaccine catch-up visit with one-year versus three-year rabies choice|1|The veterinarian made the vaccine plan explicit around the owner's preference for lower upfront cost.|The discussion compared one-year versus three-year rabies pricing and paired the selected annual vaccines with later fecal submission rather than forcing everything into one visit.|options,money,pay,staged,min
44470|Kiwi|Dog|Record-transfer wellness visit with urine-sample instructions|1|This was mostly a record-transfer wellness visit rather than an options conversation.|The veterinarian focused on obtaining outside vaccine records, planning the right vaccine interval, and explaining how to collect a urine sample at home.|nooption
44503|Pi|Dog|Chronic forelimb limping visit with x-ray versus anti-inflammatory trial|1|The veterinarian separated fracture concern from soft-tissue pain and offered a clear conservative-versus-imaging branch.|The discussion contrasted x-rays against a short anti-inflammatory trial and explained why the gait looked more like overuse or conformational strain than a true break.|options,staged,risk,min,rep
44645|Jacob|Dog|Vaccine catch-up with cost breakdown and future dental planning|1|This was a strong example of price-aware preventive planning without hiding the medical logic.|The veterinarian broke out which vaccines mattered most, dropped an unnecessary heartworm test after confirming recent results, and prepared the owner for future dental extraction needs.|options,money,pay,staged,risk,rep
45103|Murphy|Dog|Lepto timing and neuter planning for a new dachshund patient|1|The veterinarian handled vaccine hesitancy by giving a manageable timing plan instead of forcing the issue.|The discussion framed Lepto as medically important, explained reaction management with Benadryl, and coordinated later vaccine timing with neuter and microchip planning.|options,money,staged,risk
45104|Murphy|Dog|Duplicate-like Lepto timing and neuter planning visit|1|This duplicate-like capture preserves the same cost-and-timing logic around Lepto and neuter planning.|The conversation again covered reaction risk, Benadryl premedication, and how to stage Lepto, neuter, and microchip decisions into easier visits.|options,money,staged,risk
45206|Jet|Dog|Anal-sac abscess rupture treated with flush and medications|1|This was an acute problem with a fairly fixed treatment path rather than a real options discussion.|The plan was treatment-area flushing, antibiotics, pain control, and expectation setting about short-term drainage from the ruptured sac.|nooption
47531|Oliver|Cat|Chronic wound setback with added second antibiotic and frequent rechecks|1|The veterinarian escalated care because the wound had improved and then slid backward, not because a broader spectrum of options was suddenly available.|The discussion added a second liquid antibiotic, more frequent rechecks, and practical medication-delivery adjustments for a cat that would not take pills.|staged,risk,barrier,nooption
47532|Oliver|Cat|Duplicate-like chronic wound setback with the same escalation plan|1|This duplicate-like capture reinforces the same wound-care escalation without introducing a new option set.|The discussion again used a second liquid antibiotic, close bandage changes, and owner-friendly medication form rather than a pill-based plan.|staged,risk,barrier,nooption
47564|Elsa|Dog|Senior wellness visit with resolving eye concern and blood-work follow-up|1|This was mainly a senior preventive visit rather than an options-heavy encounter.|The discussion focused on an eye concern that had already improved, routine senior blood work, and vaccine maintenance.|nooption
47618|Gracie|Cat|Feline herpes flare with antibiotic support only because fever was present|1|The veterinarian explicitly protected against unnecessary antibiotics while still treating the higher-risk version of the same syndrome.|The discussion explained that most herpes flares self-clear, justified the antibiotic because of fever, and added lysine plus later revaccination as the follow-up plan.|options,staged,risk,min,rep
47690|Missy|Dog|Hip soreness after likely household mishap with conservative pain-first plan|1|The veterinarian treated this like a soft-tissue injury unless the exam suggested something more severe.|The discussion favored fresh anti-inflammatory support and monitoring, with x-rays held in reserve because the dog was still weight-bearing and slowly improving.|options,staged,risk,min
47819|Ivy|Dog|New-adoption puppy wellness visit with Lepto counseling and growth expectations|1|This was mostly an education-heavy puppy visit rather than a real options conversation.|The veterinarian reviewed Lepto importance, stool follow-up, growth expectations, and routine puppy-prevention planning without a major treatment fork.|nooption
48141|Hiro|Dog|Heartworm-treatment anxiety planning for a dog that must stay calm for months|1|The most important question here was how to keep a heartworm-positive dog safely calm through restricted activity.|The discussion clarified doxycycline dosing, reinforced the rescue-led heartworm plan, and explored chronic anxiety support because exercise restriction was making the behavior problem worse.|options,staged,risk,barrier,rep
49705|Junie|Dog|ACL-tear visit with surgery-versus-rest decision making|0|This was a clear decline-triggered pivot from the ideal orthopedic fix to the realistic conservative path.|The veterinarian explained why surgery is the definitive repair, named the age-and-cost tradeoff openly, and then offered strict rest, long-term pain control, and trazodone support as the fallback plan.|options,money,pay,alt,staged,risk,rep
49707|Looper|Dog|Foreign-body vomiting with home-versus-hospital monitoring branch|1|The veterinarian used imaging first and then framed the next decision around where supportive care should happen, not around whether the problem was real.|The discussion identified likely fleece in the colon, contrasted overnight hospitalization versus home monitoring after fluids and anti-nausea therapy, and set clear red flags for escalation.|options,staged,risk,rep
49710|Howard|Dog|Moderate THC ingestion with home-versus-hospital fluid support|1|The veterinarian kept the owner out of panic mode by separating scary appearance from truly catastrophic toxicity.|The discussion contrasted subcutaneous fluids and home monitoring against IV hospitalization, while explaining when coma-level deterioration would change the plan.|options,staged,risk,min
49725|Maple|Dog|Onion-toxicity decontamination follow-up with serial CBC monitoring|1|This was mostly a poison-control follow-up where the plan was already fixed by what had been vomited up.|The veterinarian reviewed normal organ values, highlighted Heinz-body anemia monitoring, and directed timed CBC checks with the regular vet rather than introducing a new care branch.|risk,nooption
49726|Chloe|Cat|Acute pleural-effusion heart failure with chest tap versus humane euthanasia discussion|1|This was a high-stakes branch point where the veterinarian was explicit about both intervention limits and prognosis.|The conversation used x-rays to distinguish pleural effusion from pulmonary edema, explained why cats are harder to manage when fluid sits outside the lungs, and laid out chest tap care versus euthanasia.|options,staged,risk,rep
49727|Pippa|Dog|Doberman heart-failure visit with outpatient medication versus inpatient diuresis|1|The veterinarian framed this as early enough to try, but only with realistic survival expectations.|The discussion compared starting pimobendan and diuretics as outpatient management versus keeping the dog hospitalized to drain fluid and stabilize before discharge.|options,money,staged,risk,rep
49728|Kuiper|Cat|Shallow-breathing kitten with x-ray-first workup and optional enema left off|1|The veterinarian used imaging to rule out cardiac and pulmonary disease before calling this a constipation-dominant problem.|The discussion moved from whether x-rays were necessary to confirming a clean chest and then recommending monitoring after the owner declined an enema.|options,staged,risk,min
52952|Bodie|Dog|Post-neuter scrotal hematoma with empiric treatment after culture was skipped|1|The plan stayed practical after a mouth-contaminated incision opened, and culture became secondary to protecting the wound.|The veterinarian extended carprofen, added antibiotics, recommended icing and calm confinement, and accepted the owner choice to skip culture.|risk,nooption
52953|Buster|Dog|Bilateral ear infection with home foam therapy instead of a longer-acting clinic-only option|1|The conversation matched treatment to what the owner could realistically do at home.|The veterinarian compared a five-day foam-pump ear medication against a longer-acting in-clinic option, then paired the chosen home route with pain guidance using carprofen already on hand.|options,staged,min
52956|Blu|Dog|Suspected open pyometra with antibiotics-first plan under financial constraint|0|This was a clear case where the safer definitive path was named, but a lower-cost bridge plan was still allowed because the cervix appeared open and the dog was still stable.|The veterinarian explained emergency ovariohysterectomy versus trying antibiotics first, named the surgery cost directly, and set firm worsening triggers if the medical path failed.|options,money,pay,alt,staged,risk,rep
52958|Stella|Cat|Hematuria workup that pivoted from UTI rule-out to likely bladder cancer with spread|1|The veterinarian moved stepwise from common causes to much more serious disease once ultrasound and x-rays changed the picture.|The discussion contrasted stone versus cancer, offered specialist referral versus supportive care, and explained why the recurrent UTI pattern now looked secondary to a bladder tumor.|options,staged,risk,rep
53834|Addie|Dog|Lethargy and weight-gain visit with anti-inflammatory trial versus expanded thyroid panel|1|The veterinarian did not overcall borderline thyroid numbers and instead framed a reasonable lower-cost first step.|The discussion compared an anti-inflammatory trial against sending the full thyroid panel right away, while explaining why truly hypothyroid dogs are usually more clearly abnormal than this.|options,money,staged,risk,min
53853|Dudu|Dog|Fall-related front-limb soreness with x-ray versus pain-medication approach|1|The veterinarian matched the plan to a patient that was already improving and weight-bearing.|The discussion noted that x-rays were available but leaned toward pain support and monitoring because the dog was already peeing, pooping, and using the limb better.|options,staged,risk,min
53867|Buddy|Dog|Small-dog limping episode with patella explanation and conservative pain plan|1|The veterinarian treated intermittent limping like a patellar problem first, not a rush-to-surgery problem.|The discussion explained kneecap instability, offered pain control now, and reserved surgery plus blood work for cases that became chronic or needed longer medication use.|options,staged,risk,min
53914|Cindy|Dog|Paw abscess that was opened and bandaged with routine aftercare|1|This was an acute focal problem with a direct treatment path rather than a broader options conversation.|The encounter centered on lancing the abscess, bandage care, antibiotics, and a simple recheck timeline.|nooption
53940|Belle and Aura|Dog|Pair wellness visit with loose-stool follow-up and no major treatment branching|1|This was largely a routine multi-pet visit where alternatives were not really the issue.|The discussion focused on normal exams, diet transition, and routine maintenance rather than on a meaningful spectrum-of-care decision.|nooption
53973|Selene and Michael|Cat|Paired preventive follow-up centered on parasite control and minor concerns|1|This was mostly a preventive follow-up without a true care-path split.|The discussion stayed on stool quality, mild ear follow-up, and preventive parasite coverage rather than on affordability or staged treatment tradeoffs.|nooption
54001|Lewey|Dog|Hip-dysplasia consult with surgery, injections, and pain-control branches|1|This was a strong spectrum-of-care conversation organized around outcome expectations and price sensitivity.|The veterinarian compared FHO versus total hip, discussed ongoing pain control with amantadine and Librela, and added traveling-surgeon steroid injections as the non-surgical middle path.|options,money,pay,staged,risk,rep
55291|Cooper|Dog|Rabies-only preventive visit with no meaningful treatment branching|1|This was a straightforward preventive visit where alternatives were not really the issue.|The discussion focused on a single rabies update and routine wellness check-in.|nooption
55395|Daisy|Dog|GI-recovery follow-up with return to normal food and no new branching|1|This was a recheck confirming improvement rather than a fresh options conversation.|The discussion centered on successful return to the regular diet and ongoing observation after a resolved GI episode.|nooption
55459|Jasmine|Dog|Arthritis-maintenance visit with dental quote and skin-tag cleanup planning|1|The veterinarian kept the chronic pain plan steady while adding a sensible dental-and-mass cleanup option.|The discussion continued Librela, refilled gabapentin for travel stress, and built a dental quote that included removing the more suspicious skin tag for histopathology.|options,money,staged,risk
55615|Rainy|Cat|Feline herpes eye flare with stain-first check and delayed vaccination until recovery|1|The veterinarian used minimum necessary intervention and protected the cat from getting vaccinated through an active flare.|The discussion ruled out corneal ulcer, used ointment plus lysine, and postponed FVRCP until the eyes and nasal signs had settled.|options,staged,risk,min
55826|Hopper|Dog|Chronic hip pain visit with x-ray optional and Rimadyl management choice|1|The veterinarian treated age-related hip pain as a medication-management problem first, not an imaging-first problem.|The discussion allowed x-rays if desired, but leaned toward baseline blood work and flexible once- versus twice-daily Rimadyl dosing based on the dog's bad days.|options,staged,risk,min
55827|Hopper|Dog|Duplicate-like chronic hip pain visit with the same Rimadyl-first framing|1|This duplicate-like capture preserves the same age-related hip-pain logic rather than changing the coding read.|The discussion again kept x-rays optional and focused on chronic pain control with blood-work monitoring for ongoing Rimadyl use.|options,staged,risk,min
55899|Candle|Dog|Painful intact female with CPL-first blood work that led to closed-pyometra surgery|1|The veterinarian started with the most informative blood test, then escalated appropriately once the picture sharpened.|The discussion moved from pancreatitis-versus-obstruction reasoning to x-rays that revealed a large closed pyometra requiring hospitalization before surgery.|options,staged,risk,rep
55934|Dewey|Dog|Chronic anal-gland irritation with short Apoquel course and supplement support|1|The veterinarian reframed the problem as an itch-cycle rather than only a gland-expression problem.|The discussion paired ear cleaning and gland evaluation with short-course Apoquel and a gland supplement to reduce the lick-itch-release loop.|options,staged,risk,min
56715|Daisy Mae and Honey Noel|Dog|Older multi-dog wellness visit with dental, echo, and chronic-monitoring logistics|1|This was mostly preventive maintenance, but the veterinarian still staged how cardiac screening should line up with dental planning.|The discussion kept one dog in watchful monitoring, linked echo timing to dental safety, and noted that recent blood work could save money on pre-anesthetic labs.|options,money,pay,staged
56795|Daisy|Dog|Localized lick lesion with cone-first management instead of expensive itch drugs|1|The veterinarian deliberately chose the smaller intervention because the problem area was limited.|The discussion recommended a cone and continued local care first, with a direct warning that full anti-itch medications are not cheap and may be unnecessary for one small spot.|options,money,pay,min
57051|Boss|Dog|Annual vaccine catch-up with optional Lepto and minor odor concern|1|This was mostly preventive care and record cleanup rather than a true options conversation.|The veterinarian reviewed which vaccines were actually due and handled the remaining questions as minor maintenance issues.|nooption
57125|Oliver|Cat|Senior cat follow-up with cheaper medication sourcing and oral-mass planning|1|The veterinarian paired practical cost navigation with clear explanation that the mouth lesion eventually needs a procedure.|The discussion compared medication sourcing through Costco, reviewed constipation management, and explained that biopsy or removal would require a scheduled sedated surgery day.|options,money,pay,pharmacy,staged,risk
57194|Logan|Dog|Arthritis-medication maintenance with lowest-effective-dose coaching|1|This was ongoing chronic-care management rather than a fresh options conversation.|The veterinarian used prior blood work to keep the plan simple and coached the owner on tapering to the lowest effective anti-inflammatory schedule.|nooption
57249|Maverick|Dog|Quick infected-skin recheck with another short antibiotic course|1|This was a short recheck where the plan was already narrowed to finishing the infection control.|The discussion focused on how many more antibiotic doses to use after rapid improvement.|nooption
57290|Prince|Dog|Ear-and-skin follow-up with cheaper refill logistics and watchful care|1|This was more logistics than a true medical branching conversation.|The veterinarian discussed ongoing itch monitoring and highlighted that the website auto-ship route was cheaper for the needed products.|money,pay,pharmacy,nooption
59701|Gibson|Dog|Vomiting-and-wobbliness visit with pancreatitis blood work as the first branch|1|The veterinarian started with the test most likely to answer the GI question without overcommitting to a larger workup.|The discussion framed pancreatitis blood work as the first step while leaving other explanations open if the screening did not fit.|options,staged,risk,min
59722|Bamboo|Dog|Ear-bleeding case with cytology-guided medication and scheduled recheck|1|This was a focused infection visit with a direct treatment path.|The encounter centered on cytology, oral antibiotics, medicated ear solution, and a fixed recheck interval.|nooption
59735|Tango|Dog|Persistent hematuria with ultrasound-guided urine workup for UTI, stone, or tumor|1|The veterinarian used a stepwise diagnostic frame instead of retreating to another blind antibiotic round.|The discussion moved from prior antibiotic failure to ultrasound and cystocentesis so the next treatment could be based on what was actually in the bladder.|options,staged,risk,rep
59743|Remy|Dog|Patellar-luxation consult with x-ray optional and surgery reserved for frequent limping|1|The veterinarian named the surgical fix but did not oversell it when the pattern still sounded intermittent.|The discussion explained the kneecap problem, offered x-rays for completeness, and set frequency of limping as the threshold for moving toward surgery.|options,staged,risk,min
59744|Felicia|Cat|Facial-swelling visit with pain relief and likely dental-source management|1|This was a concentrated problem visit without a broad options set.|The discussion centered on examining the swollen area and sending home pain medication while the source lesion declared itself more clearly.|nooption
62538|Guinness and Shannon|Dog|Older multi-dog vaccine visit with itch restart and murmur-stage explanation|1|The veterinarian kept the preventive visit moving while still adding a meaningful next-step branch for the newly heard murmur.|The discussion covered restarting itch control, defining echo as the next step for the murmur, and respecting the owner's choice to decline broader blood work today.|options,staged,risk
62580|Minnie|Dog|Lip-wound recheck with watchful care versus added gabapentin|1|The veterinarian let the improving wound stay on the small-plan track and made the extra pain control optional.|The discussion framed gabapentin as a calmness-and-pain add-on only if the current anti-inflammatory plan stopped being enough.|options,staged,min
62638|Drax|Dog|Seasonal itchiness visit with pill-versus-shot cost comparison|1|This was a clean cost-and-duration tradeoff discussion.|The veterinarian compared a faster pill option against a longer-acting injection, explained which path was cheaper over different time horizons, and let the owner choose based on expected season length.|options,money,pay,staged,rep
62639|Drax|Dog|Duplicate-like seasonal itchiness visit with the same pill-versus-shot cost logic|1|This duplicate-like capture preserves the same duration-and-cost tradeoff without changing the read.|The discussion again compared the quicker pill response with the longer but sometimes more cost-effective shot.|options,money,pay,staged,rep
62649|Pepper|Dog|Allergy-prone follow-up with topical option versus diet-only wait-and-see|1|The veterinarian kept the next step small and owner-controlled.|The discussion compared trying a local product now against waiting to see whether the diet shift alone improved the chronic skin issue.|options,staged,min
62760|Khloe|Dog|Senior wellness visit with lump workup and dental-cost timing|1|The veterinarian sequenced the bigger future decisions instead of trying to do everything in one day.|The discussion framed aspiration or surgery as the next step for growing lumps and explained that current blood work could make a dental cheaper if scheduled within three months.|options,money,pay,staged
62761|Khloe|Dog|Duplicate-like senior wellness visit with the same lump-and-dental timing logic|1|This duplicate-like capture keeps the same sequencing of lump evaluation and future dental planning.|The discussion again tied present blood work to cheaper later dental care and treated the lumps as separate next-step decisions.|options,money,pay,staged
62794|Ivy|Dog|Annual follow-up with food, tartar, water-intake, and spay-site questions|1|This was mainly a broad wellness conversation rather than a true options visit.|The encounter focused on maintenance questions and routine interpretation of changes rather than on a new staged treatment branch.|nooption
63281|Bailey|Cat|Senior cat dental planning with February discount timing|1|The veterinarian used the owner's timing question to stage when the dental should happen rather than pushing immediate anesthesia.|The discussion explained that the mouth issue could wait if eating stayed normal, noted the February dental-month discount, and set earlier intervention as the trigger if chewing worsened.|options,money,pay,staged
63282|Bailey|Cat|Duplicate-like senior cat dental planning with the same timing logic|1|This duplicate-like capture preserves the same wait-versus-sooner dental reasoning.|The discussion again kept February scheduling on the table while setting earlier loss of appetite as the threshold to accelerate.|options,money,pay,staged
63321|Hope|Dog|Grooming-associated scabby rash with medicated mousse instead of antibiotics|1|The veterinarian recognized an irritated skin reaction without overcalling it an infection.|The discussion ruled out obvious infection, linked the timing to grooming and licking, and chose medicated mousse as the first intervention.|options,staged,min
63370|Buster|Dog|Anxious vaccine visit with mild lameness and behavior-limited exam|1|This was mostly a behavior-limited preventive visit rather than a usable options conversation.|The discussion stayed on giving the due vaccines and acknowledging mild forelimb limping without getting far enough for a full staged plan.|barrier,nooption
63377|Tank|Dog|Annual visit with murmur staging and optional heartworm retest|1|The veterinarian turned a routine vaccine visit into a practical monitoring plan for the newly relevant heart issue.|The discussion explained echo staging for chronic valvular disease and added a send-out heartworm retest as a reasonable option because the prior preventive history was imperfect.|options,staged,risk
63473|Stella|Cat|Bladder recheck that shifted from feared cancer to resolved inflammatory change plus lung-nodule referral|1|The veterinarian updated the picture honestly once the bladder normalized and kept the remaining concern on the lung nodule.|The discussion ruled the bladder back toward inflammatory disease, then offered CT or specialty consultation to work up the incidental lung lesion instead of pretending it no longer mattered.|options,money,staged,risk
63507|Newt|Dog|Behavior-medication follow-up with simple monitoring only|1|This was a monitoring check where the current plan was working and no new branch was needed.|The encounter focused on improved behavior and the fact that recent blood work made additional testing unnecessary today.|nooption
63657|Max|Dog|Eye-irritation recheck with bilateral treatment and another planned follow-up|1|This was a narrow follow-up where the plan was already set and only needed a small adjustment.|The discussion centered on eye medication use in both eyes and the nuisance of needing one more recheck.|nooption
63826|Oakley|Dog|Nail-trim and urinary-case visit shaped heavily by short-term finances|1|This was a good example of cost changing when and how care happened, even without changing the medical goal.|The discussion weighed sedating for nails now versus waiting until more money was available or sending gabapentin and trazodone home first, then proceeded once the urinary piece also needed attention.|options,money,pay,alt,staged,barrier
63890|Daisy|Dog|Blood-work recheck with calm continuation of the existing plan|1|This was a stable follow-up without a new care branch.|The veterinarian reviewed the persistent but unsurprising lab abnormalities, kept the current schedule, and reassured the owner that nothing new looked worrisome.|nooption
64076|Jasper|Dog|Vomiting diabetic with megaesophagus and chest-xray question for aspiration|1|The veterinarian triaged the immediate metabolic risk first and left the larger imaging question in reserve.|The discussion explained that ketones were reassuring, reviewed insulin timing around vomiting, and kept chest x-rays available if aspiration or pneumonia looked more likely.|options,staged,risk,min
64156|Milli|Dog|Longstanding squealing and kneecap problem with surgery only as a later threshold|1|The veterinarian treated this as a chronic patella-pattern case, not an emergency.|The discussion emphasized that surgery exists but only becomes worth pursuing if the frequency or severity crosses a more meaningful line.|options,staged,min
64221|Coco|Dog|New puppy establishment visit with deworming skepticism and early spay counseling|1|The veterinarian avoided reflex deworming and instead tied treatment to evidence and breed-size context.|The discussion preferred a fecal-guided GI plan over blind deworming, then explained why early spay timing is less risky in toy dogs than in larger breeds.|options,staged,risk,min
64311|Mishio|Cat|Post-hematuria recheck with straightforward improvement confirmation|1|This was a short recheck confirming that the acute problem had settled.|The discussion focused on eating, weight, and the fact that the cat was no longer urinating blood.|nooption
64312|Mishio|Cat|Duplicate-like post-hematuria recheck with the same improvement read|1|This duplicate-like capture keeps the same simple recovery picture.|The discussion again confirms no further urinary blood and a stable recheck status.|nooption
64698|Bubba|Dog|Chronic soft-stool visit with strict GI Biome trial and hydration check|1|The veterinarian tied the recurrence to too many food changes and built a narrow reset rather than a scattershot plan.|The discussion favored a strict prescription GI Biome trial, minimizing homemade add-ons, and using the dog's hydration status to avoid overreacting on day one.|options,staged,min
64823|Tracy|Dog|Post-dental and urinary-accident follow-up with monitoring plus optional cancer screening|1|The veterinarian resisted overtesting once recent lab work and the exam made the biggest fears less likely.|The discussion linked the raw vulvar area to irritation and stool, kept the skull prominence in watchful monitoring, and mentioned the newer cancer screen only as an optional next step.|options,staged,risk
64930|Taki|Dog|Forelimb lameness visit with arthritis-versus-xray framing|1|The veterinarian kept the decision simple around whether this looked age-related enough to treat empirically.|The discussion weighed x-rays against managing it like early arthritis because the soreness showed up more after exertion than at rest.|options,staged,min
64970|Sammy|Dog|Stick-through-mouth injury with conservative healing instead of sedated repair|1|The veterinarian explained why doing less was actually safer here.|The discussion noted that the mouth heals well, reserved sedation and stitching as an in-theory option, and leaned toward recheck-only management because the wound location was already behaving well.|options,staged,risk,min
65005|Chip|Dog|Senior wellness visit with allergy choices and murmur workup timing|1|The veterinarian balanced the owner's wish to keep today narrow with honest guidance on what the next medical steps should be.|The discussion compared Cytopoint versus medicated shampoo for allergies, respected the decision to defer blood work, and explained echo staging before starting murmur medication.|options,staged,risk
65079|Poly|Cat|Acute respiratory-change visit with xray-first triage for heart failure versus other chest disease|1|This was an imaging-first stabilization discussion, not guesswork.|The veterinarian explained the two different ways cardiac cats can fill with fluid and used x-rays as the necessary next step before talking about drainage or prognosis.|options,staged,risk,rep
65292|Tazmin|Dog|Neck-pain visit where x-rays were intentionally deprioritized|1|The veterinarian explained why better response to anti-inflammatories mattered more than a low-yield spine xray.|The discussion treated this like a pain-and-inflammation problem first, with imaging reserved because the dog was already improving on carprofen.|options,staged,risk,min
65293|Tazmin|Dog|Duplicate-like neck-pain visit with the same anti-inflammatory-first reasoning|1|This duplicate-like capture preserves the same logic about low-yield imaging and good medication response.|The discussion again keeps x-rays off the front burner because the neck pain was already improving on treatment.|options,staged,risk,min
65368|Kane|Dog|Hunting-related interdigital splinter abscess with flush and field restriction|1|This was a focused foreign-body visit with a direct treatment path.|The discussion centered on pulling remaining splinter material, flushing the tract, considering antibiotics, and keeping the dog out of the field until the foot sealed.|risk,nooption
65369|Kane|Dog|Duplicate-like hunting splinter visit with the same direct treatment path|1|This duplicate-like capture keeps the same interdigital foreign-body read.|The discussion again focused on removing remaining splinter material and keeping the foot out of hunting until it healed.|risk,nooption
65370|Kane|Dog|Third duplicate-like hunting splinter visit with the same foot-care logic|1|This duplicate-like capture does not materially change the coding read from the other Kane files.|The discussion again centers on foreign-body removal, flushing, and temporary activity restriction while the foot seals.|risk,nooption
65471|Coco|Dog|Late-life re-establishment visit with staged vaccine and testing costs|1|This was a routine senior restart visit, but the owner was explicitly spacing care out for budget reasons.|The discussion spread vaccines, future heartworm testing, and routine senior blood work across separate visits so cost stayed manageable.|money,pay,staged,nooption
65498|Zoet|Dog|Seizure-medication recheck with phenobarbital-level monitoring and refill logistics|1|This was a controlled recheck where the current plan mainly needed dose verification.|The discussion focused on phenobarbital level monitoring, safe refill timing, and the fact that there had been no new seizures.|nooption
67462|Bentley|Cat|Diabetes voicemail follow-up with dose-stay versus dose-increase choice|1|Even in a short callback, the veterinarian framed the decision around the cat's real-world control instead of the number alone.|The message contrasted leaving the dose alone versus increasing it, then tied the choice to weight trend and clinical signs rather than fructosamine in isolation.|options,staged,min
67486|Oliver|Cat|Severe skin-lesion recheck with euthanasia versus continuing effective antifungal care|1|This was a meaningful survival-quality conversation that still recognized visible improvement.|The veterinarian acknowledged euthanasia as understandable, but pointed to wound closure and disappearing nodules as reason to continue the antifungal path with appetite support.|options,staged,risk,rep,barrier
67487|Oliver|Cat|Duplicate-like skin-lesion recheck with the same continue-versus-euthanasia discussion|1|This duplicate-like capture preserves the same prognosis conversation and visible improvement.|The discussion again weighs humane euthanasia against staying with the antifungal path because the lesions are finally closing and shrinking.|options,staged,risk,rep,barrier
67595|Kristina|Cat|Corneal-ulcer recheck with stain confirmation and likely medication taper|1|This was a healing recheck where the next step depended on whether stain proved the surface was truly closed.|The discussion used one more eye stain to confirm healing, continued the current medications, and explained that pain medicine could probably stop if the eye remained sealed.|options,staged,risk,min
67661|Gibson|Cat|First-cat wellness visit with FeLV-FIV testing explained against cost and indoor status|1|The veterinarian turned ambiguous rescue paperwork into a concrete indoor-cat decision rather than assuming prior testing happened.|The discussion compared in-house versus send-out testing costs, explained why a one-time negative matters even for an indoor cat, and paired that with deferred fecal screening.|options,money,pay,staged,risk
67757|Oliver|Cat|Post-dental and URI follow-up with benign wait-and-watch lesion guidance|1|This was mainly a successful recheck where the veterinarian named the likely benign explanation and set a size-based trigger for action.|The discussion confirmed return to dry food, improving respiratory signs, and why the pigmented lesion near the rear could simply be monitored unless it started growing fast.|min,nooption
67878|Bam|Dog|Chronic itch and anxiety visit with OTC-first steps and GoodRx fluoxetine option|1|This was a layered spectrum-of-care conversation spanning both skin and behavior.|The discussion started with ear checks and Benadryl for mild itchiness, walked through common food allergens, and then compared in-house fluoxetine against taking a written script elsewhere to shop price.|options,money,pay,pharmacy,staged,barrier
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 11',
      date: '2026-03-18',
      selectionSeed: '20260318-wave11',
      selectionMethod: 'Eleventh non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1100_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
