window.ANDY_ANALYSIS_BATCH15 = (() => {
  const rows = `
146339|Leo|Dog|Daycare bite and rib-wound visit managed with direct wound care and a narrow medication plan|1|The veterinarian kept the plan proportional because the injury already dictated a straightforward path.|The discussion centered on checking for deeper puncture damage, controlling pain, and using simple wound management rather than opening unnecessary branches.|staged,risk,min,nooption
147043|Bubbles|Dog|Progressive hind-end weakness visit with home support, rehab, and mobility-aid options|1|The veterinarian built a practical mobility spectrum instead of pretending one treatment would solve a chronic decline.|The discussion moved across harness support, amantadine, rehab options, and possible wheels or neurology follow-up for a dog likely facing ongoing spinal or orthopedic disease.|options,staged,risk,rep
147206|Boo|Dog|Hypertension recheck with a second medication added to a still-manageable plan|1|The veterinarian tightened the blood-pressure plan without overcomplicating a case that still fit outpatient management.|The discussion stayed on adding medication, monitoring response, and rechecking rather than opening a wider workup immediately.|staged,min,nooption
147213|Nasni|Dog|Runny-nose visit using OTC allergy medication before stepping up to antibiotics|1|The veterinarian used a cheaper low-intensity first step because the signs still fit irritation more than true infection.|The discussion recommended generic cetirizine, refill support, and watching for more infectious-looking discharge before escalating the plan.|options,pharmacy,staged,risk,min
147311|Kitty|Cat|Urinary-diet recheck with stress-colitis reasoning and dental disease noted for later|1|The veterinarian kept the immediate problem small while still naming the next issue that would eventually need attention.|The discussion framed the stool change as stress-related, used simple probiotic support, and left the painful tooth for a future dental rather than forcing everything into one visit.|staged,min,nooption
147330|Maru|Dog|Routine preventive visit with vaccines and bloodwork but no meaningful illness branch|1|This was a maintenance encounter rather than an affordability or option-setting case.|The conversation stayed on routine wellness tasks and did not open a substantive treatment-path decision.|nooption
147381|Diesel|Dog|Routine wellness visit with benign-lump review and no active treatment fork|1|The veterinarian kept the encounter in preventive-care territory because there was no real medical crisis to solve.|The discussion focused on ordinary wellness care, stable body findings, and reassurance rather than on competing treatment paths.|nooption
147426|Carmen|Dog|Itchy-paws and ear visit with allergy control and diet-path discussion|1|The veterinarian used common outpatient options before pushing a bigger workup for a chronic skin problem.|The discussion paired Apoquel support with food-choice reasoning and home management in a way owners could realistically follow.|options,staged
147432|Clark|Cat|Severe weight-loss visit with anemia, organ-disease concern, and life-or-death next-step framing|1|The veterinarian was explicit about the stakes while still laying out a real spectrum of immediate choices.|The discussion moved across blood work, transfusion-level concern, transfer logic, and prognosis-sensitive decision making for a medically unstable cat.|options,staged,risk,rep
147448|Tyson|Dog|Elbow-lesion and dental-planning visit kept on a modest outpatient track|1|The veterinarian treated the skin problem directly and kept the larger dental issue for planned follow-through.|The discussion stayed on local care, medication support, and later dental or mass-removal planning rather than on an emergency-style escalation.|options,staged
147460|Artemis|Dog|Forelimb-laceration visit with local repair first and heavier intervention only if needed|1|The veterinarian matched the procedure to what the wound and patient would likely tolerate.|The discussion used local lidocaine, simple closure, and a drain-or-sedation fallback only if the wound proved deeper or harder to manage than expected.|options,staged,risk,min
147678|Chico and Zeke|Dog|Two-dog preventive visit without a meaningful treatment-options branch|1|This was a stable wellness encounter where alternatives were not the core issue.|The discussion stayed on routine preventive care and ordinary behavior notes for two otherwise healthy dogs.|nooption
147720|Meyer|Dog|Small-skin-lesion visit managed conservatively with topical care and time|1|The veterinarian kept the plan narrow because the lesion looked minor and already partly resolved.|The discussion focused on a simple topical approach and ordinary follow-up rather than any costly intervention.|staged,min,nooption
147879|Clover|Dog|Routine vaccine and screening visit without a real treatment-path decision|1|This was preventive maintenance rather than a live cost-of-care conversation.|The visit stayed on vaccines and normal screening with no substantive alternative-path counseling.|nooption
147886|Clover|Dog|Routine preventive follow-up without a meaningful options discussion|1|This capture also read as straightforward maintenance care.|The discussion remained in vaccine and preventive territory rather than opening a broader treatment branch.|nooption
147991|Walter|Dog|Interdigital-cyst visit with local care, antibiotics, and recurrence watchouts|1|The veterinarian used practical home-management options while still acknowledging that the diagnosis could shift.|The discussion balanced topical care, oral medication, cone-style protection, and the possibility that fungal or deeper causes could still be in play.|options,staged,risk
148082|Leo|Cat|Urinary-diet follow-up with treat and prescription-food choices discussed openly|1|The veterinarian made the chronic diet plan workable instead of presenting only one rigid feeding rule.|The discussion allowed alternate urinary-diet formats and safe treat options while keeping stone prevention central.|options,staged,min
148135|Poppy|Dog|Post-fall hind-limb visit with conservative luxating-patella management first|1|The veterinarian resisted overcalling the orthopedic findings and kept surgery in reserve.|The discussion framed the problem around monitoring, supplements, and escalation only if function worsened beyond a mild patella issue.|options,staged,risk,min
148201|Copper|Dog|Routine preventive care without a meaningful tradeoff conversation|1|This was a simple wellness encounter rather than an options-heavy case.|The discussion stayed on vaccines and ordinary preventive tasks with no real affordability branch.|nooption
148992|Renee|Dog|Marked-lymph-node visit using aspirates and chest films to separate cancer from inflammation|1|The veterinarian built the workup around a clear differential instead of skipping straight to one explanation.|The discussion used stepwise diagnostics and explicit cancer risk framing while keeping the first moves in general practice.|options,staged,risk,rep
149092|Callie|Dog|Chronic-arthritis maintenance visit without a major new branch|1|The veterinarian treated the visit as ongoing management rather than a fresh cost-of-care negotiation.|The discussion stayed on chronic support and routine follow-up rather than on competing plans.|staged,nooption
149131|Lily mar|Dog|Anal-gland-abscess visit handled with direct cleaning, medication, and home protection|1|The veterinarian kept the plan small because the abscess already dictated what had to happen next.|The discussion focused on flushing, antibiotics, cone use, and healing support rather than on broader alternatives.|staged,risk,min,nooption
149193|Astrid|Dog|Serious-eye-disease follow-up balancing inflammatory versus fungal pathways|1|The veterinarian kept multiple disease explanations alive and tied treatment intensity to that uncertainty.|The discussion used pressure checks, medication tapering, and clear warning signs to explain why the eye could not simply be watched casually.|options,staged,risk,rep
151012|Mama|Cat|Lower-urinary-sign visit using an injection-first plan when sampling and pills were impractical|1|The veterinarian found a workable first step for a cat that was not lending itself to a cleaner diagnostic plan.|The discussion contrasted injectable treatment with oral medication and kept the immediate plan tightly focused on likely urinary inflammation or infection.|options,staged,min
151065|TT|Cat|Tail-and-back pain visit with medication first and imaging only if recovery stalled|1|The veterinarian used the least invasive useful step before opening a larger orthopedic workup.|The discussion paired gabapentin with recheck logic and left radiographs for a cat that failed to improve over the next week.|options,staged,min
151206|Penny|Dog|Routine preventive visit with no meaningful alternatives branch|1|This was a standard vaccine-and-screening encounter rather than a live affordability discussion.|The conversation stayed on routine care and did not develop into a treatment-spectrum case.|nooption
151407|Sakura|Dog|Hind-limb-stiffness visit using anti-inflammatory support before bigger escalation|1|The veterinarian treated the mobility change like a manageable first-pass orthopedic problem.|The discussion used medication and watchful follow-up around likely patella or mild pain issues instead of jumping to a high-intensity workup.|options,staged,min
151588|Penny|Dog|Poor-appetite and vomiting visit with in-house versus send-out bloodwork priced transparently|1|The veterinarian made the diagnostic tradeoff visible and let cost affect speed rather than whether care happened at all.|The discussion compared faster in-house testing against cheaper send-out testing, added anti-nausea support, and used pale-gum concern to justify bloodwork now.|options,money,pay,staged,risk,rep
151598|Dio|Dog|Dog-bite wound visit using local repair and chest x-rays only if the attack pattern warranted it|1|The veterinarian used injury details to decide whether a bigger trauma workup was necessary.|The discussion contrasted simple wound treatment against the added step of thoracic imaging if the dog had been shaken, then stayed on local closure, pain control, and antibiotics.|options,staged,risk,min
151737|Penny|Dog|High-liver-value callback pointing toward ultrasound and possible liver surgery|0|The veterinarian was candid about cancer risk while still offering a general-practice versus specialty sequencing choice.|The discussion framed send-out ultrasound, in-clinic ultrasound, and specialty referral as the next fork after severe liver abnormalities rather than pretending the answer was already known.|options,staged,risk,rep
151997|Gage|Dog|GI-history intake that cut off before a usable doctor-owner plan emerged|1|This file did not preserve enough of the actual recommendation sequence to code a real options discussion confidently.|The available text stayed in history-taking around vomiting, diarrhea, diet, and yard habits without capturing a full exam-room decision path.|nooption
152365|Emme|Dog|Vomiting-and-diarrhea visit with imaging available but supportive care still central|1|The veterinarian treated the case as a common GI problem while still naming the foreign-body fork that would matter if the dog worsened.|The discussion moved across radiographs, probiotics, anti-nausea care, and monitoring rather than assuming immediate surgery or hospitalization.|options,staged,risk,rep
152544|Susie|Cat|Sneezing-cat visit linking nasal discharge to probable dental-root disease|1|The veterinarian used a medically conservative first step while still naming the more definitive dental explanation.|The discussion paired antibiotic support now with the likelihood of later dental work if the one-sided nasal signs recurred or persisted.|options,staged,risk,rep
152556|Frannie|Dog|Acute forelimb-limp visit with meds first and x-rays reserved for nonresponders|1|The veterinarian matched the plan to a likely soft-tissue injury rather than treating it like a fracture by default.|The discussion centered on rest, medication, and a short watch period before imaging if the dog failed to improve.|options,staged,risk,min
152580|Lauren|Dog|Small-axillary-lump visit managed with monitoring before sedated sampling or removal|1|The veterinarian kept the first move proportionate because the lump still fit a benign superficial process.|The discussion used tracking and delayed intervention rather than immediate surgery for a lesion that did not yet justify it.|options,staged,min
156791|Tyler|Dog|Acute-GI-upset visit treated supportively with stool testing and symptom control|1|The veterinarian kept the plan at the minimum useful level because the dog still fit an outpatient stomach-upset picture.|The discussion focused on anti-nausea support, probiotics, and fecal testing without opening a bigger workup unless the dog failed to improve.|staged,risk,min,nooption
156850|Luna|Dog|Vaccine-site swelling visit distinguishing abscess from sterile inflammatory reaction|1|The veterinarian used cytology logic to decide between antibiotics and steroids instead of guessing.|The discussion contrasted infectious versus inflammatory explanations, adjusted medication strategy around pill-giving failure, and even named future vaccine avoidance if this kept recurring.|options,staged,risk,rep
157083|Dudley|Dog|Limp and reactivity visit combining paw care, pain control, and behavior support|1|The veterinarian treated the dog as both an orthopedic and management problem shaped by anxiety.|The discussion moved across topical paw care, as-needed anti-inflammatory use, and the option of long-term Prozac-style support for a dog whose reactivity affected daily life.|options,staged,risk,barrier
157283|Penny|Dog|UTI and hypertension recheck with kidney-versus-Cushings reasoning kept open|1|The veterinarian treated overlapping chronic problems stepwise rather than forcing one label too early.|The discussion used antibiotics, blood-pressure medication, GI Biome discussion, and later Cushing's testing as a staged path through a messy senior-dog picture.|options,staged,risk,rep
157326|Hiccup|Dog|Routine annual and vaccine visit without a substantive tradeoff discussion|1|This remained a maintenance visit rather than a real options encounter.|The conversation stayed on routine preventive care and stable concerns without opening a broader care-spectrum branch.|nooption
157368|Leo|Cat|Stress-related overgrooming discussion without a larger diagnostic fork|1|The veterinarian treated the case as a familiar behavior-context issue rather than an affordability problem.|The encounter stayed in reassurance and routine management territory with no major alternative-path discussion.|nooption
157421|Sam|Dog|Severe chronic-ear visit with cytology-guided treatment and allergy control options|1|The veterinarian tailored treatment to what the ear actually showed instead of flattening the case into one generic plan.|The discussion moved across Cytopoint, ear cleaning, foam therapy, and allergy-background reasoning in a way that balanced practicality with chronic-disease honesty.|options,staged,risk,rep
157637|Kelly|Dog|Bloody-urine visit handled as a straightforward UTI with recheck|1|The veterinarian kept the case narrow because the urinalysis already gave a usable answer.|The discussion focused on antibiotics and follow-up urine testing rather than on a larger care-spectrum conversation.|staged,nooption
157707|Luna|Dog|Likely-toxin or ingestion case with outpatient versus hospitalization logic|1|The veterinarian gave the owner a real spectrum between home support and more intensive care.|The discussion paired fluids, bloodwork, and monitoring with the option of stronger hospitalization-level management if the dog failed to turn around.|options,staged,risk,rep
157774|Pufdy|Cat|Chronic-vomiting cat framed as IBD versus GI lymphoma with biopsy held in reserve|1|The veterinarian named the hard diagnostic truth while still offering a realistic treatment-first path.|The discussion combined empirical steroids, Fortiflora, diet logic, and the reminder that only biopsy could fully separate the main chronic gut diagnoses.|options,staged,risk,rep
157877|Cuero|Dog|Tail-base itch visit kept on a modest allergy-relief plan|1|The veterinarian used the smallest useful plan because the problem still fit uncomplicated itch management.|The discussion stayed on Cytopoint, minor topical support, and routine follow-up rather than on a bigger workup.|staged,min,nooption
157975|Mocha|Dog|Allergy and diet counseling visit without a major treatment-path fork|1|This was mostly chronic-care maintenance rather than an affordability conversation.|The discussion centered on ear care, diet triggers, and routine guidance without a substantial branching decision.|staged,nooption
158115|Cairo|Dog|Routine wellness visit with food and raw-diet counseling but no real illness branch|1|The veterinarian kept the encounter in preventive territory and used it mainly for guidance.|The discussion stayed on vaccines, feeding choices, and routine screening rather than on a substantive treatment alternative.|nooption
160647|Chocoli|Dog|Possible-back-pain versus seizure event handled with conservative spine-first management|1|The veterinarian treated the likely back-pain problem while still naming the neurologic fallback if another event happened.|The discussion explained why x-rays would add little, paired rest with anti-inflammatory and nerve-pain medication, and set clear watch points for future seizure concern.|options,staged,risk,rep
160754|Chloe|Dog|Excitement-collapse visit distinguishing syncope from seizure and staging next steps|1|The veterinarian avoided overcalling the episodes while still treating them as potentially serious cardiac events.|The discussion used bloodwork now, Holter monitoring later, and trigger-based escalation rather than one reflexive diagnosis.|options,staged,risk,rep
160858|Daisy and Mabel|Dog|Two-dog preventive visit without a meaningful illness-options branch|1|This was a routine wellness encounter rather than a cost-of-care negotiation.|The discussion stayed on ordinary preventive maintenance for both dogs.|nooption
160927|Milo|Dog|Pink-eye visit with stain-guided treatment and a very small home-care plan|1|The veterinarian kept the care narrow because the eye still fit a simple conjunctivitis-type problem.|The discussion centered on ruling out a scratch, using ointment, and supportive compresses without a broader workup.|staged,min,nooption
161502|Rocky|Dog|Senior-dog swelling and weakness visit using lymph-node aspirates before stronger conclusions|1|The veterinarian treated the dramatic swelling as something that needed immediate clarification, not blind symptomatic continuation.|The discussion contrasted infection and cancer, explained why the NSAID had likely only reduced inflammation, and used in-house lymph-node sampling as the next responsible fork.|options,staged,risk,rep
162433|rigatoni|Unknown|Internal or demo-style transcript that does not function like a real exam-room case|1|This file does not read like a usable owner-facing care conversation.|The available text behaves more like a demo or internal example than a coherent transcript suitable for nuanced option coding.|nooption
162442|rigatoni|Unknown|Second demo-like file without a usable live care discussion|1|This capture likewise does not support a real affordability analysis.|The file reads like another nonstandard or internal example rather than an owner-facing exam-room conversation.|nooption
165818|Finn|Dog|Gagging and gulping visit using x-rays to separate irritation from something worse|1|The veterinarian used imaging to rule out the dangerous version while still keeping treatment outpatient.|The discussion paired normal neck films with acid-reduction and anti-nausea therapy instead of escalating to invasive care immediately.|options,staged,risk,rep
165820|Isabella|Dog|Swollen-paw visit treated as inflammation with simple home-management support|1|The veterinarian kept the plan intentionally small because the paw still fit an uncomplicated local reaction.|The discussion stayed on topical care, cone use, and medication support rather than on a larger diagnostics path.|staged,min,nooption
166085|Meadow|Dog|Wellness visit with recurring patella counseling and ordinary preventive care|1|The veterinarian used a familiar orthopedic issue to reinforce staged care rather than to push surgery.|The discussion kept luxating-patella management on a conservative track while routine preventive care stayed in the foreground.|options,staged,min
166165|Snow|Cat|Severe-IMHA-flare visit using immediate CBC results to restart aggressive treatment|1|The veterinarian moved quickly but still kept the plan structured around what had worked before.|The discussion paired steroid restart with a longer-term companion medication, named transfusion as the fallback if the cat worsened, and used repeat CBC monitoring to judge response.|options,staged,risk,rep
166254|Charles|Dog|Head-tilt and vomiting visit balancing vestibular disease against ear infection|1|The veterinarian treated the likely causes in parallel without overbuilding the workup.|The discussion used anti-nausea support, antibiotics, and time as the main tools while explaining why idiopathic vestibular disease often improves on its own.|options,staged,risk
166402|Huey|Dog|Routine preventive visit with optional cancer-screen add-on priced explicitly|1|This was mostly a maintenance visit, but the veterinarian still surfaced an elective screening decision and its cost.|The discussion stayed in routine wellness territory, with the only real branch being whether the owner wanted to add a cancer-screening test at a stated price.|money,nooption
166722|Joycie|Cat|Constipation visit with imaging, fluids, and escalation based on severity|1|The veterinarian used x-rays to decide how hard to push treatment instead of assuming the problem was mild.|The discussion moved across outpatient support and more intensive cleanout logic for a constipated cat that still needed careful triage.|options,staged,risk,rep
167195|Brady|Dog|Routine vaccine and maintenance visit without a substantive options branch|1|This was a straightforward preventive encounter.|The conversation stayed on routine care and did not develop into a meaningful treatment-path discussion.|nooption
167211|Gamja|Dog|Breeding consult that laid out natural, AI, and timing-based reproductive options|1|The veterinarian gave the owner a real menu of paths rather than collapsing the case into one breeding method.|The discussion compared insemination approaches, timing, and practical logistics in a clearly staged way.|options,staged
167334|Wyatt|Dog|Severe chronic-ear case with a cheaper jump-start plan discussed directly|1|The veterinarian was unusually explicit about cost while still making the medical limits clear.|The discussion paired a roughly hundred-dollar starter plan with pain control, anti-nausea support, and the reality that the dog's long-term ear disease could still require more than that.|options,money,staged,risk,rep
167421|Gus|Dog|Routine vaccine visit without a meaningful treatment alternatives discussion|1|This remained a maintenance encounter rather than a cost-of-care case.|The conversation stayed on standard preventive tasks and stable findings.|nooption
167455|Talia|Dog|Recurrent post-trauma nasal swelling treated again before needle sampling|1|The veterinarian kept the next move conservative but named the trigger that would justify sampling.|The discussion reused antibiotics and anti-inflammatories, tracked size with photos, and reserved aspiration for swelling that refused to settle fully.|options,staged,risk,rep
167494|Cena|Dog|Acute bloody-diarrhea visit managed supportively with fluids and GI medications|1|The veterinarian used a minimum-responsible outpatient plan because the dog still looked systemically okay.|The discussion stayed on supportive care, hydration, and what would force hospitalization rather than on a broader workup right away.|staged,risk,min,nooption
167533|Finch|Cat|Chronic-GI cat with ultrasound evidence shifting the case toward lymphoma|1|The veterinarian became more definitive without pretending the prognosis was good.|The discussion used ultrasound findings, anemia, doubled steroid therapy, and limited prognosis language to frame a supportive but realistic plan.|options,staged,risk,rep
167965|rigatoni|Unknown|Nonstandard example transcript that does not behave like a real exam-room visit|1|This file is not useful for nuanced affordability coding.|The available text reads like a demo or synthetic capture rather than a normal owner-facing conversation.|nooption
168025|Selene|Dog|Routine wellness visit with minor dental and post-spay questions only|1|This stayed in maintenance care and did not become a meaningful options conversation.|The discussion focused on ordinary preventive and home-care questions with no broader care-spectrum fork.|nooption
169457|Akira|Cat|Very short routine visit with rare cough concern and urine follow-up mention|1|This file was too thin to support a richer options analysis beyond noting a largely routine encounter.|The available text captured a minor cough concern, routine rabies care, and urine handling without a full branching recommendation sequence.|nooption
169558|Vida|Dog|Foreign-body concern with barium study, exploratory surgery, and supportive care compared directly|1|The veterinarian made both the medical uncertainty and the financial implications clear.|The discussion contrasted repeat x-rays, a barium study, surgery, and continued supportive care while keeping the owner's appetite to act part of the decision.|options,money,pay,staged,risk,rep
169599|Vida|Dog|Same-episode foreign-body visit ending in exploratory surgery being chosen|1|The veterinarian again tied the medical picture to a concrete costed decision rather than hiding the stakes.|The discussion reviewed barium testing versus surgery, walked through likely surgical costs, and ultimately moved toward operating because the guessing game had reached its limit.|options,money,pay,staged,risk,rep
169731|Beau|Dog|Panting and throat-clearing visit using OTC allergy medication before anything bigger|1|The veterinarian picked a cheap, low-friction first step because the signs still fit mild upper-airway irritation.|The discussion recommended generic cetirizine, tied the clearing to possible nasal drainage, and kept the visit in outpatient monitoring territory.|options,pharmacy,staged,min
169752|Urla|Dog|Lip-fold irritation visit managed with pain control and simple cleaning rather than a larger workup|1|The veterinarian kept the plan small because the problem still looked superficial and manageable.|The discussion used Rimadyl, baby wipes or warm compresses, and reassurance rather than pushing diagnostics for a lesion that fit local irritation.|staged,min,nooption
169874|Rudy|Dog|Acute-lameness visit treated symptomatically before jumping to radiographs|1|The veterinarian respected how often these impact injuries are soft-tissue problems without hiding the x-ray fallback.|The discussion centered on rest, injectable pain relief, and imaging only if the dog failed to improve over the next few days.|options,staged,risk,min
170054|Bentley|Dog|Routine wellness and weight-management counseling visit|1|This remained a preventive and lifestyle-focused encounter rather than a true cost-of-care branch.|The discussion stayed on calories, treats, exercise, and routine prevention with no major treatment fork.|nooption
170070|Iggy Mae|Dog|Senior-arthritis visit that also surfaced dental and cardiac-risk planning|1|The veterinarian found a reasonable first step for pain while being explicit about the pre-anesthetic heart workup needed later.|The discussion used anti-inflammatory treatment now, explained the newly heard murmur, and connected dental or mass-removal surgery to an echo-first safety plan and estimate request.|options,money,staged,risk,rep
170676|Lizzie|Cat|Congested-senior-cat visit with injection treatment and likely dental follow-through later|1|The veterinarian used the familiar URI pattern to justify a practical first move without hiding the dental source concern.|The discussion paired an antibiotic injection with bloodwork and the warning that recurrent symptoms would likely mean the infected teeth needed attention.|options,staged,risk,rep
170848|Kazu|Cat|Bladder-tumor palliative-management visit using symptom support rather than risky sampling|1|The veterinarian stayed honest about the limits of treatment while still assembling a comfort-focused plan.|The discussion worked through why sampling was hard, used whatever urine could be obtained, and sent the cat home with appetite support, pain medication, and bladder-wall supplements as realistic management tools.|options,staged,risk,rep
170978|Katie|Dog|Paw-pad laceration visit managed without stitches because the tissue should heal well|1|The veterinarian explained why the simpler path was good enough even though a more procedural option existed.|The discussion compared stitching against wrapping and antibiotics, then leaned into the path that best fit paw-pad healing and the dog's likely tolerance.|options,staged,risk,min
171035|Booger|Dog|End-stage orthopedic decline visit pairing pain-control escalation with euthanasia planning|1|The veterinarian was willing to discuss the endgame plainly while still offering one more medication step first.|The discussion kept chronic Rimadyl in place, introduced amantadine, declined repeat x-rays as low value, and then walked through euthanasia logistics and pricing for a dog nearing the limit of supportive care.|options,money,staged,risk,rep
171116|Ragz|Dog|Back-pain flare visit using steroids and more frequent gabapentin because NSAIDs were off the table|1|The veterinarian built around the owner's existing meds rather than pretending the case started from zero.|The discussion explained why steroids and NSAIDs could not be combined, increased gabapentin frequency, and framed recovery as a multiweek rest-and-taper process.|options,staged,risk,rep
171117|Odie|Dog|Boarding-time bloody-diarrhea case where hospitalization was discussed and outpatient care chosen|1|The veterinarian offered a more intensive option, then translated the case into a reasonable outpatient backup when that path was declined.|The discussion contrasted hospitalization against fluids, metro, probiotics, and bland-diet support, with clear warnings about lethargy and worsening signs.|options,alternativeOnDecline,staged,risk,min
171229|Bear|Dog|Vomiting-after-bone visit using x-rays first and supportive care once obstruction looked unlikely|1|The veterinarian used imaging to earn the right to stay outpatient rather than guessing.|The discussion contrasted radiographs against pure symptomatic treatment, then used anti-nausea medication and fluids when the x-rays did not show a clean obstructive story.|options,staged,risk,rep
171268|Bama|Dog|Routine rabies and preventive-maintenance visit without a real treatment fork|1|This was a standard wellness encounter rather than an options conversation.|The discussion stayed on vaccines, heartworm prevention, and routine maintenance tasks.|nooption
171370|Jack|Dog|Vomiting and hematochezia visit with x-rays used to rule out the scary version|1|The veterinarian treated the case as a significant GI flare but still kept the therapy outpatient once the images supported that choice.|The discussion moved across pancreatitis concern, splenic cancer fear, intestinal-wall changes, fluids, anti-nausea therapy, and GI medications rather than assuming the dog needed immediate hospitalization.|options,staged,risk,rep
171412|Milton|Dog|Routine annual visit with ordinary vaccines and screening only|1|This remained a straightforward preventive-care appointment.|The conversation stayed on maintenance care and did not open a substantive care-spectrum branch.|nooption
171438|Iggy Mae|Dog|Follow-up phone call after Galliprant GI side effects forced a new arthritis plan|1|The veterinarian pivoted honestly once the preferred stomach-sparing drug still caused trouble.|The discussion stopped Galliprant, used metronidazole for the immediate GI upset, and held out Librela or gabapentin as the arthritis-management alternatives once the stomach settled.|options,staged,risk,rep
171481|Spencer|Cat|Weight-loss visit with bloodwork and urine panel used to sort kidneys, thyroid, and crystals|1|The veterinarian widened the workup just enough to answer the real reasons a senior cat might be thinning down.|The discussion justified the more complete panel, kept crystal and kidney diet questions in view, and used Fortiflora as a lower-friction supportive add-on for a cat with chronic sniffles and vomiting history.|options,staged,risk,rep
171772|Amber|Cat|New-adoption URI visit managed with lysine, time, and stress reduction|1|The veterinarian treated the congestion as a stress-linked viral flare rather than forcing an antibiotic answer.|The discussion explained feline herpes-style URI dynamics, used supportive care and timing, and kept new-home stress central to both treatment expectations and introduction advice for the resident cat.|staged,risk,min,nooption,barrier
171835|Jojo|Dog|Chronic-back-pain and dental-follow-up visit centered on refills and planned maintenance|1|This was mainly a chronic-management check rather than a live affordability negotiation.|The discussion stayed on as-needed muscle-relaxer refill, dental planning, and trachea-support context without opening a major new treatment branch.|nooption
172242|Bean|Dog|Dental-disease consult in a dog with heart and liver concerns requiring echo-first caution|1|The veterinarian made the anesthesia-risk gating explicit rather than pretending the infected teeth could simply be fixed today.|The discussion contrasted an echocardiogram-first pathway against long-term symptom management, used oral antibiotics as a temporary bridge, and scheduled the cardiac workup as the gatekeeper for future dentistry.|options,staged,risk,rep
172394|Lincoln|Dog|Urinary-stone prevention recheck with cheaper prescription-diet options discussed openly|1|The veterinarian answered the owner's affordability question by naming lower-cost food alternatives instead of defending only the current brand.|The discussion compared urinary diets, kept urine pH central to the choice, and promised a script that would let the owner shop across brands rather than remain locked into one.|options,money,staged
172507|Wrigley|Dog|Hot-spot recheck and new in-house peeing issue framed around household disruption|1|The veterinarian treated the urine problem as a behavior-context issue shaped by the new foster dog, not as a mysterious medical emergency.|The discussion interpreted the accident pattern through social stress, recommended in-home training resources, and kept the healing hot spot on a simple maintenance track.|options,barrier
172671|Ghost|Dog|IMHA hospitalization transfer with transfusion, long recheck cadence, and prognosis discussed plainly|1|The veterinarian balanced immediate stabilization with a realistic explanation of how long this disease can dominate a household.|The discussion walked through blood typing, transfusion goals, medication strategy, likely recheck cadence, and long-term uncertainty without pretending the process would be quick or cheap.|options,staged,risk,rep
172788|Aria|Dog|Rabies-only vaccine visit without a meaningful medical branch|1|This was a simple preventive task rather than an options conversation.|The discussion stayed on the rabies shot and tag logistics with no larger treatment-path issue.|nooption
173034|Ruby|Dog|Red-eye visit using stain-first logic before steroid-style treatment|1|The veterinarian explained why the eye had to be sorted into ulcer versus irritation before the soothing plan could be chosen.|The discussion contrasted allergies and conjunctivitis with a corneal cut, then used staining as the gate before moving to more soothing therapy.|options,staged,risk,min
173118|Spencer|Cat|Kidney-disease callback using diet change first and fluids reserved for progression|1|The veterinarian gave the owner a practical chronic-kidney plan that still respected the cat's crystal and heart history.|The discussion moved from worsening creatinine to a combined kidney-and-crystal diet, future anemia watch, and eventual subcutaneous fluids only if the numbers kept climbing.|options,staged,risk,rep
  `;

  const flagMap = {
    options: 'optionsOffered',
    money: 'explicitMoneyLanguage',
    decline: 'explicitDeclineInquiry',
    alt: 'alternativeOnDecline',
    pay: 'payRelatedOption',
    staged: 'stagedTradeoff',
    pharmacy: 'pharmacySavings',
    risk: 'riskExplained',
    min: 'minimumResponsible',
    nooption: 'noOptionButAppropriate',
    rep: 'representative',
    barrier: 'barrierDetected',
    alternativeOnDecline: 'alternativeOnDecline'
  };

  function createTags() {
    return {
      optionsOffered: false,
      explicitMoneyLanguage: false,
      explicitDeclineInquiry: false,
      alternativeOnDecline: false,
      payRelatedOption: false,
      stagedTradeoff: false,
      pharmacySavings: false,
      riskExplained: false,
      minimumResponsible: false,
      noOptionButAppropriate: false,
      representative: false,
      barrierDetected: false
    };
  }

  const transcripts = rows.trim().split('\n').map((line) => {
    const [id, pet, species, visit, accepted, takeaway, notes, flagText] = line.split('|');
    const tags = createTags();
    const flags = flagText ? flagText.split(',').filter(Boolean) : [];

    flags.forEach((flag) => {
      const key = flagMap[flag];
      if (key) tags[key] = true;
    });

    return {
      id,
      pet,
      species,
      visit,
      firstRecommendationAccepted: accepted === '1',
      takeaway,
      notes,
      tags,
      transcriptPath: `3-8-jason.szumski copy/Transcripts/${id}-transcript.txt`
    };
  });

  return {
    meta: {
      title: 'Andy Hand-Coded Batch 15',
      date: '2026-03-19',
      selectionSeed: '20260319-wave15',
      selectionMethod: 'Fifteenth non-overlapping 100-transcript hand-coded batch from the Transcripts folder using the uncoded backlog manifest.',
      memoPath: 'Andy_1400_Transcript_Analysis.md',
      ids: transcripts.map((item) => item.id)
    },
    transcripts
  };
})();
